### ISSUE TITLE
A cookie associated with a cross-site resource was set without the `SameSite` attribute

### ISSUE THREAD

**Issue by timc986** [iconify/iconify#10]
Got this warning message in Chrome, wondering if its going to be an issue in the future?

> A cookie associated with a cross-site resource at http://iconify.design/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Environment:
Angular 8.2.0
Chrome 78.0
Windows 10
iconify 1.0.3

Thanks a lot

**Comment by cyberalien** [comment]
Thanks for noticing. It seems to be new Chrome notice that appears on pretty much every website.

I'm not a fan of tracking, so Iconify doesn't use any cookies and doesn't track anyone.

That cookie notice is not from Iconify, but from CloudFlare. There is nothing I can do about that. There are some threads on CloudFlare forum about it, like this one: https://community.cloudflare.com/t/new-chrome-warning-about-digitrust-cookie-cloudflare-is-setting/118690 so maybe CloudFlare staff will do something about it.

If you really want that cookie or notice to be gone, there are few options:
1. Try including script from cdn.jsdelivr.net or host it on your server or bundle it with webpack. However this approach will still load icons from API that is also routed through CloudFlare so you'll get cookies from that unless you bundle all icons.
2. Host your own API instance. Then you'll have full control over everything. See https://github.com/iconify/api.js and https://github.com/iconify/api.php
3. Use Iconify for React or Iconify for Angular. Those components do not use Iconify script and do not use Iconify API, instead icons are bundled during build process. So your project will not be accessing any external websites, thus no extra cookies.
