### ISSUE TITLE
Iconify React required "fr" attribute

### ISSUE THREAD

**Issue by pearcake** [iconify/iconify#100]
Hi,
It seems that Iconify React types have type error that makes "fr" param on Icon component required
Is that a bug or intentional?

Cheers

**Comment by cyberalien** [comment]
I've looked at file generated by build script, that attribute is there. It shouldn't be. Looks like `React.forwardRef` is causing API Extractor to generate weird code.

Thanks for reporting, I'll find a way to fix that.

**Comment by cyberalien** [comment]
I think I've fixed it. Can you please test it?

I didn't publish it as `latest` yet in case fix won't work. Install latest version of component using `npm install @iconify/react@test` and please post here if that fixes issue for you.

**Comment by pearcake** [comment]
Wow, that was quick!
Yep, error is gone now. 
Thanks for quick response and this great project, happy New Year!

**Comment by cyberalien** [comment]
Thanks!

Happy New Year to you too!

I'll keep this issue open until I do more testing to make sure there are no surprise side effects from this fix.

**Comment by cyberalien** [comment]
Tested changes in project using Vite + TS. Confirmed bug in old version and confirmed that fix works correctly.
