### ISSUE TITLE
Need fallback in the event of 404 errors on API

### ISSUE THREAD

**Issue by karlcarstensen** [iconify/iconify#103]
Need a way to specify an Icon fallback when an issue occurs, such as an API change, so that the icons degrade gracefully. 

As an example, these icons were working last week, but are now getting a 404 without any other information provided. 

https://api.iconify.design/exclamation.json?icons=circle
https://api.unisvg.com/exclamation.json?icons=circle
https://api.simplesvg.com/exclamation.json?icons=circle

https://api.iconify.design/arrow.json?icons=down
https://api.unisvg.com/arrow.json?icons=down
https://api.simplesvg.com/arrow.json?icons=down

**Comment by cyberalien** [comment]
Those icons weren't working last week either. There are no such icons. You probably used custom icons with names `exclamation-circle` and `arrow-down` but misplaced code that added data for those icons.

Icons are never removed from Iconify, so fallback functionality isn't really needed. If icon set author removes an icon, it is marked as hidden, so it no longer shows up in icons list, but data is still available.

However, if you do need fallback icon, you can can create some fallback functionality using `loadIcons` function: https://docs.iconify.design/icon-components/svg-framework/load-icons.html That function will be called on both success and failure, so you can change icon name on failure.

**Comment by karlcarstensen** [comment]
Ahh, apologies you're correct, it is indeed some legacy code from Font Awesome that wasn't updated properly.

And thanks for the additional information about the `loadIcons` function, that is really helpful. Enjoying this icon component very much! Super useful.
