### ISSUE TITLE
Missing "type": "module" from package.json

### ISSUE THREAD

**Issue by TeemuKoivisto** [iconify/iconify#106]
Hey, first off - nice library! I have been using this library as a replacement for react-icons in my SvelteKit project. Which has its bugs and issues but this time, I think the reason it fails seems justified.

So SvelteKit is using Vite to resolve its dependencies which so far has worked somewhat ok with iconify (bundling has been slow). Yet with the latest minor Vite version 2.7 I had to change my iconify imports from `  import menu from '@iconify-icons/mdi/menu'` to `  import menu from '@iconify-icons/mdi/menu.js'` as the app wouldn't otherwise build which I thought was weird. The reason came apparent as each time I start my app this error is thrown:

```
0] 15.19.04 [vite] Error when evaluating SSR module /src/routes/write/__layout.reset.svelte:
[0] /Users/xxx/node_modules/.pnpm/@iconify-icons+mdi@1.1.42/node_modules/@iconify-icons/mdi/menu.js:6
[0] export default data;
[0] ^^^^^^
[0] 
[0] SyntaxError: Unexpected token 'export'
[0]     at Object.compileFunction (node:vm:352:18)
```

So as Vite tries to resolve the `.js` files inside `@iconify-icons/md` it automatically expects them to be CJS as the package.json does not contain `"type": "module"`. I'm still able to run my app despite the error, it's just the first render does fail and I have to revisit the page to reload it.

Simply adding `"type": "module"` ought to fix this.

**Comment by cyberalien** [comment]
Thanks for reporting!

I'll update all packages.

**Comment by cyberalien** [comment]
Done. Script is updating all packages, should take about 15 minutes to publish 100+ packages.

**Comment by TeemuKoivisto** [comment]
@cyberalien wow, awesome! Never has my issues been fixed this quick 😄. Resetted the imports to omit `.js` and can confirm the bug is gone!
