### ISSUE TITLE
Icons render an empty <span /> in React when using offline icons and the icon is used in another package

### ISSUE THREAD

**Issue by XFaonAE** [iconify/iconify#127]
I made a UI framework at https://github.com/skylixgh/nexts that uses @iconify/react and @iconify/icons-fluent.
When testing nexts in developer mode it works, but when I publish to NPM and install on my other apps, the iconify offline icons are just an empty span, i checked my builds and iconify's components and icons were imported correctly.
![image](https://user-images.githubusercontent.com/85759101/159139756-9bb536d7-f1e3-4b35-80ac-a8023230223f.png)
![image](https://user-images.githubusercontent.com/85759101/159139768-cbdfca24-be4b-466d-8e95-c80e5952d160.png)

**Comment by cyberalien** [comment]
I've looked at code, don't see any issues. Which command in which package should I run to test it?

**Comment by XFaonAE** [comment]
1) Run `npm i` from the root of Nexts
2) Run `npm run build:watch` from the root
3) cd into `./scratch` and run `npm i`
4) Run `npx nexts dev --name desk` from `./scratch`

You will see a simple NEXTS app and the icons are working

**Comment by XFaonAE** [comment]
The icons dont render in this app though. https://github.com/skylixgh/app
1) `npm i`
2) `npm run dev:desktop`

**Comment by cyberalien** [comment]
Thanks for instructions.

I've inspected elements in your app, icon component uses data loaded from Iconify API, not imported from `@iconify/icons-fluent` package. At least that's true for icons I see in navigation on left side. Normally that wouldn't be an issue, but its clearly not what you intended because `@iconify/icons-fluent` package is not used.

**Comment by XFaonAE** [comment]
The navigation uses the API icons due to my IDE having a stroke at that time. The titlebar uses offline icons because its in for production, and if the device is not connected to the internet, they would not know what to do. I also did try to install @iconify/react and @iconify/icons-fluent into skylixgh/app but nothing changed.

**Comment by XFaonAE** [comment]
The titlebar is rendered here https://github.com/SkylixGH/Nexts/blob/main/packages/desktop-uix/src/controls/app/App.tsx and the build imports and App.tsx imports look like this
![image](https://user-images.githubusercontent.com/85759101/159140836-b86a46f5-8159-462f-b9d8-2bbe50cf3882.png)
I'm not sure thats wrong here, when using ReactDevTools to see the icon component, the only data seems to be the body, i'm not seeing hidden, width, or height

**Comment by cyberalien** [comment]
I'm trying to debug `app` repository. After replacing `node_modules/@iconify/react` with debug component and running `npm run dev:desktop` nothing changes. Removing `.nexts` does not change anything. Is there anything special I need to do to correctly recompile it?

**Comment by XFaonAE** [comment]
If you modify node_modules and save it, the electron app should restart, I also noticed my BuildTool doesnt want to place node_modules cache in the correct location, you may notice `apps/desktop/node_modules/.vite` that is where the cache is, and the compiled version of the UI, you may want to try modifing builds via that file

**Comment by XFaonAE** [comment]
Restarting `dev:desktop` should also help

**Comment by cyberalien** [comment]
Still can't get it to refresh. Replaced icon component with one that renders `<i>` element with debug data instead of `<span>` to make sure it re-renders, re-checked all files in component to make sure there are no traces of `span` anywhere, but still getting empty `<span>`.

Steps:
- In `apps/desktop/node_module` remove `.vite`
- In root directory remove `.nexts`
- `npm run dev:desktop` (closing it before trying whole process again)

Old component still seems to be cached somewhere.

**Comment by XFaonAE** [comment]
This refresh issue seems to be something with ViteJS, but one hacky idea I have is to
1) Shut down the dev server
2) Find `node_modules/@nexts-stack/desktop-uix/package.json` and update both exports to `./src/index.ts` and set the main to `./src/index.ts`
3) Execute the dev server and now when you update code in the src of that package, the UI will find out and recompile the TS

**Comment by cyberalien** [comment]
Found why icon is not rendered. This is value of `icon` attribute that is passed to component:

`{"__esModule":true,"default":{"body":"<rect width=\"10\" height=\"1\" x=\"3\" y=\"7.5\" fill=\"currentColor\" rx=\".5\"/>"}}`

Which means something in bundler handles defaults exports from CommonJS modules incorrectly.

There are two solutions:
- Find where bug is. Most likely some configuration option that deals with CommonJS.
- Switch from `@iconify/icons-fluent` to `@iconify-icons/fluent`. It is identical module, but with ES exports.

**Comment by XFaonAE** [comment]
![image](https://user-images.githubusercontent.com/85759101/159142465-55e5d7f2-7739-4ae3-ad6d-17c418de6e7a.png)
Thats odd, its still happening

Here is what I did:
 1) I updated the package to @iconify-icons/fluent
 2) I published to NPM after confirming that the app at `./scratch` is working
 3) I deleted `node_modules` in skylixgh/app
 4) I updated all NEXTS packages and ran `npm i` in skylixgh/app

**Comment by XFaonAE** [comment]
Oh, I just relised that the other bug I fixed didnt even show up in `skylixgh/app` I am going to recheck the hashes and stuff to make sure NEXTS actualy got built

**Comment by XFaonAE** [comment]
Yup, the new function I implemented before publish didn't show up

**Comment by XFaonAE** [comment]
NPM is still indexing the files and data, maybe thats why my IDE says the hashes didnt match

**Comment by XFaonAE** [comment]
Thank you so much!! The issue is fixed.
*By the ways, iv'e never had this good of an experience opening an issue on any repo, everyone else takes a long time or rejects the issue if they even miss a small detail, thanks!*

**Comment by XFaonAE** [comment]
![image](https://user-images.githubusercontent.com/85759101/159142903-c268f0ef-022b-482f-b9bd-21505c9df31a.png)
