### ISSUE TITLE
Can not connect to server https://code.iconify.design/

### ISSUE THREAD

**Issue by D-Mino** [iconify/iconify#13]

**Comment by cyberalien** [comment]
Can you post results of traceroute?

**Comment by D-Mino** [comment]
<img width="664" alt="Screen Shot 2020-02-05 at 22 42 33" src="https://user-images.githubusercontent.com/23691343/73857040-e8ef0a80-4868-11ea-8b20-4eb4b90dc80c.png">

**Comment by cyberalien** [comment]
Looks like a temporary outage at CloudFlare DNS in few regions. Website is up and working fine, issue is with CloudFlare.
