### ISSUE TITLE
icon-park version problem

### ISSUE THREAD

**Issue by PeyFon** [iconify/iconify#133]
![image](https://user-images.githubusercontent.com/60815493/159653533-c0edfb6a-79d5-4817-9d78-013431cd34c2.png)
![image](https://user-images.githubusercontent.com/60815493/159653596-f1e2247a-9726-43e1-a19d-0aff7b7ea5a8.png)
The new version has changed the default style

**Comment by cyberalien** [comment]
Thank you for reporting.

Update script retrieved version number from wrong `package.json` file. It used file in root directory, but correct version number is in `packages/svg/package.json`.

**Comment by PeyFon** [comment]
Hope to update soon.  Thank you very much

**Comment by PeyFon** [comment]
> Thank you for reporting.
> 
> Update script retrieved version number from wrong `package.json` file. It used file in root directory, but correct version number is in `packages/svg/package.json`.

Hope to update soon. Thank you very much

**Comment by cyberalien** [comment]
It will be fixed on next update, which is in 2 days.

The only thing that needs fixing is version number. All icons are already up to date.

**Comment by cyberalien** [comment]
It was fixed in yesterday's update.
