### ISSUE TITLE
iconExists() always return false if loadIcons() is not called

### ISSUE THREAD

**Issue by ducbh62git** [iconify/iconify#138]
I'm trying to check if the icon exists like the document in Reactjs:
https://docs.iconify.design/icon-components/react/icon-exists.html

My code:
```
import { iconExists, loadIcons, Icon } from "@iconify/react";

const icon = "emojione:locked-with-pen";
const Test = () => {
  loadIcons([icon]);
  return <Page title="TEST">{iconExists(icon) && <Icon icon={icon} />}</Page>;
};
```

If I don't call `loadIcons()` then `iconExists()` always returns false. 

Does it require `loadIcons()` to call first to cache the icon ?

**Comment by cyberalien** [comment]
I think you misunderstood function's purpose. It doesn't check if icon exists on API, it checks if icon exists in component's data storage.

So if icon is not loaded, `iconExists()` will return false. 

Also your usage of `loadIcons()` in your code is incorrect. It is not a synchronous function, icon will not be loaded immediately and next `iconExists()` will likely return false too.

**Comment by ducbh62git** [comment]
@cyberalien  thank you, sir
I got it

**Comment by Coinhexa** [comment]
> I think you misunderstood function's purpose. It doesn't check if icon exists on API, it checks if icon exists in component's data storage.
> 
> So if icon is not loaded, `iconExists()` will return false.
> 
> Also your usage of `loadIcons()` in your code is incorrect. It is not a synchronous function, icon will not be loaded immediately and next `iconExists()` will likely return false too.

so If I wanted to check if an icon exists in the API and return a fallback icon if it doesnt then how do I go about it?

**Comment by cyberalien** [comment]
> so If I wanted to check if an icon exists in the API and return a fallback icon if it doesnt then how do I go about it?

There is no function for that because I think it is not needed. What would be a use case for that function?
