### ISSUE TITLE
Feature Request: SVG Sprites Mode

### ISSUE THREAD

**Issue by AdsonCicilioti** [iconify/iconify#139]
This goes for all code implementations of icons with Iconify:

See the following scenario:
![image](https://user-images.githubusercontent.com/6278398/157615987-06aad70e-3dfe-4c80-8e07-212bc0bd419f.png)

Where the icon (svg code) is repeated multiple times and makes the code bloated.

It would be interesting to make use of Svg Sprites to optimize this.

**Comment by cyberalien** [comment]
Closing as solved.

For React there are 2 solutions now:

1. Web component mentioned above. For web component I've written a wrapper for React, which provides typings and maps `className` (used in React components) to `class` (used in web components) and allows to use `ref`. See https://docs.iconify.design/iconify-icon/react.html 

```bash
npm install --save-dev @iconify-icon/react
```

2. Also added this functionality to old React component too in version 4:

```bash
npm install --save-dev @iconify/react@next
```
