### ISSUE TITLE
Icons not showing bundled in Angular

### ISSUE THREAD

**Issue by whatdeheck** [iconify/iconify#14]
I have created a bundle file of some Icons as described in this article:
https://iconify.design/docs/icon-bundles/. Everything went fine with that. Now when I use those icons in a static HTML file like in the guide then everything works fine. If I start using the icons in for example a ngIf directive then they do not show, there is not error in the console. It just does not get replaced with the SVG. If I move away from the bundle file and to the online version then the icons start showing again.

**Comment by cyberalien** [comment]
Angular is a special case, it freaks out when something is happening to DOM.

I suggest to try Angular component instead: https://github.com/iconify/iconify-angular

**Comment by whatdeheck** [comment]
Actually the documentation says that it works well with Angular and as mentioned it does work with the online version that is why I am confused.

**Comment by cyberalien** [comment]
Can you try replacing Iconify with files from attached package?

[iconify-2.0.0-dev-20Mar20.zip](https://github.com/iconify/iconify/files/4358726/iconify-2.0.0-dev-20Mar20.zip)

If you are using Iconify as NPM package, replace files from `dist` with attached files. If you are including Iconify remotely, link to `iconify.min.js` from attached file.

Attached file is early alpha of Iconify 2.0. It was completely rewritten from ground up and handles icons differently. Maybe it will solve issue.

You will also need to change bundle a bit. In bundle file replace `SimpleSVG.addCollection` with `Iconify.addCollection`. It was legacy code to support old version. I'll replace it in tools package soon.

**Comment by whatdeheck** [comment]
I am sorry I was asked to move away from this task now, I hope I can get back to it not too long from today then I will give you some feedback. Thanks for looking into it
