### ISSUE TITLE
custom icon server, how to load icons

### ISSUE THREAD

**Issue by xiaoxian521** [iconify/iconify#142]
Hey, First of all thanks a lot for iconify this icon library it is very powerful!
I'm having some confusion with my custom icon server, as follows:

I use https://github.com/iconify/api.js , run locally
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/44761321/168538925-f8fd3f9c-a112-42ec-ad3d-86db0cb2fe38.png">
Then I want to load the icon using the icon component of online mode
`<Icon icon="mdi-light:home" />`
But I found that this address will actually be requested https://api.iconify.design
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/44761321/168539803-8346346c-e7b8-4052-adb0-ec860cc1fec9.png">
Can you provide an api to replace the resource address, this can have the same Properties as the online icon
<img width="837" alt="image" src="https://user-images.githubusercontent.com/44761321/168539630-c3ff9fa5-6d0c-40a8-aa36-a42a5d8549c0.png">

**Comment by cyberalien** [comment]
You need to change configuration for component to point to your API.

```js
import { addAPIProvider } from '@iconify/vue';

addAPIProvider('', {
	resources: ['http://localhost:3000'],
});
```

**Comment by xiaoxian521** [comment]
Thank you very much 🙏
