### ISSUE TITLE
Wrong Belgium flag icon in Circle Flag set

### ISSUE THREAD

**Issue by antoniogiroz** [iconify/iconify#146]
Hi!

This flag is wrong for Belgium:

```html
<Icon icon="circle-flags:be"  />
```

https://icon-sets.iconify.design/circle-flags/be/

However, the original set shows the right flag:

https://hatscripts.github.io/circle-flags/gallery (Search for "BE" or "Belgium")

Thanks!

**Comment by cyberalien** [comment]
Thanks for reporting.

Yes, that's a Belorussian flag. Must be a bug somewhere in import script.

**Comment by cyberalien** [comment]
Fixed.

Issue was caused by file `flags/language/be.svg` in icon set repository, which is a symbolic link pointing to `flags/by.svg` and it overrode import for `flags/be.svg`.
