### ISSUE TITLE
[Question] Render icon picker/library

### ISSUE THREAD

**Issue by IGMontero** [iconify/iconify#147]
Hey, first of all thank you for this amazing library.
One question, I wanted to know if it's possible to render a icon picker for the end-user, just like the one you have hosted on your website, so they can pick a icon from the entire library.

Thanks!

**Comment by cyberalien** [comment]
It was planned, but then I've messed it up by turning it into unmaintainable spaghetti code.

Currently in process of rewriting it all for the 3rd time, so it will take a while.

**Comment by cyberalien** [comment]
API has been rewritten, new version with icon search engine is available here: https://github.com/iconify/api

Documentation is available here: https://docs.iconify.design/api/ and it includes documentation for API queries, including queries needed for browsing/searching icons: https://docs.iconify.design/api/queries.html
