### ISSUE TITLE
How exactly does it work?

### ISSUE THREAD

**Issue by SoftCircuits** [iconify/iconify#148]
Can someone point me to an article that explains how the library works? How exactly does the JavaScript load just the requested icons?  Is the browser able to cache used icons? And how much overhead is involved in this process? Thanks.

**Comment by cyberalien** [comment]
Data is loaded from API. Documentation for API: https://docs.iconify.design/api/

Yes, there is cache.
1. API responses are cached in `localStorage` or `sessionStorage`, depending on configuration. By default its `localStorage`. See https://docs.iconify.design/iconify-icon/enable-cache.html 
2. If that fails, there is always browser cache. Displaying same page means loading same icons, so API queries are the same and are usually cached in browser.
