### ISSUE TITLE
Apply `customizations` before validation

### ISSUE THREAD

**Issue by equt** [iconify/iconify#149]
Currently, in the `getCustomIcon` function, there's a simple validation check for the passed in SVG source.

https://github.com/iconify/iconify/blob/5ab275c091244a7138ebbe0e715586ca339d9dd1/packages/utils/src/loader/custom.ts#L33-L38

This is right before the `customizations` get called. I personally think it might help much if the customizations are done **before** this mandatory check.

```ts
const { transform } = options?.customizations ?? {};

result = typeof transform === 'function' ? await transform(result, collection, icon) : result;

if (!result.startsWith('<svg')) {
  console.warn(`Custom icon "${icon}" in "${collection}" is not a valid SVG`);
  return result;
}
```

An example would be removing the `<?xml` like comment at the start of the SVG.

**Comment by equt** [comment]
It's an excellent UnoCSS config example, and I'm actually coming from UnoCSS to close the https://github.com/unocss/unocss/issues/959.

The issue claims that the leading comments would break the _tricky_ SVG encoding, and IIRC, it's pretty standard for design tools to add trademarks there. The error is not that obvious, so I believe we could do better here, e.g., trimming comments inside `customizations`.

Of course, it would be better if we do that in the https://github.com/iconify/iconify/blob/5ab275c091244a7138ebbe0e715586ca339d9dd1/packages/utils/src/svg/encode-svg-for-css.ts. This might not be a great approach, and since `preset-icons` deeply integrated with Iconify, any suggestions on that are appreciated.

**Comment by userquin** [comment]
@cyberalien @equt working on it...
