### ISSUE TITLE
title="my help text" doesn't work

### ISSUE THREAD

**Issue by serloi** [iconify/iconify#151]
Hello!

I'm using vue 3 and the arg "title" doesn't work
<Icon icon="bi:power" **title="DISCONNECT"**/>

I tried this too without the Icon component:
<span class="iconify" data-icon="bi:power" **title="DISCONNECT"**></span>
same thing..

I tried on Chrome and Edge.
On other html part in my vue file it works.

Do I doing something wrong?

Thank you for your help

**Comment by cyberalien** [comment]
I've just tested it with Vue 3 demo, title is passed correctly:

```vue
<Icon :icon="icon" color="red" title="Red icon" />
```

results in:
```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" title="Red icon" width="1em" height="1em" viewBox="0 0 20 20" style="color: red;"><path fill="currentColor" d="M10 9.25c-2.27 0-2.73-3.44-2.73-3.44C7 4.02 7.82 2 9.97 2c2.16 0 2.98 2.02 2.71 3.81c0 0-.41 3.44-2.68 3.44zm0 2.57L12.72 10c2.39 0 4.52 2.33 4.52 4.53v2.49s-3.65 1.13-7.24 1.13c-3.65 0-7.24-1.13-7.24-1.13v-2.49c0-2.25 1.94-4.48 4.47-4.48z"></path></svg>
```

There is also unit test in component for passing title property, it works fine too.

**Comment by serloi** [comment]
Thank you for your (quick) response :)
You're right, I have the title tag too in the html element...
So problem is elsewhere
Bye

**Comment by serloi** [comment]
After read some docs, I confirm that title doesn't work always with svg tag. (for me chrome et edge up to date)
some documentation: [here](https://css-tricks.com/svg-title-vs-html-title-attribute/)
also here: [https://www.dofactory.com/html/svg/title](https://www.dofactory.com/html/svg/title)

about this source:
```
<svg title="TITLE IN SVG" width="100" height="100">
  <!-- <title>TITLE ELEMENT UNDER SVG</title> -->  
  <circle cx="50" cy="50" r="40" stroke="steelblue" 
          stroke-width="2" fill="lightblue" />
</svg>
```

if I execute this: I have no help when I hover the mouse (I don't have "TITLE IN SVG")
if I desactivate comment, I have the text "TITLE ELEMENT UNDER SVG"

In my mind, Icon tag should generate a title tag under svg.. ?

**Comment by cyberalien** [comment]
It can be done, but it is not trivial. Problem is, that would require sanitising title tag, which adds to icon component size, so I'm not sure if it is a good idea.

Better approach is to switch to new web component: https://www.npmjs.com/package/iconify-icon

It is an upcoming replacement for current components, including Vue component you are using. It works much better than current Vue component because it separates rendering logic from framework.

Title attribute works correctly with web component.

**Comment by serloi** [comment]
Ok thank you I will try with iconify-icon
I just changed all my "el-icon" (element plus) vs "Icon" (iconify/vue) ...;)

**Comment by cyberalien** [comment]
Closing this issue.

Title, as well as all other accessibility attributes, work very well with web component. For older implementations it is not worth effort to add support for title, so best option is switching to web component.
