### ISSUE TITLE
pending updates on next branch

### ISSUE THREAD

**Issue by userquin** [iconify/iconify#153]
@cyberalien just a reminder before merging on master
- update root readme about installation, still with npm 
- include CONTRIBUTING.MD adding some hint about corepack 
- rename vitest scripts on utils package , for example using test:vitest-esm,  test:vitest-cjs and test:vitest for running esm and cjs 
- you should add a changelog gh hook to enable release notes from PR (just a suggestion)
- you should use main branch instead master, you can keep master if you want

**Comment by cyberalien** [comment]
Thanks!

Done most of it.

**Comment by cyberalien** [comment]
Done. Published stable versions of all packages and merged `next` to `main`.

All major rewriting done during last few months is now published on NPM with `latest` tag.
