### ISSUE TITLE
React testing in Jest enviornment using data-testid

### ISSUE THREAD

**Issue by nickfreemandesign** [iconify/iconify#154]
Hello and thanks for putting together such a cool library. I have some click events on Icons that were targeted using `data-testid` and `screen.getByTestId()` respectively, but after migrating to Iconify they don't seem to render in the Jest environment.

Rendering of the element containing Iconify, Jest is showing an output with an empty `<span/>` instead

deps:
```json
    "react-scripts": "5.0.1",
    "typescript": "^4.6.3"
    "react": "^18.1.0",
    "react-dom": "^18.0.0",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.1.1",
    "@testing-library/user-event": "^13.5.0",
```

`screen.debug()` in Jest:

```react.js
                  <th
                    class="MuiTableCell-root MuiTableCell-body MuiTableCell-alignLeft MuiTableCell-sizeMedium css-e1wn5e-MuiTableCell-root"
                    scope="row"
                    width="70px"
                  >
                    <span /> // <------ icon is in here
                  </th>
```

Rendering of the element in a web browser however, will show the SVG element with the `data-testid` appended as expected. 

```html
<svg 
  xmlns="http://www.w3.org/2000/svg" 
  xmlns:xlink="http://www.w3.org/1999/xlink" 
  aria-hidden="true" 
  role="img" 
  class="MuiBox-root css-5eyfm2 
  iconify iconify--eva" 
  data-testid="row-delete-1" <!-- element renders correctly in browser -->
  sx="[object Object]" 
  width="1em" 
  height="1em" 
  preserveAspectRatio="xMidYMid meet" 
  viewBox="0 0 24 24"> 
    <path fill="currentColor" d="M21 6h-5V4.33A2.42 2.42 0 0 0 13.5 2h-3A2.42 2.42 0 0 0 8 4.33V6H3a1 1 0 0 0 0 2h1v11a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V8h1a1 1 0 0 0 0-2ZM10 4.33c0-.16.21-.33.5-.33h3c.29 0 .5.17.5.33V6h-4ZM18 19a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V8h12Z"></path><path fill="currentColor" d="M9 17a1 1 0 0 0 1-1v-4a1 1 0 0 0-2 0v4a1 1 0 0 0 1 1Zm6 0a1 1 0 0 0 1-1v-4a1 1 0 0 0-2 0v4a1 1 0 0 0 1 1Z"></path>
</svg>
```

AFAIK asynchronous items are being handled correctly, and I'm wondering if this is particular to this library operating in a Jest environment. Any clues are appreciated, cheers

**Comment by cyberalien** [comment]
Icon data is not fetched in node.js, unless fetch function is set: https://docs.iconify.design/icon-components/react/set-fetch.html

However, it is not a good idea to do that just for testing. Not only it will waste API resources, but also might cause other issues. Server side rendering has been a major pain for various reasons: async rendering, random unique ids (for masks, clip paths and animations) breaking hydration.

Better solution is to switch to web component. It renders icon data in shadow DOM, while all React sees is `<iconify-icon />` element. See https://github.com/iconify/iconify/issues/152

**Comment by nickfreemandesign** [comment]
cool beans, thanks @cyberalien i'll give it a try, thanks for pointing me in this direction. cheers
