### ISSUE TITLE
svelte icons not display:block by default

### ISSUE THREAD

**Issue by Sarah-W** [iconify/iconify#155]
Your documentation indicates  `<Icon icon = "iconname" />`  should give a display:block styled svg and `<Icon icon = "iconname" inline={true} />`  should give a display:inline one.

This is not currently the case. You get an svg with the browser default display, which is inline.

**Comment by Sarah-W** [comment]
After a little more poking around - you're just passing those attributes straight through, so `<Icon icon = "close" style={"display:block"}/>` gives me a properly block-styled icon. 

cheers
S

**Comment by cyberalien** [comment]
I think you misunderstood documentation. It doesn't add any style.

Display modes "inline" and "block" are not related to display style. That attribute handles vertical alignment of icon. Inline is when icon is displayed in text, like font like this: 🖼, so it is vertically aligned below baseline. Block is when icon is displayed as image, without special alignment.

It was originally intended to be as way to help migrate from icon fonts. Naming for attribute could have been better though.

**Comment by Sarah-W** [comment]
OK. Adding `inline={true}` changes nothing that I can see, and I really need a way to remove the padding left for risers/descenders at the bottom of the icon. Is `<Icon icon = "close" style={"display:block"}/>` your recommended way of doing this.

**Comment by Sarah-W** [comment]
Thanks. that pretty much solves my problem.
