### ISSUE TITLE
Don't load hidden icons

### ISSUE THREAD

**Issue by uok** [iconify/iconify#156]
Thanks for this great tool!

Is there a way that Iconify does not load hidden icons?
e.g. `<span class="iconify" data-icon="fa-solid:home" style="display:none"></span>`

**Comment by cyberalien** [comment]
Sorry, missed notification for this.

It is not possible. Even if you set style like that, it can be overwritten in stylesheet using `!important`, so it is not an indication of visibility. While it can be calculated, there is no way to know when visibility has changed.
