### ISSUE TITLE
Is it possible to load all icons according to the collection name

### ISSUE THREAD

**Issue by newives** [iconify/iconify#157]
such as: https://esm.sh/@iconify-json/ri@1.1.3/icons.json

**Comment by cyberalien** [comment]
Link you've posted contains exactly that. 

If you want big package with all icon data, see https://docs.iconify.design/icons/all.html

Individual icon sets are available as NPM packages, which link you've posted points to. See https://docs.iconify.design/icons/json.html

**Comment by newives** [comment]
thanks
