### ISSUE TITLE
Where should `addAPIProvider` be called in SvelteKit?

### ISSUE THREAD

**Issue by NextReactionary** [iconify/iconify#159]
For the sake of performance, I'd like to host the API on the same server as the application. Downloading and running the API was quite trivial, luckily, but I'm not sure where I should call `addAPIProvider`.

I'm using SvelteKit with Vite, so my first attempt was the root `__layout.svelte` like so:

```html
<script lang="ts">
	import "virtual:windi.css";
	import "virtual:windi-devtools";
	import { addAPIProvider } from "@iconify/svelte";

	addAPIProvider("", {
		resources: ["https://localhost:6499"]
	});
</script>

<slot />
```

But this didn't seem to work, as stopping the server did not hinder the icon retrieval (including icons I had not used before, so it's not just a cache thing either).

My second attempt was through `vite.config.js`, though I figured this would absolutely not work, seeing as it's just supposed to export a config object:

```js
import { sveltekit } from "@sveltejs/kit/vite";
import WindiCSS from "vite-plugin-windicss";
import { addAPIProvider } from "@iconify/svelte";

addAPIProvider("", {
	resources: ["https://localhost:6499"]
});

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit(), WindiCSS()]
};

export default config;
```

Needless to say, this didn't work either. So, I've come here to ask with some embarrassment where I am supposed to call this function.

Thanks!

**Comment by cyberalien** [comment]
It needs to be used at run time, so second option won't work.

First code seems like a good solution. I suspect layout is rendered after rendering components used in it, so probably by the time that code was reached, icons were already loading. Try putting it in `<script context="module">` in same file, which might run earlier.

**Comment by cyberalien** [comment]
One more thing: for server side rendering I recommend switching to `iconify-icon` package.

Problem with Svelte and other components is, when used in server side rendering with icons that use unique ids, it might end up messing up unique ids that will fail hydration. See https://docs.iconify.design/iconify-icon/#ssr

**Comment by NextReactionary** [comment]
Thanks for the quick replies! I did some tests (which was surprisingly difficult due to the cache and having to disconnect my internet just to be 100% sure), and this is the only configuration that consistently works:

In my root `__layout.svelte`:
```html
<script lang="ts">
	import "virtual:windi.css";
	import "virtual:windi-devtools";
	import "iconify-icon";
</script>

<script context="module">
	import { addAPIProvider } from 'iconify-icon';
	addAPIProvider('', {
		resources: ['http://localhost:6499'],
 	});
</script>

<slot />
```
For future reference: note the `context="module"` and empty string in the first argument of `addAPIProvider`. I can't find any issues with this implementation as of now, so this issue should be fully resolved. 

Though I am a bit worried about browser compatibility with web components, but that's beyond the scope of this ticket I assume. SvelteKit has compatibility problems out of the box anyhow (if you still call not supporting Internet Explorer a "problem" nowadays), so perhaps I'll stumble upon some good polyfills once I get to optimising my application for compatibility.

Thanks!

**Comment by cyberalien** [comment]
Yes, compatibility might be an issue if you expect to support older versions of IE. Chromium based versions of Edge support it, but older versions don't and polyfills are rather sketchy. 

`@iconify/svelte` works fine with old IE. So choice is either not supporting old IE or possibility of hydration issues.

**Comment by NextReactionary** [comment]
Thanks for the help and advise!
