### ISSUE TITLE
Icon name may overflow on icon browser

### ISSUE THREAD

**Issue by kidonng** [iconify/iconify#163]
https://icon-sets.iconify.design/fluent-emoji-flat/atom-symbol/

<img width="502" alt="image" src="https://user-images.githubusercontent.com/44045911/184522420-69a9fa7e-2684-42cb-b9f0-505713df5e9f.png">

**Comment by cyberalien** [comment]
Thanks for noticing and reporting! Fixed.

Changes will appear on website after tomorrow's icons update.

**Comment by cyberalien** [comment]
Thanks for all suggestions and reports today!

Pushed update for website to test all changes earlier than automated update, while traffic is low during weekend. Also changed code samples.
