### ISSUE TITLE
Add `autofocus` attribute to "Search all icons" input

### ISSUE THREAD

**Issue by kidonng** [iconify/iconify#164]
This will make searching the icon more convenient:

<img width="319" alt="Screen Shot 2022-08-14 at 14 06 28" src="https://user-images.githubusercontent.com/44045911/184524725-dc52ec72-47d3-47cb-bd6c-781abf9eae3a.png">

**Comment by cyberalien** [comment]
Thanks for suggestion, but I won't be adding it because of touch devices. When page appears, with autofocus also keyboard appears, which on some devices takes half of screen and makes website annoying to use.

**Comment by kidonng** [comment]
Maybe we can have the next best thing instead?

```js
if (navigator.maxTouchPoints === 0) input.focus()
```
