### ISSUE TITLE
Add a `/` shortcut to focus search box

### ISSUE THREAD

**Issue by kidonng** [iconify/iconify#166]
Aiming to enhance search experience similar to #164. This shortcut can be found in lots of website, like Google, MDN, and this very website (GitHub).

When in a specific icon set the shortcut should probably search in that icon set.

**Comment by cyberalien** [comment]
Thanks for suggestion.

However, there is a problem: as `accesskey` attribute that shortcut for some reason doesn't work in Chrome. so solution requires JavaScript, but bundle is already too big so I won't be adding this.

**Comment by kidonng** [comment]
> so solution requires JavaScript, but bundle is already too big so I won't be adding this.

I'm not sure that's the case at all. This is enough to work:

```js
addEventListener('keydown', (event) => {
    if (event.key !== '/' || event.target.tagName === 'INPUT') return
    event.preventDefault()
    const input = document.querySelector('.iif-view--collection .iif-input input') || document.querySelector('.iif-content--view .iif-input input')
    input.focus()
})
```
242 bytes after minified by Terser, and that's not even counting gzip/brotli.

**Comment by cyberalien** [comment]
Good point!

Added.

**Comment by kidonng** [comment]
It's working 🚀

The implementation is a little different from mine though, as it does not search inside a specific icon set. Not necessarily a bad thing 👀
