### ISSUE TITLE
vitejs logo is not rendered

### ISSUE THREAD

**Issue by toniengelhardt** [iconify/iconify#167]
For some reason `<i class="i-logos-vitejs" />` is not rendered. Other icons are working. Is it possible that it is somehow stripped out by Vite itself bc of its name?

See here under "Shout-out & Attribution": [https://repo-tracker.com/impressum](https://repo-tracker.com/impressum)

VS code recognises the logo:

![Screen Shot 2022-08-15 at 12 30 59](https://user-images.githubusercontent.com/2703233/184627732-5c6f8401-0fe8-475a-bbcb-083e5bdf9303.png)

**Comment by cyberalien** [comment]
Most likely you need to update dependencies, more specifically, `@iconify-json/logos`

**Comment by toniengelhardt** [comment]
@cyberalien I have `v1.1.14` of @iconify-json/logos. Should be the latest right?

**Comment by cyberalien** [comment]
Yes, it is.

I've looked at your website, logo is rendered correctly. Maybe a browser cache issue?

**Comment by toniengelhardt** [comment]
@cyberalien oh wow, you are right, on the live page it is rendered, only in dev-mode it is not.

Closing... Sorry for the false alarm.
