### ISSUE TITLE
mdi:sort-ascending icon should have a arrow up instead of a arrow down

### ISSUE THREAD

**Issue by vinicenter** [iconify/iconify#169]
Hello guys. first of all thank you for this nice library.

I have noticed that the icon "mdi:sort-ascending" have a arrow down instead of a arrow up. i think that the right position for this icon is to have the arrow up.

Thanks.

![image](https://user-images.githubusercontent.com/23382040/189704990-a6c4e7bb-11ce-48b7-b5b3-fdcfe5623769.png)

Iconify icon: https://icon-sets.iconify.design/mdi/sort-ascending/
pictogrammers: https://pictogrammers.github.io/@mdi/font/2.0.46/

**Comment by cyberalien** [comment]
Source image: https://github.com/Templarian/MaterialDesign/blob/master/svg/sort-ascending.svg

Font is wrong.

**Comment by cyberalien** [comment]
I found what is causing that issue: you are using very old version of font.

Latest version is `7.0.96`, which has arrow pointing down for `sort-ascending`: https://pictogrammers.github.io/@mdi/font/7.0.96/

**Comment by vinicenter** [comment]
hello, thanks for the support!
