### ISSUE TITLE
Inline style not working on 1.0.5

### ISSUE THREAD

**Issue by setochris** [iconify/iconify#17]
Hi, I just updated my load script to 1.0.5 and have noticed that inline styles are not working with the icons.  If set on a parent tag the style works fine, also if set on a class using css the styles are fine too, but inline styles are definitely not working.  I switched back to loading 1.0.4 and it's working fine.

For example using this line 

`<span class="iconify" data-icon="mdi:lock-outline" data-inline="false" style="font-size:170px;"></span>`

Does not work using 1.0.5.

I'm loading the script for 1.0.5 from the cdn using : 

`<script src="https://code.iconify.design/1/1.0.5/iconify.min.js"></script>`

As per the documentation.  Have tested on a few different pages with the same results.  Can someone confirm if this is the case for them please?  Thanks

**Comment by cyberalien** [comment]
Can confirm. Thanks a lot for reporting! I'll fix it

**Comment by cyberalien** [comment]
Fixed in 1.0.6. Also added unit tests to make sure it doesn't happen again.
