### ISSUE TITLE
Error: [Vue warn]: $attrs is readonly.

### ISSUE THREAD

**Issue by nasirDoe** [iconify/iconify#172]
I installed in nuxt 2. That's error is annoying. How to fix that ? Thank you

![Screen Shot 2022-10-04 at 11 29 12](https://user-images.githubusercontent.com/16643567/193734467-096b3598-05fe-4c87-9384-b0f4181637c3.png)

**Comment by cyberalien** [comment]
It can't be solved because of how Nuxt 2 works. I recommend switching to [https://docs.iconify.design/iconify-icon/](iconify-icon) package, it works with all versions of Vue and Nuxt.

**Comment by cyberalien** [comment]
Actually... maybe there is a solution. Not sure though. Added a small workaround to next version, but not sure if it helps.

**Comment by dlodeprojuicer** [comment]
I have the same error on Nuxt 2, I am on @iconify/vue2 2.1.0.

**Comment by kyakaze** [comment]
> Actually... maybe there is a solution. Not sure though. Added a small workaround to next version, but not sure if it helps.

Link is broken, Can you add your workaround please?
I'm using Vue2 with rails but also experience this problem

**Comment by cyberalien** [comment]
Fixed link in post above.

Correct link is https://iconify.design/docs/iconify-icon/
