### ISSUE TITLE
Open shadowRoot?

### ISSUE THREAD

**Issue by chasegiunta** [iconify/iconify#173]
Is there a specific reason the `shadowRoot` is closed in the web component?

I'm using [adopted stylesheets](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/adoptedStyleSheets) to reset the default `width` & `height` to `inherit` so I can just adjust with classes, and it's working fine, but I'm curious if there was a reason it was closed, and if it would make more sense to open it.

**Comment by cyberalien** [comment]
That's a good point. Not sure why I set it to closed.

**Comment by cyberalien** [comment]
Remembered why it was done: component rendered only 2 nodes: style + icon. When updating child elements, it assumed that first element is style and second is icon, so adding extra code could mess it up.

I've updated code to handle it differently, so custom code should not cause problems and opened shadowRoot. Will release new version later today.

**Comment by chasegiunta** [comment]
Great. I think ultimately it's the better move 👍

**Comment by cyberalien** [comment]
Published version `1.0.1`. Please tell me if it solves your issue.

**Comment by chasegiunta** [comment]
Working on my end!
