### ISSUE TITLE
Offline usage in Nuxt 2 slows down the dev page loading times

### ISSUE THREAD

**Issue by kon3ko** [iconify/iconify#175]
nuxt: 2.15.8
node: v16.14.2

I'm working on it with Nuxt SSR. I created a plugin
```
//plugins/iconify.js
import Vue from 'vue';
import { Icon } from "@iconify/vue2";
import { addIcon } from "@iconify/vue2/offline";

import mdiYoutubeTv from "@iconify/icons-mdi/youtube-tv";
addIcon('mdi:youtube-tv', mdiYoutubeTv);

Vue.component('Icon', Icon);
```
run `yarn dev`

After that it seems The loading of the web page is extremely slow. It takes about 1-3+ seconds from 50-200ms.
If importing a lot It will take more time. This only happens when dev only production is very fast.

before
![image](https://user-images.githubusercontent.com/50349884/195865389-776bd365-8a96-4003-83cd-ec4313f9d545.png)

after
![image](https://user-images.githubusercontent.com/50349884/195865729-3c1e8cb1-89e1-4582-89b8-88a115d2f7da.png)

**Comment by kon3ko** [comment]
After change code to
```
import mdiYoutubeTv from "@iconify-icons/mdi/youtube-tv";
addIcon('mdi:youtube-tv', mdiYoutubeTv);
```

**Nuxt error**
require() of ES Module /var/www/project/client/node_modules/@iconify-icons/mdi/youtube-tv.js from /var/www/project/client/node_modules/vue-server-renderer/build.dev.js not supported. Instead change the require of youtube-tv.js in /var/www/project/client/node_modules/vue-server-renderer/build.dev.js to a dynamic import() which is available in all CommonJS modules.

Do you know how to fix it?

**Comment by cyberalien** [comment]
Revert to `@iconify/icons-mdi`. You are using legacy system that uses CommonJS, so you cannot import ES modules.

**Comment by kon3ko** [comment]
Ok and you know Why is it loading slowly? Now I use it without offline mode.
If it can't be fixed, I'll try it on production to see if there's a big difference with no offline mode.

**Comment by cyberalien** [comment]
I don't know.

One possibility I can think of is slow file system. Material design icons is one of the largest icon sets, so there are many files in directory and importing one icon from it in theory could be slow. In production its pre-bundled, so it is not an issue.

**Comment by cyberalien** [comment]
If you want to use only offline mode, maybe `unplugin-icons` would solve issue? See https://github.com/antfu/unplugin-icons

It generates components dynamically for each icon, no extra overhead. Iconify components are meant to be used with API, but `unplugin-icons` is meant to be used with bundlers.

**Comment by kon3ko** [comment]
Looks like it's probably what you said. Because I tried another icon It's slow, but not this much. but when i import I only imported one icon. Why is it loading slowly? Or does it import all of them, even just one item?

**Comment by cyberalien** [comment]
Try adding `.js` to import.

**Comment by kon3ko** [comment]
> Try adding `.js` to import.

Still error "ES Module".

**Comment by kon3ko** [comment]
It looks like `unplugin-icons` It works well and is fast. thank you for the advice.
Should this write a warning for other developers? Because I've been having this problem for over 7 months, I thought it was normal if there were more and more components.

**Comment by cyberalien** [comment]
Excellent.

`unplugin-icons` is a much better solution for offline use.
