### ISSUE TITLE
Why do icons have rotate 360?

### ISSUE THREAD

**Issue by jwr12135** [iconify/iconify#176]
Why do a lot of icons (all of the ones I've examined do far) have `style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);"`. Rotating an icon 360 degrees makes the icon look exactly like it did before.

**Comment by cyberalien** [comment]
It is a fix for rendering bug in Firefox. If icon side is placed on sub-pixel (for example, if icon is after text that is 100.5 pixels wide), Firefox rendered icon incorrectly, blurring its edges. Adding simple transform forced it to render at rounded pixel.

This is no longer an issue though, it has been fixed a while ago in Firefox. Icons rendered by API include that fix, [new version of API that is currently in development](https://github.com/iconify/api.js/issues/7#issuecomment-1279065663) no longer has it.

**Comment by jwr12135** [comment]
Thanks for the response!
