### ISSUE TITLE
https://api.iconify.design/icon.json  404

### ISSUE THREAD

**Issue by Healerlosers** [iconify/iconify#177]
vite3+vue3不支持了吗

**Comment by cyberalien** [comment]
There is no such URL. If you are trying to access it, you are doing something wrong.

My guess is you have icon that starts with `icon-`, such as `icon-home`, but that's a custom icon and you are not providing icon data for it correctly.

**Comment by lidianlei** [comment]
> There is no such URL. If you are trying to access it, you are doing something wrong.
> 
> My guess is you have icon that starts with `icon-`, such as `icon-home`, but that's a custom icon and you are not providing icon data for it correctly.
Thanks, it's my problem
