### ISSUE TITLE
[Feature Request] Please add Tailwind option when downloading SVGs on your site

### ISSUE THREAD

**Issue by Arturexe** [iconify/iconify#179]
I am using tailwind to configure SVG dimensions and would love to see an option on your site with a bit less boilerplate in the SVG code and instead a class attribute with, let's say `inline w-6` classes. Reason being that right now I am copying the SVG code and deleting `width`, `height`, and `preserveAspectRatio` attributes manually in every SVG (because they're not required and just add bulk):

```
<svg class="inline w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 221"><path fill="#41B883" d="M204.8 0H256L128 220.8L0 0h97.92L128 51.2L157.44 0h47.36Z"/><path fill="#41B883" d="m0 0l128 220.8L256 0h-51.2L128 132.48L50.56 0H0Z"/><path fill="#35495E" d="M50.56 0L128 133.12L204.8 0h-47.36L128 51.2L97.92 0H50.56Z"/>
</svg>
```

This could be done by adding an additional tag `SVG for Tailwind` or similar:

![image](https://user-images.githubusercontent.com/42435701/197134347-f8deff09-eee3-409e-bec5-9c90e2892ed0.png)

It would reduce verbosity of your SVGs for tailwind users and would make work a tad more pleasant.

Loving your app!

**Comment by Arturexe** [comment]
The great thing about using the website is that you're just copying raw code without any dependencies. I'd like to keep it that way.

**Comment by cyberalien** [comment]
But it is still a very rare use case.

For Tailwind I suggest using same approach that UnoCSS is doing: adding icon to stylesheet, then using it as class. Method used by UnoCSS is described here: https://antfu.me/posts/icons-in-pure-css and you can copy icon code from "SVG as data: URI" tab.
