### ISSUE TITLE
Size property is required and doesn't change the size of the Icon (Vue3)

### ISSUE THREAD

**Issue by Phill030** [iconify/iconify#181]
When trying to implement the icons, the require the size prop which doesn't even work,
Code:
```html
    <Icon icon="mdi:alert" color="white" :size="55"/>
```

Icon with Size property:
![chrome_lAS0UQ1Fym](https://user-images.githubusercontent.com/50775241/197842492-b1b63f41-b64d-4b6e-a219-a2e2b4c0df9f.png)
Icon without Size property + Error
![chrome_lAS0UQ1Fym](https://user-images.githubusercontent.com/50775241/197842492-b1b63f41-b64d-4b6e-a219-a2e2b4c0df9f.png)
```
Type '{ icon: string; color: string; }' is not assignable to type 'ComponentProps<ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{ noSelect: boolean; shadow: boolean; shadowColor: string; }> & Omit<Readonly<ExtractPropTypes<{ icon: { ...; }; size: { ...; }; noSelect: { ...; }; shadow: { ...; }; shadowColor: { ...; }; }>> & VNodeProps &...'.
  Property 'size' is missing in type '{ icon: string; color: string; }' but required in type 'Omit<Readonly<ExtractPropTypes<{ icon: { type: StringConstructor; required: true; }; size: { type: NumberConstructor; required: true; }; noSelect: { type: BooleanConstructor; required: false; }; shadow: { ...; }; shadowColor: { ...; }; }>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, DefaultKeys<...>>'.ts(2322)
Icon.vue(16, 5): 'size' is declared here.
```

**Comment by cyberalien** [comment]
There is no such property and never was. There are `height` and `width` properties, you can either use both or one of them. If you use one of them, such as `height="55"`, `width` will be set automatically to fit icon.
