### ISSUE TITLE
Add devicon collection

### ISSUE THREAD

**Issue by janosh** [iconify/iconify#184]
https://devicon.dev is a set of icons representing programming languages, designing and development tools.

MIT licensed: https://github.com/devicons/devicon

**Comment by cyberalien** [comment]
I've tried adding it earlier today, ran into many issues due to bad code in many icons.

Related issue: https://github.com/iconify/icon-sets/issues/66#issuecomment-1320960495

**Comment by cyberalien** [comment]
Closing as duplicate. Let's keep track of stuff in other issue at icon sets repository.
