### ISSUE TITLE
Is there a way to use Iconify in Qwik?

### ISSUE THREAD

**Issue by cayter** [iconify/iconify#185]
As topic and the website is [here](https://qwik.builder.io/docs/components/overview/).

**Comment by cyberalien** [comment]
Web component should be usable with it: https://docs.iconify.design/iconify-icon/

**Comment by cayter** [comment]
Cool, it works with using the CDN link but not the bundler way. I guess it's because of web component doesn't have a way to do SSR.

**Comment by cyberalien** [comment]
Can you test something for SSR? Open `node_modules/iconify-icon/package.json`, add `"sideEffects": "dist/*", then rebuild your app. Maybe that will solve bundling issue.

**Comment by cyberalien** [comment]
Oh well :( 

Thanks a lot for testing!

**Comment by cayter** [comment]
It's okay, I can live with web components for now which at least avoids me from having to manually import all the icons I need. Thanks for the awesome library!
