### ISSUE TITLE
Styles problems with Nuxt3

### ISSUE THREAD

**Issue by amoralesdesign** [iconify/iconify#186]
A <style> fragment is being generated for each icon that is rendered. This <style> has classes that affect the svg display of the icon.

This icon (iconify-icon icon="fa6-solid:eye") renders this:
**<style data-style="data-style">:host{display:inline-block;vertical-align:0}span,svg{display:block}</style>**

That <style> fragment affects the display of the icon:
![screen1](https://user-images.githubusercontent.com/4416148/203562869-887785ed-0027-4f8f-a985-cb649d25a1e7.png)

When I delete that <style> line, my icon displays and aligns correctly: 

![scree2](https://user-images.githubusercontent.com/4416148/203563642-5a6750f6-c8b4-4d4d-93cf-eb79e0085442.png)

**Comment by cyberalien** [comment]
That's correct behaviour. Without style it would display as block, which is what you want, but not what is usually expected.

You can change it by applying custom style to `iconify-icon` element, such as 
```css
iconify-icon { display: block; }
```

**Comment by cyberalien** [comment]
What style are you trying to apply to it?

**Comment by amoralesdesign** [comment]
> 

iconify-icon svg { display: initial; }

**Comment by amoralesdesign** [comment]
> 

iconify-icon svg { display: initial; }

**Comment by amoralesdesign** [comment]
> 



> 

No, what I don't want is for the svg to be block.
Right now that <style> that the component generates marks the svg as block.

I want the svg to be display initial.

Thanks

**Comment by cyberalien** [comment]
Then you should align `iconify-icon` element, not SVG inside it.

Looking at screenshot, you want to center it. That can be done with this CSS:
```css
iconify-icon { display: block; width: 1em; margin: 0 auto; }
```

Without style in shadow DOM, result is SVG with display set to `inline-block`, which causes container, which has display set to `block`, to have extra few pixels of padding below icon, resulting in a mess. Style is applied to fix that issue. Pretty much every use case can be achieved by setting style to `iconify-icon` element.

**Comment by cyberalien** [comment]
Closing issue as stale, probably resolved.
