### ISSUE TITLE
Please add support for React Native

### ISSUE THREAD

**Issue by tankmohit** [iconify/iconify#187]

**Comment by cyberalien** [comment]
My experience with React Native doesn't go beyond checking out some documentation. As far as I understand, it doesn't support SVG.

**Comment by cyberalien** [comment]
`react-native-svg` requires converting an entire icon code to React nodes tree. That means each icon must be pre-parsed, so it cannot be used with any icon components that load icon data on demand.

So the only solution is to use packages that generate components on demand during compilation, such as Unplugin Icons: https://github.com/antfu/unplugin-icons Currently it does not support React Native, but I think that's the best option to make Iconify icons work with React Native.

**Comment by cyberalien** [comment]
Closing as not planned.

Creating separate packages with icon data converted to JSX tree is not planned, as it is counter productive. The only use for such packages would be for React Native, which doesn't even fully support SVG.

It can be done with something like Unplugin Icons, as mentioned above, but that's out of scope for this project. Third party components are welcome.
