### ISSUE TITLE
Using an invalid icon set with `loadIcon` causes an indefinite hang

### ISSUE THREAD

**Issue by harlan-zw** [iconify/iconify#188]
This has been reproduced in Nuxt3, I'd imagine it would affect other implementations. 

Related issue https://github.com/nuxt-modules/icon/issues/30

I believe the problem is that the `loadIcons` function doesn't call the callback when there is an issue, so the promise is never resolved

**Comment by cyberalien** [comment]
Thanks for reporting and reproduction!

**Comment by cyberalien** [comment]
Fixed in `4.0.1`.

Bug actually affects every single icon component, not just Vue. Weird that such simple bug went unnoticed for so long.

Thanks a lot for reporting!

**Comment by harlan-zw** [comment]
Thanks for the quick fix :) 

Weird indeed! I've been using iconify for ages and only ran into this issue because I was migrating from `<i-set-icon />` to `<icon name="set:icon>"
