### ISSUE TITLE
Stoppped working in sveltekit dev mode

### ISSUE THREAD

**Issue by Mr-M1M3** [iconify/iconify#189]
Suddenly, stopped reflecting changes in HMR (sveltekit). However, it does work if I build then preview it.

**Comment by cyberalien** [comment]
Works fine for me.

HMR is tricky, it can be broken by many things, most often by browser cache. I recommend opening developer tools in browser, switching to network tab and disabling cache. Then keep it open during development. Usually that fixes HMR in any project.

**Comment by cyberalien** [comment]
Closing this because there is nothing to do.
