### ISSUE TITLE
[@iconify-icon/react] Provide a way to import the wrapper component without bundling the web component

### ISSUE THREAD

**Issue by dtinth** [iconify/iconify#191]
Hello. First, thank you very much for this project. Iconify is now my favorite way of using icons in the web!

I am building a website using Next.js with Server Side Rendering. So far so good.

However, I noticed that **until the page is hydrated by Next.js, icons are not shown.** This is because the `iconify-icon` web component is bundled into the JavaScript bundle generated by Next.js. That bundle needs to load first, before the Web Component can kick in.

To make icons appear faster I injected the script tag into `_document`’s `<Head>`:

```ts
        <script
          async
          src="https://cdn.jsdelivr.net/npm/iconify-icon@1.0.2/dist/iconify-icon.min.js"
          integrity="sha256-kwd+IKkvIXP95TLOfLvp/rHfnja1G+Ve+u1UR22A02k="
          crossOrigin="anonymous"
        />
```

This allows the `iconify-icon` to be loaded (and cached) separately. Now the Web Component can be instantiated without having to wait for Next.js bundle (which includes `react`, `react-dom`, and other stuff) to load.

However, importing the `Icon` Wrapper this way results in the Web Component being imported 2 times.

```js
import { Icon } from '@iconify-icon/react'
```

- First, by the `<script>` tag
- Second, by `@iconify-icon/react`

It would be great if the package provides a way to import just the wrapper component without importing the web component definition. Some examples:

```js
// Import both the Wrapper and the Web Component
// (most convenient, but for SSR icons will not show until page is hydrated)
import { Icon } from '@iconify-icon/react'

// Import only the Wrapper
// (the Web Component has to be imported separately, but this allows instantiating the Web Component before hydration)
// e.g.
import { Icon } from '@iconify-icon/react/wrapper-only'
import { Icon } from '@iconify-icon/react-wrapper'
```

My current workaround is: I maintain a copy of the React Wrapper that does not import the Web Component here: https://github.com/dtinth/notes.dt.in.th/blob/3a2765e1b1db2f6a191b50698b4a72f46c91b3ff/src/packlets/icons/index.tsx

**Comment by cyberalien** [comment]
That's a known bug in Next.js, which I've reported: https://github.com/vercel/next.js/issues/43068

Workaround is to create a client only wrapper, like this:
```js
"use client";
import { Icon } from "@iconify-icon/react";

export default Icon;
```

**Comment by dtinth** [comment]
@cyberalien Thank you for the reply, but I think they are different issues (I am not using React Server Components).

For this issue, I don’t want to bundle the Web Component in my Next.js app, because when the Web Component is bundled, it will not be activate until Next.js hydrates the app in the client-side.

Instead, I want to [sideload it into the web page](https://github.com/dtinth/notes.dt.in.th/blob/3a2765e1b1db2f6a191b50698b4a72f46c91b3ff/pages/_document.tsx#L15-L20), so that icons can display when while the Next.js client-side bundle is still loading. This made icons appear faster by about 1 second from my testing.

**Comment by cyberalien** [comment]
Oh I see. Then you don't need a Rect component at all.

Use `<iconify-icon icon="mdi:home" />` in TSX without React component. The only difference is if you are using class names, you should use `class` property, not `className`.

If you want to bundle web component, install and bundle `iconify-icon` package, not `@iconify-icon/react`.

**Comment by dtinth** [comment]
@cyberalien I see. Yes, that would work too. Still, I find having a [wrapper component](https://github.com/dtinth/notes.dt.in.th/blob/3a2765e1b1db2f6a191b50698b4a72f46c91b3ff/src/packlets/icons/index.tsx) beneficial because:

- TypeScript won’t complain about the unknown `iconify-icon` element.
- The wrapper also handles the stringification of object icons (as well as better treatment of boolean and className props).

Would you accept a PR that implements the following proposal?:

- Introduce a package `@iconify-icon/react-wrapper` that exports just the Wrapper component without pulling in the Web Component at runtime.
- Refactor the `@iconify-icon/react` package to re-export the wrapper from `@iconify-icon/react-wrapper`.

Alternatively, I can publish my own version of the wrapper that doesn’t include a bundled web component (maybe named `iconify-icon-react-wrapper`).

**Comment by cyberalien** [comment]
No need to create a new package for it. Just add this to your project:
```ts
import React from 'react';
import type {
	IconifyIconProperties,
	IconifyIconHTMLElement,
} from 'iconify-icon';

/**
 * Properties for React component
 */
export interface IconifyIconProps
	extends React.HTMLProps<HTMLElement>,
		IconifyIconProperties {
	// Rotation can be string or number
	rotate?: string | number;
}

/**
 * React component
 */
export const Icon = React.forwardRef(
	(
		props: IconifyIconProps,
		ref: React.ForwardedRef<IconifyIconHTMLElement>
	) => {
		const newProps: Record<string, unknown> = {
			...props,
			ref,
		};

		// Stringify icon
		if (typeof props.icon === 'object') {
			newProps.icon = JSON.stringify(props.icon);
		}

		// Boolean
		if (!props.inline) {
			delete newProps.inline;
		}

		// React cannot handle className for web components
		if (props.className) {
			newProps['class'] = props.className;
		}

		return React.createElement('iconify-icon', newProps);
	}
);
```

**Comment by dtinth** [comment]
@cyberalien I already did 😅

https://github.com/dtinth/notes.dt.in.th/blob/3a2765e1b1db2f6a191b50698b4a72f46c91b3ff/src/packlets/icons/index.tsx

I plan to use it in other projects too, having to copy and paste doesn't seem convenient, that's why I intend to create a package so it can be reused easily.

If you have concerns about using the global namespace (`react-iconify-icon-wrapper`), I can namespace it.
