### ISSUE TITLE
Transformations not applied when SVG is formatted

### ISSUE THREAD

**Issue by dhruvkb** [iconify/iconify#192]
The transformations applied to the SVG use string replace with `'<svg '` as the search string.

https://github.com/iconify/iconify/blob/b5e9ecd2b4216559939a25dee8d7f81923617067/packages/utils/src/loader/utils.ts#L83

https://github.com/iconify/iconify/blob/b5e9ecd2b4216559939a25dee8d7f81923617067/packages/utils/src/loader/utils.ts#L90

https://github.com/iconify/iconify/blob/b5e9ecd2b4216559939a25dee8d7f81923617067/packages/utils/src/loader/utils.ts#L94

This breaks when the SVG is formatted using Prettier, which formats the with attributes on separate lines:

```svg
<svg
  viewBox="0 0 24 24"
  xmlns="http://www.w3.org/2000/svg">
  <!-- paths -->
</svg>
```

In these cases the search pattern doesn't match `'<svg\n'` and so the props are not applied.

**Comment by cyberalien** [comment]
Thanks for reporting!

Fixed and published version `2.0.10` with fix.
