### ISSUE TITLE
How to call iconify globally with vue 3

### ISSUE THREAD

**Issue by filigreti** [iconify/iconify#194]
I would like to be able to call iconify globally and use it anywhere within the app without import but still shouldn't load all the files as well, only those passed to the v-bind:icon prop

**Comment by cyberalien** [comment]
What exactly are you trying to do?

**Comment by filigreti** [comment]
i dont want to have to import iconify in every vue file when i want to use it, im currently using it in mamy files, and i just want to be able to call if like  <Icon :icon="something" /> at anywhere in the app

**Comment by cyberalien** [comment]
So you want to use component without importing it? Then register it. See https://vuejs.org/guide/components/registration.html
