### ISSUE TITLE
Add `iconify-icon` element to `HTMLElementTagNameMap` for better typescript typing

### ISSUE THREAD

**Issue by Legend-Master** [iconify/iconify#195]
Without:
![image](https://user-images.githubusercontent.com/68118705/214093920-ae56d7b8-e3d2-443e-b795-ec5f426adadf.png)

With:
![image](https://user-images.githubusercontent.com/68118705/214094210-c59937a3-c73e-4e7f-8125-821c7f4da3e1.png)

**Comment by cyberalien** [comment]
This works. Thanks a lot for suggestion!

Added.
