### ISSUE TITLE
How to set stroke-width for `<iconify-icon>` web-component?

### ISSUE THREAD

**Issue by TheHadiAhmadi** [iconify/iconify#196]
Hi everyone.

I want to set stroke-width property of elements inside of iconify's `<svg>`. previously when using `@iconify/svelte` package it was just a simple css code:

```css
svg.icon * {
    stroke-width: 1.5;
}
```
and everything worked as expected.

now I want to replace `@iconify/svelte` with `<iconify-icon>`, only problem is that I cannot change `stroke-width`. 

is it possible to do this right now?

thanks.

**Comment by cyberalien** [comment]
Can't do that with web components.

I'm not sure if there is an elegant solution for this. The only option I can think of is to create a wrapper component, which loads data from API using `loadIcon` function, then modifies stroke in it, then passes it as parameter instead of icon name to `iconify-icon` component.

**Comment by cyberalien** [comment]
If you want to control contents of icon, best option is to switch to component that gives you full control over style, such as `@iconify/svelte` or `unplugin-icons`. Then you can use your CSS.

**Comment by cyberalien** [comment]
Added new function to `iconify-icon` package: `appendCustomStyle` that adds custom css to all icons rendered after function call.

So you can do this:
```ts
import { appendCustomStyle } from 'iconify-icon';

appendCustomStyle('svg [stroke-width="2"] { stroke-width: 1.5; }');
```

Calling function after creating nodes won't affect previously rendered nodes because package does not keep track of existing nodes.

**Comment by TheHadiAhmadi** [comment]
@cyberalien Thanks a lot.  

https://svelte.dev/repl/83807bb9a54746d58c092f76ee811450?version=3.55.1

`appendCustomStyle` works as expected and we can close this issue, but is's it better to have to have something like `data-css` prop for `<iconify-icon>` component which appends those styles for that particular component? 
something like this:

https://svelte.dev/repl/7b5c7d3dc29246e484c07239c5298647?version=3.55.1

thanks
