### ISSUE TITLE
InlineIcon does not working when using tailwind CSS

### ISSUE THREAD

**Issue by SlavenDj** [iconify/iconify#198]
InlineIcon is block element when using tailwind CSS. My current solution is to use className='inline'.

**Comment by cyberalien** [comment]
I think you misunderstood what `inline` means in Iconify. It doesn't change display mode, it only adjusts vertical alignment, so it is aligned nicely when rendered in text, similar to how icon fonts work.

So it's an issue of bad naming. Seemed like a good idea when I was adding that.

Also, for Tailwind I suggest checking out Iconify plugin: https://www.npmjs.com/package/@iconify/tailwind No overhead, no SVG in DOM - everything is in CSS.

**Comment by SlavenDj** [comment]
Thank you for quick reply and valuable information. I'm sorry for misunderstanding the meaning of inline in this context.
