### ISSUE TITLE
Issue with an icon

### ISSUE THREAD

**Issue by Barbapapazes** [iconify/iconify#205]
Hello,

There is an issue with this icon https://icon-sets.iconify.design/fluent-emoji/teddy-bear/

I don't know if it's from iconify or if the issue is from somewhere else.

**Comment by cyberalien** [comment]
Thanks for reporting!

I've checked original icon, it is correct, so bug happened somewhere during optimisation. I'll fix that.

**Comment by Barbapapazes** [comment]
Thanks!

**Comment by cyberalien** [comment]
Fixed.

It was caused by bug in third party software, which affects icons that use both transformations and filters (multiple entries of same transformation on sibling element + filter on parent element). I've reported bug and added a temporary workaround for it.
