### ISSUE TITLE
Support pnpm linking

### ISSUE THREAD

**Issue by innocenzi** [iconify/iconify#206]
I've encountered an issue where I have a target application using Iconify (specifically, `unplugin-icons`) which can't find locally-installed icon packages.

![image](https://user-images.githubusercontent.com/16060559/219970607-8ca9af6f-66c2-4d25-ab4a-2b9ee0d38c53.png)

The issue is that the loader is looking for a locally-installed package but can't find it because I'm using `pnpm i /local/path/to/some/package`. In that case, the local package that I'm developing is the one that contains `unplugin-icons` (it has an integration), so I guess Iconify tries loading icons from that specific `node_modules` hierarchy instead of the target one. 

That being said, the auto-installation properly install icon packages on my target project. This is a mix of a pnpm issue, a [`local-pkg`](https://github.com/antfu/local-pkg) issue and an Iconify issue. Not sure how to properly tackle that.

**Comment by cyberalien** [comment]
It uses `resolveModule` from `local-pkg` to find file, which uses Node's `createRequire().resolve()` to locate it.

So looks like Node.js cannot resolve it. I suggest to add few `console.log` to installed version of `local-pkg` in `resolveModule()` function to figure out what exactly goes wrong. Check if it tries to resolve correct package.

Something like this: in index.mjs and index.cjs replace
```js
export function resolveModule(name, options) {
  try {
    return _require.resolve(name, options)
  }
  catch (e) {
    return undefined
  }
}
```
with
```js
export function resolveModule(name, options) {
  console.log('Trying to resolve', name);
  try {
    return _require.resolve(name, options)
  }
  catch (e) {
    console.error('Failed to resolve', name)
    return undefined
  }
}
```

**Comment by innocenzi** [comment]
Definitely comes from there: 

![image](https://user-images.githubusercontent.com/16060559/219972168-6db22989-1e24-4bdc-bfe0-f2ec77723b08.png)

`hybridly/hybridly` there is the local package that's installed via symlink in `hybridly/demo` (seen at the bottom of the stack trace)

**Comment by cyberalien** [comment]
Looking at logs, it does try to resolve correct file, so Node.js can't resolve it, so it's a pnpm issue.

pnpm has various config options, which might solve it. See https://pnpm.io/package_json

**Comment by innocenzi** [comment]
Right. I've already tried changing `.npmrc` options such as `node-linker` but with no luck. I'll keep using my workaround for now (installing `@iconify/json` as a dev dependency of the linked project).

Thanks for your help @cyberalien, appreciate it!

**Comment by cyberalien** [comment]
A possible workaround: in your config for unplugin icons, use `material-icons` as a custom collection. Make a copy of it or attempt to resolve it from config.

**Comment by innocenzi** [comment]
When working on a feature for my package which included `unplugin-icons`, I realized that the second parameter of `isPackageExists` accepts a `paths` property. 

Setting it to `process.cwd()` seems to solve the problem, as the resolution will start from where the script is executed. Unsure if it is a potential fix for this issue, I think so but it could potentially break other setups?
