### ISSUE TITLE
Animated icon does not render in Android mobile browser

### ISSUE THREAD

**Issue by J4gQBqqR** [iconify/iconify#208]
Hi I am using the `<Icon icon="" />` component for svelte. 
I was unable to render animated icons in Android Chrome and Android Firefox. For example, [this one](https://icon-sets.iconify.design/line-md/).
The icon will appear blank and animation will not start after I load the webpage. 
I cannot reproduce this behavior in Windows Desktop Firefox and Chrome's responsive design mode. This only happens in Native Android browser.

Could anyone help me verify if this behavior is a bug?

**Comment by cyberalien** [comment]
I have no issues with animations in browsers on Android phone.

Even old Samsung browser, which I haven't updated in few years, renders icons correctly.

**Comment by cyberalien** [comment]
Closing this.

Whatever issue is, it is a browser issue and there is nothing I can do about it.
