### ISSUE TITLE
error something

### ISSUE THREAD

**Issue by Hrero** [iconify/iconify#210]
RollupError: "Icon" is not exported by "node_modules/.store/vue@3.2.47/node_modules/vue/dist/vue.runtime.esm-bundler.js", imported by "src/components/common/SvgIcon/index.vue?vue&type=script&setup=true&lang.ts"

**Comment by cyberalien** [comment]
Why are you importing it from `vue`?

**Comment by Hrero** [comment]
https://www.npmjs.com/package/@iconify/vue/v/4.1.0
write document

**Comment by cyberalien** [comment]
Look at your error message. It clearly states you are trying to import `Icon` from `vue`, not `@iconify/vue`.

**Comment by Hrero** [comment]
node 18.15.0;
vue 3.2.47; 
npm i @iconify/vue --save
No use pnpm
This error occurred
i'm cannot help but

**Comment by cyberalien** [comment]
Error is in your code in `src/components/common/SvgIcon/index.vue`

**Comment by Hrero** [comment]
yes

**Comment by Hrero** [comment]
node_module package @iconify/vue Of the root directory ；import a vue package ；Very strange

**Comment by cyberalien** [comment]
> Error is in your code in `src/components/common/SvgIcon/index.vue`
