### ISSUE TITLE
 Black box around animated icons in Firefox v111

### ISSUE THREAD

**Issue by escherlies** [iconify/iconify#214]
![Screenshot 2023-04-07 at 18 06 23](https://user-images.githubusercontent.com/24828012/230714586-f7e6d6b3-da20-429e-ad67-42a21e5e4060.png)

Using the Tailwind CSS Icon Plugin package, animated icons display with a black box around them in Firefox v111, while appearing correctly in other browsers like Chrome and Safari. This inconsistency affects the overall visual appeal of the project.

Steps to reproduce:

1. Install this Tailwind CSS Icon Plugin package.
2. Add an animated icon using provided classes (e.g., `animate-spin`).
3. Open in Firefox v111 and notice the black box around the icon.
4. Compare with other browsers to confirm the issue is Firefox-specific.

Expected: Animated icons display consistently without artifacts.
Actual: Black box appears around animated icons in Firefox v111.

Additional info:

    Firefox version: 111
    OS: macOS Ventura (13.2)
    Tailwind CSS version: ^3.3.1
    Tailwind CSS Iconify Plugin version: latest

Please advise on any known workarounds or further information needed. Thanks!

**Comment by cyberalien** [comment]
Can you post full list of classes you are using for that bugged element?

**Comment by cyberalien** [comment]
Managed to reproduce it.

Definitely a bug in Firefox. It renders edge pixels of mask image incorrectly when its rotated.

**Comment by userquin** [comment]
@cyberalien I solve this using preserve-3d wrapper:
- https://github.com/elk-zone/elk/pull/1081
- https://github.com/unocss/unocss/issues/300

**Comment by cyberalien** [comment]
Awesome. I've been trying everything in last 5 minutes to find a workaround, ran out of ideas.

It works!

Though `preserve-3d` doesn't seem to exist in Tailwind so I've used inline style instead:
```html
<span
	class="animate-spin"
	style="display: inline-flex; transform-style: preserve-3d"
>
	<span class="icon-[mdi-light--arrow-left]"></span>
</span>
```
