### ISSUE TITLE
iconify.mjs?Why is .mjs?

### ISSUE THREAD

**Issue by MomokaKawakabe** [iconify/iconify#215]
in ./node_modules/@iconify/vue2/dist/iconify.mjs

Module parse failed: Unexpected token (66:2)
You may need an appropriate loader to handle this file type.
| });
| const defaultIconProps = Object.freeze({
|   ...defaultIconDimensions,
|   ...defaultIconTransformations
| });

**because**
Must be used
![image](https://user-images.githubusercontent.com/30244380/231167117-73c8a0e5-b0c6-40a0-b26e-76ee91903470.png)

That's not good. 
because mjs

**Comment by cyberalien** [comment]
Looks like you are using ancient version of babel, which cannot handle spread operator. Update your dependencies.

**Comment by cyberalien** [comment]
Closing this. Issue is in severely outdated development environment, not in Iconify.
