### ISSUE TITLE
Improving SVG spinner animation

### ISSUE THREAD

**Issue by jd-solanki** [iconify/iconify#216]
Hey  👋🏻 

Your work always amazes me ❤️ 

Recently, I noticed iconify does provide spinners https://icones.js.org/collection/svg-spinners

Then I thought I can use this in my component lib instead of my custom vue component, This will allow users to user any spinner they like for loading animation.

I tried it and found that it's animation isn't smooth (it looks like it pauses for fraction of the second) as my custom components, I don't know how SVG animation is implemented but do you think that can be improved further?
Difference:
https://user-images.githubusercontent.com/47495003/231944675-13ed6bed-24bd-4a15-a563-c2e2c00b4730.mov

I have added live demo in my docs temporary for more visible difference:
https://anu-vue.netlify.app/guide/components/loader.html
![image](https://user-images.githubusercontent.com/47495003/231945724-5d4170b8-ea7d-4f20-ac82-205ee2bb3424.png)

**Comment by cyberalien** [comment]
In browsers animation timers start only after DOM is loaded, so pause can happen during loading.

Solution is to use icon in CSS as background or mask (such as UnoCSS). Timers for animations in background/mask images are separate from main timers, so they start animating immediately, even if DOM is still loading.

**Comment by jd-solanki** [comment]
Thanks for the response, I wasn't refering to initial pause I was refering to similar to 60fps behavior.

Have you checked the live demo? svg icon spinner animation looks like it pauses for fraction of the second after each time frame (I don't know much about animation glossary so I hope you understand what I'm trying to say). Whereas, vue component animation looks smooth.

Regards.

**Comment by cyberalien** [comment]
Oh, I see issue now, but only on video. Checked attached demo frame by frame, can see many frames where first icon is identical in 2 frames in a row, while bottom icon animates.

From what I've seen in various tests, CSS animations require much less CPU and render faster. In case of spinner, as far as I understand browser behaviour, icon is rendered only once, then cached and rotated, so circle doesn't need to be re-calculated on each frame.

Repeating SVG animations (such as spinners) require re-rendering icon on every frame, which requires way more CPU than simple CSS rotation, which could result in fps loss and high CPU usage.

I suggest to offer both options, with CSS animation as default behaviour. SVG animations are shiny, but simple rotation is performed much better with CSS.

**Comment by jd-solanki** [comment]
Just to make sure we are on the same path, iconify SVG spinners uses SVG animations, Right?

> _I suggest to offer both options_

Actually, I was going replace my custom spinner with iconify's spinner for wider options.

Have you checked the quasar's spinners: https://quasar.dev/vue-components/spinners#example--other-spinners

**Comment by cyberalien** [comment]
Yes, all those icons use SVG animations, including Quasar icons.

**Comment by jd-solanki** [comment]
🤔  Quasar's animations still looks smooth, only issue I noticed is loaders get blurry when size is increased above 5em (maybe 80px).

Anyways, Should we close this or keep it open for future improvements?
