### ISSUE TITLE
Iconify w/ Svelte breaks custom attributes

### ISSUE THREAD

**Issue by boian-ivanov** [iconify/iconify#217]
After the `3.1.1` update on the `@iconify/svelte` package, the `Icon` component now has lost compatibility with custom attributes assigned to it, such as `class` or any `data-` attributes that might be needed. It's not ideal, since as users of that library, it has worked completely fine with attaching custom attributes to it. Prior version `3.1.0` is working flawlessly. 
Is there a chance for that compatibility to be brought back? Also, since this should've been a patch version, it would be great for it not to have breaking changes, maybe something for future release versions.

**Comment by cyberalien** [comment]
Thanks a lot for reporting!

Issue is caused by this pull request: https://github.com/iconify/iconify/pull/213

I think this can be fixed. Need to figure out how to add all `span` attributes to component props.

**Comment by cyberalien** [comment]
I think it is fixed now.

Can you please check by installing `@iconify/svelte@dev`? That should install version `3.1.2-beta.1`

**Comment by boian-ivanov** [comment]
Yes, after testing it, it has now been fixed. The `IconProps & HTMLAttributes<SVGSVGElement>` union type seems to be working perfectly now. 
Thank you for your fast response on the matter! 👏 🎉

**Comment by boian-ivanov** [comment]
So a minute after I closed this, I noticed that every other attribute is now allowed, with the only exception of data attributes (I would assume aria ones as well). I've just tested it by making the union to handle both of them fixes the error. Shall I make a PR to add that or can I leave it with you @cyberalien?
This made it work in my case:
```ts
export default class Icon extends SvelteComponentTyped<
	IconProps & HTMLAttributes<SVGSVGElement> & AriaAttributes & DOMAttributes
> {}
```
As I've said above, I've added `AriaAttributes`, mostly for other cases, in my one it worked fine with just the `DOMAttributes` addition.

**Comment by cyberalien** [comment]
This is strange because `HTMLAttributes` extends both `AriaAttributes` and `DOMAttributes`:

```ts
export interface HTMLAttributes<T extends EventTarget> extends AriaAttributes, DOMAttributes<T> {
```

**Comment by boian-ivanov** [comment]
I would imagine so, yet VSCode seems unsatisfied for some reason 🤔 
<img width="928" alt="image" src="https://user-images.githubusercontent.com/15968453/232798333-e17b25af-1aef-4d1a-96e8-991a3d2c1927.png">

**Comment by cyberalien** [comment]
Tested `data-set-theme` attribute. No autocomplete, but also doesn't complain.

Maybe add `Record<string, string>` to union?

**Comment by cyberalien** [comment]
Could also be an issue with specific VSCode extension. I'm using `Svelte for VS Code` that is official extension, but there are plenty of other extensions, some could be broken.

**Comment by boian-ivanov** [comment]
On my side, I'm using the same Svelte extension. I wouldn't imagine autocomplete on custom data attributes, but I'm wondering why it might be happening. Maybe some of the extended types are being stripped through the `Props` generic on `SvelteComponentTypes`? 
I think a generic `Record<string, string>` might be to open though. So maybe the previously mentioned union might be enough for now? 🤔

**Comment by boian-ivanov** [comment]
@cyberalien Yup, works perfectly fine now. Thank you for helping sorting this out :)
