### ISSUE TITLE
在vitepress 中可以用么

### ISSUE THREAD

**Issue by trry-hub** [iconify/iconify#220]
我想在vitepress 中使用 iconify/vue， 但是安装完依赖，使用时，没有显示图标，不知到原因，请知道的大佬，帮忙解答下

**Comment by trry-github** [comment]
报了这些警告 
![image](https://user-images.githubusercontent.com/67309192/236968944-f4114e71-4f29-41bd-845c-883278d0d806.png)

**Comment by cyberalien** [comment]
I'll test it.

However, I recommend using `iconify-icon` package for Vitepress, not `@iconify/vue`. It works very well with SSR, currently being used on new website for Iconify, which uses Vitepress: https://github.com/iconify/website

**Comment by lovetingyuan** [comment]
https://vuejs.org/guide/extras/web-components.html#using-custom-elements-in-vue
设置一下webcomponent，不然vue会把iconify-icon当作一个vue组件而不是webcomponent
