### ISSUE TITLE
Missing some icons.

### ISSUE THREAD

**Issue by BTBMan** [iconify/iconify#221]
Icons are incomplete while searching icons using the Figma plugin and [Browse all icon sets](https://icon-sets.iconify.design/) website.

Search by https://icon-sets.iconify.design/carbon/. It's not found.

<img width="997" alt="image" src="https://github.com/iconify/iconify/assets/26108004/b2512f01-39b5-42ec-9f35-723564fd649f">

Search by https://icones.js.org/collection/carbon?s=cut+in+half

<img width="111" alt="image" src="https://github.com/iconify/iconify/assets/26108004/cbed01a7-ef58-4009-bc71-96c133b1405a">

**Comment by cyberalien** [comment]
That's a bug. Icon is there, but it is marked as hidden, which means it was removed at some point from icon set.

Icones shows hidden icons. Iconify website doesn't, though it should when icon is selected by name, so something is bugged in search.

**Comment by cyberalien** [comment]
This has been fixed in new version of website a while ago.

New Figma plugin uses same code as website, so fixed in Figma plugin too. Not published yet on Figma community, preview is available here: https://github.com/iconify/iconify-figma
