### ISSUE TITLE
Most icons do not render properly

### ISSUE THREAD

**Issue by erikdred** [iconify/iconify#228]
Copied from inconify discord.

Hi There. I'm having trouble with most icons not rendering properly. Instead of the icon, I get a nice black filled square box.

I'm using @iconify/tailwind and @iconify/json

HTML:
 <span class="icon-[material-symbols--123]"></span>
 <span class="icon-[fluent-emoji-flat--alarm-clock] text-red-600"></span>
 <span class="icon-[bx--abacus]"></span>

The fluent emoji is coming through, but the material symbol and bx abacus are just black boxes. I verified that both icons appear to exist in their respective json files with svg data.

Any ideas?

Edit: I tried adding a pic of it, but can only seem to add links.    https://ibb.co/0MZ1kPt

**Comment by cyberalien** [comment]
I'm not sure what Discord are you talking about because I don't see such message in `#iconify` channel on Discord.

Unfortunately screenshot is not enough to figure out what's wrong. Can you post a small chunk of HTML code you are using? Also, check if packages are up to date, there was a bug in older version that could have caused something like that.

**Comment by erikdred** [comment]
Sorry. I didn't notice that the HTML snippet did not come through. All packages are up to date.

```
<span class="icon-[material-symbols--123]"></span>
<span class="icon-[fluent-emoji-flat--alarm-clock] text-red-600"></span>
<span class="icon-[bx--abacus]"></span>
```

**Comment by cyberalien** [comment]
I've just tested that snippet, it works correctly.

Are you sure packages are up to date? Latest version of plugin is `0.1.2`

**Comment by erikdred** [comment]
Package.json for @iconfiy/tailwind

```
{
  "name": "@iconify/tailwind",
  "description": "Iconify plugin for Tailwind CSS",
  "author": "Vjacheslav Trushkin <cyberalien@gmail.com> (https://iconify.design)",
  "version": "0.1.2",
  "license": "MIT",
  "main": "./dist/plugin.js",
  "types": "./dist/plugin.d.ts",
  "bugs": "https://github.com/iconify/iconify/issues",
  "homepage": "https://iconify.design/",
  "funding": "https://github.com/sponsors/cyberalien",
  "repository": {
    "type": "git",
    "url": "https://github.com/iconify/iconify.git",
    "directory": "plugins/tailwind"
  },
  "dependencies": {
    "@iconify/types": "^2.0.0"
  },
  "devDependencies": {
    "@iconify-json/line-md": "^1.1.22",
    "@iconify-json/mdi-light": "^1.1.5",
    "@microsoft/api-extractor": "^7.33.7",
    "@rollup/plugin-node-resolve": "^15.0.1",
    "@rollup/plugin-replace": "^5.0.2",
    "@types/jest": "^29.2.4",
    "@types/jsdom": "^20.0.1",
    "@types/node": "^18.11.17",
    "@typescript-eslint/eslint-plugin": "^5.47.0",
    "eslint": "^8.30.0",
    "jest": "^29.3.1",
    "rimraf": "^3.0.2",
    "rollup": "^3.8.1",
    "tailwindcss": "^3.2.4",
    "ts-jest": "^29.0.3",
    "typescript": "^4.9.4",
    "@iconify/utils": "^2.1.4"
  },
  "scripts": {
    "clean": "rimraf lib dist tsconfig.tsbuildinfo",
    "lint": "eslint src/**/*.ts",
    "prebuild": "pnpm run lint && pnpm run clean",
    "build": "node build",
    "build:api": "api-extractor run --local --verbose",
    "build:lib": "tsc -b",
    "build:dist": "rollup -c rollup.config.mjs",
    "test": "jest --runInBand"
  }
}
```

**Comment by cyberalien** [comment]
This is very strange. Can you inspect failing icon and post CSS browser shows you?

**Comment by erikdred** [comment]
**-webkit-mask-image: var(--svg);
 -webkit-mask-image: var(--svg);** both lines are crossed out
**mask-image** gives a warning: unknown property name
**mask** gives a warning: invalid property value

```
.icon-\[material-symbols--123\] {
    width: 1em;
    height: 1em;
    -webkit-mask-image: var(--svg);
    -webkit-mask-image: var(--svg);
    mask-image: var(--svg);
    --svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='black' d='M5.5 15v-4.5H4V9h3v6H5.5ZM9 15v-2.5q0-.425.288-.713T10 11.5h2v-1H9V9h3.5q.425 0 .713.288T13.5 10v1.5q0 .425-.288.713t-.712.287h-2v1h3V15H9Zm6 0v-1.5h3v-1h-2v-1h2v-1h-3V9h3.5q.425 0 .713.288T19.5 10v4q0 .425-.288.713T18.5 15H15Z'/%3E%3C/svg%3E");
    background-color: currentColor;
    display: inline-block;
    -webkit-mask: none center / 100% no-repeat;
    mask: none center / 100% no-repeat;
}
```

**Comment by erikdred** [comment]
![image](https://github.com/iconify/iconify/assets/88980320/b84c9323-e747-41bf-b354-88e836f5ba2a)

**Comment by cyberalien** [comment]
That's correct CSS. Any other rules affecting that element?

**Comment by erikdred** [comment]
> Actually, that's not correct CSS. `mask-image` and prefixed version should be set after `mask`. Maybe you have a plugin that sorts rules or something like that?

I don't think so.  This is very bare-bones template so far.

Package.json
```
{
  "name": "parcel",
  "version": "1.0.0",
  "description": "template for starting ch5 panel projects",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html --public-url .",
    "build:archive": "ch5-cli archive -p basics -d dist -o tsw"
  },
  "dependencies": {
    "@crestron/ch5-crcomlib": "^2.3.1"
  },
  "devDependencies": {
    "@iconify/json": "^2.2.74",
    "@iconify/tailwind": "^0.1.2",
    "parcel": "^2.9.1",
    "postcss": "^8.4.24",
    "tailwindcss": "^3.3.2"
  }
}
```


All VSCode plugins disabled and no change in output (didn't expect a change).

**Comment by erikdred** [comment]
> So something is sorting rules incorrectly. Maybe its another Tailwind CSS plugin, maybe its something else in build process that inserts CSS in pages.
> 
> Not a big issue, can be easily bypassed with a bit longer CSS. I've published version `0.1.3` that is generating a bit different CSS. Can you see if it fixes your issue?

I will give it a shot and report back very soon.

**Comment by erikdred** [comment]
Success!!  Thank you very kindly for the very prompt attention and fix!!

**Comment by erikdred** [comment]
> But it does sort rules somewhere in that build chain.
> 
> That's not CSS that plugin generates, plugin puts `mask` first, which sets everything, then `mask-image` to override image. So between plugin generating code and code appearing in CSS, something is messing with it and does it incorrectly.

I would suspect that it is something in the parcel bundler.  Have you tried parcel to see if it affects your environment in a similar way?

**Comment by cyberalien** [comment]
No, I don't use parcel in my projects.

Oh well, whatever it is, now there is a workaround.

**Comment by cyberalien** [comment]
Found out what's causing bug: its Parcel.

Reported it at https://github.com/parcel-bundler/parcel/issues/9075
