### ISSUE TITLE
Installation is a bit confusing

### ISSUE THREAD

**Issue by nada-abuzaid** [iconify/iconify#231]
I faced a problem when trying to install the library as a dev dependency or as a dependency because there were two commands to choose from.

<img width="389" alt="image" src="https://github.com/iconify/iconify/assets/52599778/23a8f33f-db31-4f11-b5ba-bd3fe6c34f86">

<hr />

<img width="443" alt="image" src="https://github.com/iconify/iconify/assets/52599778/21599897-9bc6-48f1-b9c3-723e3e8edea8">

**Comment by KhaledToha** [comment]
me too
