### ISSUE TITLE
[bug]: missing type for incoming icon set

### ISSUE THREAD

**Issue by RSS1102** [iconify/iconify#237]
After I installed it,
```
npm install @iconify-json/fluent-mdl2 --save-dev
```
 I used this and it showed no type
```
import { icons } from '@iconify-json/fluent-mdl2'
```
Should types be added to the package?

![image](https://github.com/iconify/icon-sets/assets/81673017/eeab9863-721b-4f6a-bc8f-4cb01c26fffe)

**Comment by cyberalien** [comment]
There is a `types` entry in package, but not in `exports`. Looks like it needs duplicating for newer TypeScript that supports types in exports object.

I'll update packages tomorrow, until then you can open package.json, find
```
".": {
			"require": "./index.js",
			"import": "./index.mjs"
		},
```
and replace with
```
".": {
			"types": "./index.d.ts",
			"require": "./index.js",
			"import": "./index.mjs"
		},
```

**Comment by cyberalien** [comment]
Should be fixed now in latest version. Please tell me if fix works for you.

**Comment by RSS1102** [comment]
yes,Thank you very much for your timely repair. It has made me much happier.
![image](https://github.com/iconify/iconify/assets/81673017/56fec837-0a34-483b-aa10-fa6c5cb7090b)
![image](https://github.com/iconify/iconify/assets/81673017/187e6cec-aac7-4d03-b316-fb532bbd9538)
