### ISSUE TITLE
Usage of "alt" property throws error on SvelteKit + TypeScript

### ISSUE THREAD

**Issue by BRGustavoRibeiro** [iconify/iconify#244]
Hi, folks!

I'm creating a website on SvelteKit + TypeScript, and I'm trying to use the HTML _alt_ property on an Icon.
![image](https://github.com/iconify/iconify/assets/34517016/0eceb1d6-2775-4df7-9eb9-32f4173b4372)

The website runs fine, but TypeScript is throwing an error because the property doesn't exist.
![image](https://github.com/iconify/iconify/assets/34517016/dc8e8b6c-8f4d-4392-95f4-a9f25d1383c5)

This is a bug or am I doing something wrong?

Thanks a lot.

**Comment by cyberalien** [comment]
`alt` attribute is for images rendered as `<img>` to show text if image fails to load or cannot be viewed.

For `<svg>` attribute you are looking for is `title`.

**Comment by BRGustavoRibeiro** [comment]
YOU. ARE. THE. BEST.
Thanks a lot 🙂
