### ISSUE TITLE
I added a new collection to Iconify but it doesn't see the collection?

### ISSUE THREAD

**Issue by H7KZ** [iconify/iconify#248]
I imported svg icons correctly, named correctly, svg bodies as strings are correct, IconifyJSON also is correct... WHAT THE HELLL

```ts
import { icons } from '$icons';
import { addCollection, iconExists } from '@iconify/svelte';
import {
    cleanupSVG,
    runSVGO,
    parseColors,
    isEmptyColor,
    blankIconSet,
    SVG
} from '@iconify/tools';

export default async function importIcons() {
    const iconSet = blankIconSet('test');

    for (const { name, icon } of icons) {
        const svg = new SVG(icon);

        try {
            cleanupSVG(svg);

            await parseColors(svg, {
                defaultColor: 'currentColor',
                callback: (attr, colorStr, color) => {
                    return !color || isEmptyColor(color)
                        ? colorStr
                        : 'currentColor';
                },
            });

            runSVGO(svg);
        } catch (err) {
            iconSet.remove(name);
            return;
        }

        iconSet.fromSVG(name, svg);
    }

    const success = addCollection(iconSet.export());
    console.log('Imported icons:', success);
    console.log(iconExists('test:arrows'));
}
```

![image](https://github.com/iconify/iconify/assets/74021016/f9aee5b2-55fc-4ce2-b598-67854ffa6248)

**Comment by cyberalien** [comment]
Can you log icon names after this line: `iconSet.fromSVG(name, svg);`?

**Comment by H7KZ** [comment]
So, icons from $icons are in this format:
![image](https://github.com/iconify/iconify/assets/74021016/c525bf0d-85d9-4f42-a993-58cdb6b91999)

This is icon name that is logged after the line you want:
![image](https://github.com/iconify/iconify/assets/74021016/612041dc-b71b-4a15-a37e-71204ed1a2f9)

And this is the SVG:
![image](https://github.com/iconify/iconify/assets/74021016/566304f5-2226-43ad-8351-4ca61fbbf083)

And the final .export() method returns:
![image](https://github.com/iconify/iconify/assets/74021016/20259b7b-df3c-4685-86e6-1a8c4ac122b6)
![image](https://github.com/iconify/iconify/assets/74021016/2856552b-4b7b-489d-aa4c-461899c1f0cb)

**Comment by cyberalien** [comment]
In your code you are using `test:arrows`, but in screenshot its `timer`. Do you have `arrows` icon in exported icon set?

**Comment by H7KZ** [comment]
yes I do. I just copied the timer from the list.

**Comment by cyberalien** [comment]
Can't reproduce that. Can you make a small reproduction?

**Comment by H7KZ** [comment]
Yes, tried it on another project, same result.

I have sveltekit +layout.server.ts file that loads the icons:
```ts
import { addCollection, iconExists } from '@iconify/svelte';
import importIcons from '$utils/importIcons.util';
import type { LayoutServerLoad } from './$types';

export const load = (async () => {
	const icons = await importIcons();

	addCollection(icons);

	console.log(iconExists('test:timer'));

	return {};
}) satisfies LayoutServerLoad;
```

Then I have the util that imports the icons in a iconify useable format:
```ts
import type { IconifyJSON } from '@iconify/svelte';
import { blankIconSet, cleanupSVG, isEmptyColor, parseColors, runSVGO, SVG } from '@iconify/tools';
import { icons } from '$icons/svgs';

export default async function getIconifyJSON(): Promise<IconifyJSON> {
	const iconSet = blankIconSet('test');

	for (const { name, icon } of icons) {
		const svg = new SVG(icon);

		try {
			cleanupSVG(svg);

			await parseColors(svg, {
				defaultColor: 'currentColor',
				callback: (attr, colorStr, color) => {
					return !color || isEmptyColor(color) ? colorStr : 'currentColor';
				}
			});

			runSVGO(svg);
		} catch (err) {
			iconSet.remove(name);
		}

		iconSet.fromSVG(name, svg);
	}

	return iconSet.export();
}
```

and then in the icons/svg I have a index.ts file that contains this:
```ts
import timer from './timer.svg?raw';

export const icons: { name: string; icon: string }[] = [
	{
		name: 'timer',
		icon: timer
	}
];
```

I really don't know where is the problem. But what is interesting that if I take already made icon set and remove all of the icons from it and then I replace it with my icon lets say timer, it works... WHAT THE F***

**Comment by cyberalien** [comment]
That doesn't help. Without test case I can't debug it.

If it is hard to create a usable test case, I suggest to go a different route: use import function in build process separate from main code, export icon set to a JSON file, then import that JSON file in your code.

**Comment by H7KZ** [comment]
Well I don't know what else I am suppose to do. I tried exporting it to JSON and then importing it. Everything happens in the +layout.server.ts and It just doesn't work... I really don't know what black magic fuckery is going on :/

**Comment by H7KZ** [comment]
ok, nvm. somehow it now works... after I just ctrl c v whats in the docs it suddenly works... I think I will bury my self... welp, thanks for the help cyberalien, I am just an idiot

**Comment by cyberalien** [comment]
No worries. It happens to everyone. Glad you sorted it!
