### ISSUE TITLE
During packaging, assert json reports an error

### ISSUE THREAD

**Issue by WoJiaoFuXiaoYun** [iconify/iconify#250]
vue3  + vite 

node version ：v16.17.1

@iconify-json/ep : v1.1.11

```
Unexpected token (Note that you need plugins to import files that are not JavaScript)

1: import icons from './icons.json' assert { type: 'json' };
                                    ^
2: import info from './info.json' assert { type: 'json' };
error during build:
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

**Comment by cyberalien** [comment]
You need to update node

**Comment by WoJiaoFuXiaoYun** [comment]
> 您需要更新节点

@cyberalien 

I have reverted the version of the `@iconify-json/ep` package to `1.1.8`.

Of course, I also noticed the suggestion to update the node version to `17` or higher.

 Thank you for your response

**Comment by cyberalien** [comment]
That works too.

Unfortunately there is no way to support both old and new versions of node. Old version cannot handle `assert`, new version doesn't work without `assert

**Comment by WoJiaoFuXiaoYun** [comment]
That also works.
Sure, I'll translate the text for you. Please provide the text you would like me to translate
Unfortunately, there is no way to provide support for both older and newer versions of Node. The older version is unable to handle the `assert` function, while the newer version cannot function properly without it.

Yes, unfortunately. This will cause inconvenience for both users and warehouse maintenance personnel
