### ISSUE TITLE
CORS issue with importing icons using @iconify/vue

### ISSUE THREAD

**Issue by flingyp** [iconify/iconify#254]
How to avoid this cross-domain problem when using Iconify's icon?

![image](https://github.com/iconify/iconify/assets/57666140/7c200d1c-e3f4-498c-9c30-c8431ab06ddd)

**Comment by cyberalien** [comment]
Remove that policy from your code.

If you can't, you'll need to use a different solution for icons which bundles all icons, such as Unplugin Icons: https://github.com/unplugin/unplugin-icons

**Comment by flingyp** [comment]
Yes, I know to resolve this question by remove policy or unplugin-icons. But, i want to get icons by request rather than bundles all icons in local.  
Can https://api.iconify.design consider allowing cross-domain, otherwise @iconify/vue will not work.

**Comment by cyberalien** [comment]
It is caused by something in your settings: `'Access-Control-Allow-Origin' header has a value "http://localhost:8848'`.

Find where it is, remove it. It might be sent as header, might be included in head section of html.

**Comment by flingyp** [comment]
Yes, thanks for your time to reply me.
