### ISSUE TITLE
Using static icons with Next.JS 13

### ISSUE THREAD

**Issue by Karakatiza666** [iconify/iconify#255]
Is it possible to simply use static files (e.g. 'public/icons/icon.svg') with @iconify/react, utilizing Next bundler's custom url via `import icon from 'public/icons/icon.svg'` ? I haven't found anything in the docs.

**Comment by cyberalien** [comment]
It can be done by converting icon set (see Iconify Tools package), then bundling it.

However, that negates whole point of package. Its main function is to load icon data on demand, which cannot be done from local files. If icons are bundled, then why use icon component in first place? Would be more efficient to just use SVG as is. If icons are used in multiple places, alternative is to use icons in CSS so icon is used only once.

**Comment by Karakatiza666** [comment]
The problem is I was dynamically passing strings of shipped icon sets to a component to display, and now I need to use a static icon in the same element. Right now I am resorting to wrapping <Icon> with a component that displays <img src={..}> instead of Iconify <Icon> if icon string is a local path

**Comment by Karakatiza666** [comment]
It looks like Iconify Tools package needs Node.js for import, so it should be prevented from running in browser, or icons set should be precompiled; either way wrapper component is easier.

**Comment by Karakatiza666** [comment]
Or is displaying statically known icons from multiple icon sets interchangeably with some static custom icons not a use-case for Iconify library,?

**Comment by cyberalien** [comment]
It is, but not in your case. If it is done with icons loaded from API, it is intended use case because client only loads icons that are needed. If it is done with custom icons that are bundled, it is a waste of resources because bundled icons are loaded anyway, so all advantages of icon component are gone.

As for Iconify Tools, it is indeed only for Node.js use. You can use it in build process to create icon set.

**Comment by Karakatiza666** [comment]
I see, thank you! I will then use the icon sets I need with respective libraries so that they are all statically bundled.

**Comment by cyberalien** [comment]
If you are mixing custom icons and icons from existing sets, I suggest to check out Unplugin Icons: https://github.com/unplugin/unplugin-icons

You can use it with custom icons too, it bundles everything without any overhead.
