### ISSUE TITLE
include uxwing.com icons

### ISSUE THREAD

**Issue by sant0s** [iconify/iconify#256]
consider enriching iconify with https://uxwing.com/ icons.
uxwing.com seems to include icons that do not exist in iconify's current icon sets. example: the [alu 41 symbol](https://uxwing.com/?s=alu).

**Comment by cyberalien** [comment]
It cannot be included because:
- It is not open source. Icon set must have a valid open source license.
- Looks like it is not available on GitHub or any other method to automatically download all icons. Downloading icons one by one from a website will not work because it cannot be automated.

**Comment by sant0s** [comment]
fair enough, thanks anyway.
