### ISSUE TITLE
Sveltekit icon component change icon viewbox

### ISSUE THREAD

**Issue by lunatiqqc** [iconify/iconify#257]
Hi, how can I give props to the component that changes the viewbox of the Icon?

I am looking for a way similar to this

import Icon from '@iconify/svelte';

<Icon icon="dashicons:saved" viewBox={{ top: 99, left: 99, width: 99, height: 99 }}  />

**Comment by cyberalien** [comment]
You can't.

If you want full control over SVG content, I suggest to use SVG instead of component.

Alternatively, you can use CSS to adjust whitespace: add margin to icon or padding to container element. If you want to reduce size, use negative margin on SVG element and hide overflow in container.
