### ISSUE TITLE
Add option for @iconify/tailwind to disable height / width props

### ISSUE THREAD

**Issue by IHIutch** [iconify/iconify#258]
I'm experiencing an issue where I use height/width classes to style an icon's size. By default, this seems to work fine. However, when doing something like `h-6 w-6 icon-[material-symbols--add] group-aria-expanded:icon-[material-symbols--remove]` the additional specificity causes the icons to revert back to parent's font size. 

I understand that the sizing is controlled by the font-size rather than height and width. And in some cases, as noted in [Icons in Pure CSS](https://antfu.me/posts/icons-in-pure-css#scalable) this makes sense when using icons inline. However, icons are not always used inline. 

More broadly, it seems weird to me to use font-size to style height and width. Both Tailwind and UnoCSS have explicit classes to support these properties already. Further, to come back more into the Tailwind context, Tailwind has far fewer font-size styles than height and width styles. And soon, hopefully, a single class to support both height and width properties. In my opinion, following the logic of style systems like Uno and Tailwind, allowing users to opt in to font-size based sizing using `h-[1em] w-[1em]` makes more sense than handling it that way out of the box.

Or at the very least, making it configurable via the built in plugin system

**Comment by cyberalien** [comment]
Reason for using 1em width/height is there needs to be a default value. When using icon in CSS, it is used as background or mask, not as SVG, so it needs to have some dimensions. Expecting user to specify dimensions for each entry is unreasonable, 1em is chosen because icon fits nicely in text and is easy to resize.

Issue here is not with default values, but with specificity. Icon, `h-6` and `w-6` generate css with same specificity, so order of rules in css matters.

I think best approach is to add option to plugin to not add width/height to css, which would require adding both width and height for each icon.

**Comment by IHIutch** [comment]
> Issue here is not with default values, but with specificity

That's true, and what made me think about using in the context of Tailwind/Uno specifically.

I guess depending on the use case, I can understand needing to specify size of each icon could feel unreasonable, although that's not been my experience. That made me think, though, that perhaps specifying a default size within the plugin options, might align more closely with Tailwind/Uno's config/plugin systems

**Comment by IHIutch** [comment]
Actually, playing Uno's icon plugin, I wonder if `@iconify/tailwind` could work similarly to that, where `scale` is exposed as an option and I can set it to `0`.

**Comment by cyberalien** [comment]
Yes, using `scale` option makes sense with possibility of using 0 to completely remove size.

**Comment by cyberalien** [comment]
Thanks a lot for pull request. Merged, added demo and published new version of plugin.

**Comment by IHIutch** [comment]
Of course, thanks for the discussion!
