### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Rar9** [iconify/iconify#262]
your patch to fix the warning  is not working. 

Error when evaluating SSR module /src/routes/+page.server.ts: failed to import "/src/collections/index.ts"
|- ReferenceError: exports is not defined

Try 
```
"exports": {
        ".": {
            "svelte": "./src/index.js"
        }
    },
```

Downgrading helps for now

**Comment by cyberalien** [comment]
Sorry. Please try `@iconify/svelte@dev`

**Comment by Rar9** [comment]
"@iconify/svelte": "dev",  shows as @iconify/svelte 3.1.6 and works, thanks

**Comment by cyberalien** [comment]
Excellent. Added `latest` tag to it.
