### ISSUE TITLE
search page can set bigger or  loading more 

### ISSUE THREAD

**Issue by linpan** [iconify/iconify#263]
https://icon-sets.iconify.design/?query=sync

**Comment by cyberalien** [comment]
This is changed in new version of website (not published yet). It loads all available results, has dynamic pagination based on current browser window and it can be scrolled.

![Screenshot 2023-12-17 at 15 28 54](https://github.com/iconify/iconify/assets/822287/79f68733-33bf-4ff3-afe5-ae10ec126bb2)
