### ISSUE TITLE
Tailwindcss - Svelte - CMS

### ISSUE THREAD

**Issue by miguel-krasamo** [iconify/iconify#264]
Hello guys, I'm using tailwindcss version which uses `icon-[icon-name]` in classes.
If I write the icon and use it it works, but If I get the same string from a CMS it's blank.

I don't know if it's possible to set icons dynamically from somewhere else than the app, like a CMS or an API.

Here's my flow, CMS has an entry with icon prop (string) I.E icon = `icon-[whh--batman]` that I set like this: `<div class='${icon}' role="img" aria-hidden="true" />`  which translates into `<div class="icon-[whh--batman]" role="img" aria-hidden="true" />`
and the icon doesn't display.

Note, here I didn't used back tick because it broke the code markup.

**Comment by cyberalien** [comment]
Tailwind works by parsing files, finding all classes and creating CSS for it. If it can't parse content, it can't find those classes. It parses only during build process, not dynamically.

So looks like Tailwind is not a good solution for your use case, for all selectors, not just icons.

I recommend using [`iconify-icon` web component](https://iconify.design/docs/iconify-icon/) for your use case. That's the only dynamic solution which doesn't require build process.

**Comment by miguel-krasamo** [comment]
Thanks, that worked, I missed that in the docs, I was going to try the svelte component before your comment.

**Comment by cyberalien** [comment]
If your CMS uses server side rendering, such as SvelteKit, I recommend not to use Svelte component. Because of how hydration works in Svelte, component cannot render anything before it is mounted, which can cause content shift on page load.

This is solved by using web component.
