### ISSUE TITLE
width and height is not matched correctly when setting with a decimal

### ISSUE THREAD

**Issue by chenglu4343** [iconify/iconify#268]
The configureSvgSize method has a problem with the regular expression matching width and height. The width and height attributes with decimals cannot be correctly matched

in packages\utils\src\loader\utils.ts:5

such as 
```
<svg width="250.666" > 
    ...
</svg>
```

it will get 
```
<svg width="1em" width="250.666" > 
    ...
</svg>
```

**Comment by cyberalien** [comment]
Thanks for pull request. Published version 2.1.14 with fix.
