### ISSUE TITLE
Icon collection request: Bitcoin Icons

### ISSUE THREAD

**Issue by AaronDewes** [iconify/iconify#270]
Hi! Can you please add https://bitcoinicons.com/ to this collection?

If you let me know where I would need to implement it, I can also implement a downloader for it myself.

**Comment by cyberalien** [comment]
MIT licensed, available on GitHub, nice 24x24 grid. Looks good. I'll add it today.

**Comment by cyberalien** [comment]
Added. It will appear in icon sets tomorrow.

**Comment by AaronDewes** [comment]
Thanks a lot!
