### ISSUE TITLE
✨ Align syntax for icons

### ISSUE THREAD

**Issue by jd-solanki** [iconify/iconify#273]
Hi 👋🏻 

I've been using iconify from UnoCSS and it was really nice like `i-mdi-home`. However, I switched to tailwind and use your `@iconify/tailwind` and realized I can't use this syntax anymore.

Using square brackets is weird, Can you please allow unocss like syntax?

**Comment by cyberalien** [comment]
Tailwind is far inferior to UnoCSS, it requires plugins to generate all possible selectors before it scans pages. So to use `i-mdi-home` selector, all CSS for all icons in icon set must be generated by plugin, which is very slow. The only way to load data dynamically in Tailwind is to use brackets.

**Comment by jd-solanki** [comment]
Thanks for your inputs. Closing this as this outside of the scope of iconify.
