### ISSUE TITLE
Penpot integration

### ISSUE THREAD

**Issue by thomasfrobieter** [iconify/iconify#277]
Not sure if the [Penpot](https://penpot.app/) API is already advanced enough to do this, but a Penpot integration would be awesome.

https://help.penpot.app/technical-guide/integration/

**Comment by cyberalien** [comment]
I'd love to do that, but unfortunately Penpot API is very basic. I don't see how to import SVG to document.

**Comment by cyberalien** [comment]
Bad news. 

Long awaited version 2 of Penpot has been released, but it has no support for third party stuff: no plugins, no usable API.

Unfortunately there is nothing I can do about that.
