### ISSUE TITLE
bug[React]: Icon Component does not render icon on first render when using `loadIcons` to preload

### ISSUE THREAD

**Issue by SaintPepsi** [iconify/iconify#278]
When using `loadIcons` to preload icons before they get displayed, it seems that the `this.state.icon` in `IconComponent` does not get set until the second render cycle.

I confirmed this by calling `this._checkIcon(false)` on the first render in the first line of the method. which then makes it so that `this.props.icon` is no longer `null`

I was able to fix it for myself by changing the contructor function of the `IconComponent` to use the `this.props.icon` as base value for the state:

```
constructor(props) {
    super(props);
    this.state = {
        // Render placeholder before component is mounted
        icon: { data: props.icon }
    };
}
```
    
I'm not 100% sure what the actual underlying issue is. I know that `this.state.icon` can't be null on the first render if you already have the icon name and or data available in order to render the icon first go.

The issue does not seem to occur when rendering the Icon component directly, but when using abstraction in another component, the current implementation causes issues with loadIcons.

For example we have something like this:
```
const iconLoadList = new Set();

function CustomIcon({ icon, ...props }) {
  return (
    <Icon
      width="1em"
      height="1em"
      icon={icon}
      className={`Icon--${icon}`}
      {...props}
    />
  );
}

function getIconSet(iconName) {
  iconLoadList.add(iconName);

  function IconWrap(props) {
    return <CustomIcon icon={iconName} {...props} />;
  }

  return IconWrap;
}

const Icons = /** @type {const} */ ({
  CaretUp: getIconSet("ph:caret-up"),
  CaretDown: getIconSet("ph:caret-down"),
  CaretLeft: getIconSet("ph:caret-left"),
  CaretRight: getIconSet("ph:caret-right"),
});

loadIcons(Array.from(iconLoadList));
```

And then render it like so:

```
 <Icons.CaretDown fontSize={24} />
```

Please see my attempt at trying to create a minimal reproducable example: [codesandbox.io](https://codesandbox.io/p/sandbox/zen-glitter-zzj84m?file=%2Fsrc%2FApp.js%3A56%2C18&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clphshnnc00073b6h8qwv760x%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clphshnnb00033b6hy5x3kj7t%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clphshnnb00043b6h5uemgdjb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clphshnnb00063b6hr6m5ys2h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clphshnnb00033b6hy5x3kj7t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clphshnna00023b6h9njzb2q4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cls11t74w00023b6llp701uc9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A56%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A56%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clphshnnb00033b6hy5x3kj7t%2522%252C%2522activeTabId%2522%253A%2522cls11t74w00023b6llp701uc9%2522%257D%252C%2522clphshnnb00063b6hr6m5ys2h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clphshnnb00053b6h8ax5ak7o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clphshnnb00063b6hr6m5ys2h%2522%252C%2522activeTabId%2522%253A%2522clphshnnb00053b6h8ax5ak7o%2522%257D%252C%2522clphshnnb00043b6h5uemgdjb%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clphshnnb00043b6h5uemgdjb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

I've been trying for a couple hours now to create a minimal example, but I cannot for the life of me recreate it.
I can see that the `icon` prop is getting passed through correctly and exists at every stage of rendering. the only place it doesn't exist is inside `@iconify/react`'s `IconComponent`'s state.

Any suggestions on how I could recreate a minimal example to reproduce the issues are greatly appreciates since i'm at the end of my straw on this one.

The project i'm having this issues in is using `"react": "18.2.0"` and `"@iconify/react": "^4.1.1"` and `"webpack": "5.88.1"`

See [#279](https://github.com/iconify/iconify/pull/279)

**Comment by cyberalien** [comment]
That's correct behavior. Icon component does not render icon until component is mounted. This is done because of SSR - if icon is rendered before it is mounted and page is generated on server, it breaks React's hydration.

**Comment by cyberalien** [comment]
If you do want icon to render as soon as it is available without mounted shenanigans, I suggest to switch to `iconify-icon` web component. It renders icon immediately when data is available in shadowDOM, independent of framework. All React sees is `iconify-icon` element, contents are not visible to React, so web component doesn't have to account for possible hydration shenanigans.

Also available as `@iconify-icon/react` for React that is a simple wrapper that maps `className` to `class` (for web components in React you should use `class`, not `className`, which confuses some developers, so I've made a simple wrapper).

**Comment by SaintPepsi** [comment]
Thanks @cyberalien didn't know that was the way, I'll have a look at those.
I've not really worked with SSR for react, but could the base state be assigned with a `window` check? if the window doesn't exists does that mean it's being SSR'd? so you could do something like `icon: window ? { data: props.icon } : null`?

**Comment by cyberalien** [comment]
Hydration works like this:
- Components are rendered on server, converted to HTML, page is sent to browser as static HTML that is rendered immediately by browser before loading any scripts. This is called server side rendering.
- Then, in browser, after React is loaded, it generates page again in virtual DOM, rendering each component used on page. So like normal client side rendering. However, instead of just rendering it in HTML, it checks HTML page, expecting to find the same content in live HTML, assigns event listeners and stuff to existing HTML instead of replacing content. This is called hydration.

In order for hydration to work, content generated on server and content generated on client must match, otherwise hydration might fail for an entire page.

Window check would not help. It would result in different HTML rendered on server and client, causing hydration errors or complete hydration failure.

One caveat of hydration process is mounting of components. When components are rendered on server, mount event is never called. On client hydration is done before component is mounted because React needs to figure out which component should be assigned to which existing HTML element, only then mount component. Which means after mount event is called, hydration has been completed, so component can render whatever it needs without accounting for SSR.

Why would content be different in case of icon component, causing hydration to fail? Data for icons is loaded asynchronously, which means icon data might not be available when component is rendered. If data is not guaranteed to be available, but content rendered from that data must be identical, the only option is not render icon until hydration process is complete.

There are 2 viable solutions for this:
- Wait for component to mount, then render icon. This is what icon component currently does.
- Render icon without React. This is what web component does.

**Comment by SaintPepsi** [comment]
Thanks for explaining it, It makes sense.

I've applied your suggestion for `iconify-icon` and `@iconify-icon/react` and it works as desired, first time for me working with web components, very nice!

I'll close this issue and PR. Thanks again!
