### ISSUE TITLE
iconExists() not working on deployed site

### ISSUE THREAD

**Issue by SksOp** [iconify/iconify#282]
### Use case
I am retrieving some names of techstack ex go,react,python from my DB and then I am checking if the logo exists on iconify , if `yes` then I show the logo otherwise I  don't.

```javascript

      "use client"

      # rest of the code

      const logoName = `logos:${tech.name.toLowerCase()}`;
      const renderLogo = iconExists(logoName);
      
      // later
      return <>{isLogoExist && <IconButton sx={{ bgcolor: 'white' }}>{logoRender}</IconButton>}</>

```

### Problem
The problem is its working fine on `dev` server locally, but once I deploy it on vercel it just don't work and return false for every logs. 
The hardcode icons are woking just fine. I tried to print the argument and its type and its also getting logged as expected. 

## My environment
1. Next 13 
2. node 20
3. Deployed on vercel

**Comment by cyberalien** [comment]
Its a problem of bad naming. That function checks if icon exists in component's storage, not on Iconify API.

If you need to get list of icons to find which icon is available, I suggest fetching list of available icons from API and checking that list. See https://iconify.design/docs/api/collection.html

**Comment by cyberalien** [comment]
Alternatively, you can use `loadIcon` function if you need to check only few icons without fetching full list: https://iconify.design/docs/iconify-icon/load-icon.html
