### ISSUE TITLE
[BUG] Deprecation Warning on Nuxt.js build due to package.json export

### ISSUE THREAD

**Issue by hmingv** [iconify/iconify#284]
I encountered the following error when using the Nuxt-Icon module on the Nuxt framework. It seems to be related [to this line of code](https://github.com/iconify/iconify/blob/a8e3b45ecd56e194fd8ef2c3b4eeb6f8c4e68bb1/components/vue/package.json#L27). Can you please help me take a look?

https://github.com/nuxt-modules/icon/issues/140

**Comment by cyberalien** [comment]
That's a weird one because exports are correct.

I suspect code somewhere tries to import `@iconify/vue/` with extra slash at the end, which triggers that warning, but can't find such code anywhere.

**Comment by hmingv** [comment]
It does seem to have no direct relationship with @iconify/vue

When I encountered the .npmrc file, I removed the shamefully-hoist=true line and the problem was solved.
