### ISSUE TITLE
Using with Turbolinks: How to manually tell Iconify to insert icons?

### ISSUE THREAD

**Issue by dtgay** [iconify/iconify#29]
I'm trying to use Iconify with Rails, which uses [Turbolinks](https://github.com/turbolinks/turbolinks). The issue is, on a Turbolinks page load, Iconify doesn't load in icons. It only inserts the icons on a regular, full page load.

With Turbolinks, you can listen for a Turbolinks load:
```javascript
document.addEventListener("turbolinks:load", function() {
  // ...
})
```

Is there an Iconify method I can put inside of that listener to tell it to insert the icons? Or is there another solution?

I'm using Iconify via yarn + webpack, but I've also tried just using the `<script>` tag. It doesn't seem to make a difference.

**Comment by cyberalien** [comment]
Sure. You can use `Iconify.scanDOM();` for that.

**Comment by dtgay** [comment]
Awesome, that worked! I was looking for a method in the function docs here: https://iconify.design/docs/functions/. Not sure if `Iconify.scanDOM();` is meant to be there, but it's currently not. I know a new version is in beta, and maybe the method will be listed in those docs.

Thanks!

**Comment by cyberalien** [comment]
Excellent.

That documentation is old and almost useless. I'm currently working on new documentation, which I hope will be published soon. It is already several times bigger than old documentation, yet I haven't covered third of topics.

Method `scanDOM()` is available in version 2 as well.
