### ISSUE TITLE
在uniapp中怎么使用unocss+iconify实现图标展示啊？

### ISSUE THREAD

**Issue by github-cherry** [iconify/iconify#291]
[在vue中我知道](https://quanyi.blog.csdn.net/article/details/135680388)，但在uniapp中怎么实现呢？按照[vue](https://quanyi.blog.csdn.net/article/details/135680388)的方式引入了，不显示
![image](https://github.com/iconify/iconify/assets/43592730/a2ad9a9a-5688-411f-aa62-87262ee4f90b)

**Comment by cyberalien** [comment]
You are posting to wrong repository. UnoCSS issues should be posted to UnoCSS repository.

In this case I don't think it is UnoCSS issue, but that platform's issue. Make sure it can render SVG as mask images, which it probably can't.
