### ISSUE TITLE
Opacity on icons

### ISSUE THREAD

**Issue by Liritt** [iconify/iconify#294]
Hello, as I was browsing on the icon sets iconify proposes, I crossed upon logos with an opacity option, like ph:question-duotone. It seems like currently we can't change opacity on the Icon component (I am using svelte iconify). Is it going to be added in the future ? I have cases where such option could be very interesting and I don't want to use a raw svg for that...

Thanks in advance for any response !

**Comment by cyberalien** [comment]
Sorry, I have no plans to add that.

Opacity is just one of properties that can be changed. For some icons it is as simple as changing `fill-opacity="0.3"` string, for some icons that use masks it requires parsing mask and changing grayscale color. Also there are options for stroke width, animation duration and option to completely remove animation. All of that are part of same parser.

Adding parser to component would increase its size by a lot. Considering that icon component is bundled and sent to visitors, increasing size for feature that will be rarely used is not a good idea.
