### ISSUE TITLE
Icon toggles visibility when scrolled in/out of viewport - observer="false" does not work?

### ISSUE THREAD

**Issue by av01d** [iconify/iconify#296]
FIrst of all: thanks for Iconify!!! It's brilliant.
I am using 2.0.0 in a new project and I run into a small issue.
I have a button with an iconify icon in it. When this button is scrolled out of the viewport, the icon inside the button becomes hidden, resulting in the button getting smaller (less width). 
I thought that adding `observer="false"` would fix this, but it does not.
Here is a fiddle demonstrating this: https://jsfiddle.net/av01d/7m4rxujq/

I'd really like the iconify-icons to stay visible once they're loaded, regardless of scrolling. (How) Can I do that? Or is this indeed a bug?

**Comment by cyberalien** [comment]
There is attribute for that, but its `observe`, not `observer`.

I recommend setting width and height in CSS to avoid layout shift. Web component is initialised asynchronously by browsers, which means before it is initialised, icon is not rendered and element has no width. I always add this code to CSS:
```css
iconify-icon { width: 1em; height: 1em; }
```

**Comment by cyberalien** [comment]
Oh, there is a bug!

In one place attribute is referenced as `observer` instead of `observe`, which causes it to fail.

**Comment by av01d** [comment]
The documentation is wrong then: https://iconify.design/docs/iconify-icon/, this page clearly states it's `observer`.
And even `observe` doesn't fix it.

**Comment by cyberalien** [comment]
Its bugged more than I thought. Sorry about that.

After fixing naming, it was defaulting to `false` if not set, which worked other way than expected: disabled by default and needed to be enabled.

So I've changed behavior and attribute name. New attribute is `noobserver`. It is a boolean attribute, so does not need a value, just needs to be set. Properly tested it to make sure it works as expected. I'll publish version `2.1.0` in few minutes with fix.

**Comment by cyberalien** [comment]
Published 2.1.0 with fix.

**Comment by av01d** [comment]
I can confirm that 2.1.0 does indeed fix the issue, when using `noobserver`. Thanks a lot for the very quick response.
Don't forget to update your docs: https://iconify.design/docs/iconify-icon/

**Comment by cyberalien** [comment]
Updated docs, which also now uses latest version.

Thanks a lot for noticing bug and reporting it!
