### ISSUE TITLE
`@iconify-icon/react` prop `observe` didn't work

### ISSUE THREAD

**Issue by HoshinoSuzumi** [iconify/iconify#297]
I'm using `@iconify-icon/react` and set prop `observe` to `false`, but the observer still working.

```tsx
<Icon icon={ 'tabler:satellite' } observe={false}/>
```

**Comment by cyberalien** [comment]
That option was bugged in version 2.0.0, in version 2.1.0 it was fixed and renamed to `noobserver`.

See https://github.com/iconify/iconify/issues/296

**Comment by HoshinoSuzumi** [comment]
Thank you very much! sorry I didn't see the previously closed issue.
