### ISSUE TITLE
finding the "real corner" of an svg

### ISSUE THREAD

**Issue by christopherreay** [iconify/iconify#299]
Hi!

Thanks for the amazing project.

I have found it is very useful for my webApp design to be able to combine two SVGs together, with one in the corner of another. I allows me to quickly create complex navigation and process diagrams for users ... without much faffing. iconify-icon makes that a breeze.

Obviously "putting an icon on the corner of another one", is somewhat of an artform.

I have thought of two ways of maybe doing this.

With SVGs, it is reasonably simple to try and brute force calculate the "cornery" most points of the actual picture.

It also seems like this is something that could pretty easily be "crowd informationed".

I think being able to have anchor points as part of (perhaps an alternative) iconify-icon webComponent would be very useful.

A nice way to engage the community.

Obvs some kind of transformers could probably do a good job of it by brute force also.

What do you think?

I guess part of the point is that I am sort of compiling a list of offsets as I go along anyway, so I can use them myself.

**Comment by cyberalien** [comment]
That's a nice use case, but this is not in scope of the project.

Not sure it would be popular enough to warrant development.

Even if code for calculations already existed, I wouldn't add it to web component because it would drastically increase package size. Increasing web component size for a rarely used feature is not acceptable.

Sorry. Closing this as not planned.

**Comment by christopherreay** [comment]
No, I wouldnt add it to the WebComponent either.

But it could be added to a separate component, along with a database of svg specific mount points.

There are many really complex UX processes I have been able to solve elegantly with this technique.

Not important :)

Maybe Ill do it myself.

Great product, thank you will donate when I can
