### ISSUE TITLE
Feature Request: Support for title attribute

### ISSUE THREAD

**Issue by huynhtk** [iconify/iconify#3]
Feature request to support the title attribute.
E.g.
`<i class="iconify" data-icon="ic:baseline-favorite-border" data-width="24px" title="Favorite"></i>`

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="24px" height="24px" style="vertical-align: -0.125em;-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" _ngcontent-c8="" class="iconify ng-tns-c8-0 ng-star-inserted" data-icon="ic:baseline-favorite-border" data-width="24px" title="Favorite"><path d="M16.5 3c-1.74 0-3.41.81-4.5 2.09C10.91 3.81 9.24 3 7.5 3 4.42 3 2 5.42 2 8.5c0 3.78 3.4 6.86 8.55 11.54L12 21.35l1.45-1.32C18.6 15.36 22 12.28 22 8.5 22 5.42 19.58 3 16.5 3zm-4.4 15.55l-.1.1-.1-.1C7.14 14.24 4 11.39 4 8.5 4 6.5 5.5 5 7.5 5c1.54 0 3.04.99 3.57 2.36h1.87C13.46 5.99 14.96 5 16.5 5c2 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.9 10.05z" fill="currentColor"></path></svg>`

SVG element does support title.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title

**Comment by cyberalien** [comment]
That's a good idea for screen readers. Thanks for suggestion.

Since title is valid attribute to any tag, it doesn't require data- prefix. It can be moved directly to SVG element. I'll implement it.

**Comment by cyberalien** [comment]
Implemented in version 1.0.1

**Comment by Karmalakas** [comment]
What's the status of this? I'm on 2.0.0-rc5 and title tag is not rendered. It still remains as attribute in svg tag - `<svg ... title=""><path /></svg>` :(

**Comment by cyberalien** [comment]
I've just tested, it works correctly. Title attribute is passed from placeholder to SVG.

**Comment by cyberalien** [comment]
Oh, ignore that. It was supposed to be moved to `<title>`, but it is rendered as attribute.

**Comment by xVyre** [comment]
Any update on this?

**Comment by cyberalien** [comment]
After evaluating it, I think this is a very bad idea.

Title tag doesn't add anything special. If you need a tooltip, adding `title` for placeholder will keep it as attribute, so you get a tooltip. For screen readers it is recommended to use `aria-label` attribute. Same stuff you would use for `<img>` tag.

Additionally, it would require adding extra useless code to implement it. New version can be used in server side rendering, where DOM is not available, so using DOM to add text node is not an option. Proper implementation would require converting attribute to text node, escaping all special characters to prevent script injection. That's a lot of code that will not be used by 99% of users.
