### ISSUE TITLE
I can't tell why is this happening

### ISSUE THREAD

**Issue by r4rmas** [iconify/iconify#301]
<img width="1307" alt="image" src="https://github.com/iconify/iconify/assets/57473003/34eecfd6-1c19-4d28-904c-bc4a843dc55c">

**Comment by cyberalien** [comment]
Please post your config and html that triggers that bug.

**Comment by r4rmas** [comment]
Well, I don't know. I just installed it

**Comment by cyberalien** [comment]
Can't help you without code sample that triggers that error.

**Comment by r4rmas** [comment]
can't even work 💁🏻‍♂️

**Comment by cyberalien** [comment]
You are doing something wrong. But without any code, I can't help.

It is not "I just installed it". For error to appear, plugin must be triggered first by Tailwind CSS. For Tailwind CSS to trigger plugin, it should find some code that it thinks should be ran by plugin. Therefore, you have added some code to trigger that.

**Comment by r4rmas** [comment]
"it should find some code that it thinks should be ran by plugin".
I see. This is an incompatible plugin for some cases.

**Comment by cyberalien** [comment]
Possibly. But, as I said before, without code I can't help.

**Comment by cyberalien** [comment]
After thinking more about it, error is actually in screenshot: `${string}--${string}`.

So you must have used `icon-[${string}--${string}]` somewhere, which for some reason Tailwind thinks is a valid selector.

**Comment by r4rmas** [comment]
I created a type like that, then removed it, but the error continued. 
I restarted everything and the error continued.

I'm mapping a lot of Tailwind classes and maybe any of them are causing this. 
I think this error wouldn't occur if the plugin provided a non-dynamic way to get icons.

Anyway, the [@egoist solution](https://github.com/egoist/tailwindcss-icons) works well for these cases.
