### ISSUE TITLE
How do you guarantee icons don't change

### ISSUE THREAD

**Issue by Visible-Radio** [iconify/iconify#313]
Let's say you're using the iconify web component in an app. It dynamically fetches the icons based on the string identifier. What if the thing attached to that identifier changes or is removed? Is there a way around this? If I self host the api, can I lock the set of icons that gets served to guarantee consistency?

**Comment by cyberalien** [comment]
Icon sets are kept up to date, which means if something changes in source, it changes in Iconify too.

The only exception is deletion. If icon is removed from source, it is still available in Iconify, just marked as hidden so it does not appear in search results. That guarantees that stuff won't break for users that use that icon.

If you want to make sure icon is never changed, you need to either host API yourself locked to specific version of icon set or use a different solution. There are other icon components and various plugins (Tailwind, UnoCSS) that use `@iconify/json` as dependency, which you can lock down to specific version.

**Comment by Visible-Radio** [comment]
Thanks for the info and the quick reply! I'll look into the self host option - I think it'll suit my use-case better than tailwind. I've got a dockerized app that sets up some navigation based on configuration passed at run-time. There's no way to know in the app source which icons will be needed since that is up to whoever uses the container. I think this would rule out the tailwind option - I would expect it needs to know all of the classnames being used at build time.

Awesome project by the way. Not everyone gets how painful dealing with icons can be. This solves the problem of inlining svgs so they can be styled without having a react wrapper for every. single. icon.

**Comment by cyberalien** [comment]
Thanks!

Yes, for that use case custom API is the best option. Icon component was designed exactly for your use case.
