### ISSUE TITLE
Show API link for icons

### ISSUE THREAD

**Issue by kidonng** [iconify/iconify#316]
First, apologize since this is probably not the best (and correct) place to ask this question.

Can we have like a button on the icon page that show the API link to icons (as documented in [Rendering SVG](https://iconify.design/docs/api/svg.html))? Potential issue I see is this would encourage hotlinking which may not be welcome?

<img width="662" alt="Screenshot 2024-07-10 at 5 30 56 PM" src="https://github.com/iconify/iconify/assets/44045911/60687576-a595-486e-85ee-f70551514894">

I used to be able to copy the link from the CSS tab, but now that tab uses SVG code directly. Meanwhile this bookmarklet works:

```js
javascript:prompt('', location.href.replace('icon-sets', 'api').replace(/\/$/, '.svg'))
```

**Comment by cyberalien** [comment]
No, sorry.

I'm trying to reduce API load. API costs money to run, currently GitHub sponsors don't even cover hosting costs. Currently load is getting close to 100k queries per minute, which API can handle, but usage is growing and I'd like to not encourage that if possible.

So all code samples, except for Iconify Icon web component, offer solutions that do not rely on API.

**Comment by kidonng** [comment]
Sorry to hear that! Yeah it makes sense. I only do hotlinking out of convenience for things I don't control (e.g. Notion page icons), when I build projects I'm definitely using npm packages.
