### ISSUE TITLE
Tailwind plugin: allow non-square icons

### ISSUE THREAD

**Issue by condemil** [iconify/iconify#318]
The following is mentioned in `addIconSelectors()` docs:

> This plugin generates only square icons. Icons that are not square will be resized to fit square.

It would be nice to have an option to generate non-square icons, as I can see it only requires to have original size values in viewBox, width and height attributes in the resulting css file.

**Comment by cyberalien** [comment]
Added option `square` to version `1.1.2` that generates non-square icons:

```js
addIconSelectors({
	square: false,
}),
```
