### ISSUE TITLE
Request to add new icons

### ISSUE THREAD

**Issue by danielmarostica** [iconify/iconify#32]
Some important python libraries icons are missing, such as numpy and scikit-learn.

How is the process of adding new icons?

**Comment by cyberalien** [comment]
There is no automated system yet. I do plan to make it possible to publish icon sets, but it will take a while to develop. For now I'm manually adding icon sets to crawler.

To add icon set, icon set must:
- Have free or open source licence that allows redistribution.
- Be available on GitHub or NPM in SVG or in format that can be easily converted to SVG. Icon sets are automatically updated every few days, so there must be a simple way to retrieving them. For now crawler supports GitHub repositories and NPM packages as source, though support for other package managers is easy to add.
- Icons should have consistent size.

Please post links to icon sets, I'll take a look at them.

**Comment by danielmarostica** [comment]
Hi,

https://github.com/valohai/ml-logos

**Comment by antfu** [comment]
BTW, adding my requests

Octicons V2 - https://github.com/primer/octicons (the current one in Iconify is v1)
Codicon - https://github.com/microsoft/vscode-codicons (the icons from VS Code)

Thanks, and I am happy to help if there is any guide on how to add new ones.

**Comment by cyberalien** [comment]
Thanks!

Updated Octicons. Crawler was using NPM as source, which still has old version. Switched source to GitHub.

Added Codicon.

ML Logos is not a good set. Icons don't have any dimensions that would make sense and spacing around logos seem to be random. It is just a set of images collected from various websites, not an icon set.

**Comment by PeterShaggyNoble** [comment]
@danielmarostica, if you're looking for _specific_ brand icons to be added then please submit a request to @simple-icons.

**Comment by Darshan-Ramesh** [comment]
Could you also please add this-> https://github.com/PyTorchLightning/pytorch-lightning/blob/master/docs/source/_images/logos/lightning_icon.svg
