### ISSUE TITLE
Add "Iconsax" set

### ISSUE THREAD

**Issue by imrofayel** [iconify/iconify#327]
Consider adding **Iconsax** Icons created by [Vuesax](https://vuesax.com/), Its official website is [Iconsax.io](https://iconsax.io/) which no longer available maybe but you can check icons with downloadable SVGs here [Iconsax](https://iconsax-react.pages.dev/).

Its Official repo is https://github.com/lusaxweb/iconsax

According to [Iconduck](https://iconduck.com/sets/iconsax-icon-set), Iconsax is an Icon Set of 6,002 icons. It's been open sourced with the license: MIT License. All icons can be used for personal & commercial purposes. You can check and get SVGs from this site too.
 
there's this package [vue-iconsax](https://www.npmjs.com/package/vue-iconsax), but I wanna use these icons in Nuxt project like other iconify icon sets.

**Comment by cyberalien** [comment]
See https://github.com/iconify/icon-sets/issues/23

That icon set is not MIT. It has a custom license, not a proper open source license. Iconduck is misusing it with wrong license.
