### ISSUE TITLE
Imports with "assert" keyword are not supported anymore

### ISSUE THREAD

**Issue by thetutlage** [iconify/iconify#330]
Sorry, if this is not the correct repo to report the issue. I can move it to a different repo :)

I am using the [@iconify-json/tabler](https://www.npmjs.com/package/@iconify-json/tabler) package which uses JSON imports with the `assert` identifier. 

The `assert` identifier has been removed by Node.js in favor of the new ECMA proposal of [Import attributes](https://github.com/tc39/proposal-import-attributes).

It will be nice if we can use the newer syntax :)

**Comment by MidAutumnMoon** [comment]
Deno also deprecated the `assert` identifier starting from v1.46 released weeks ago. Hope this project can keep up with the changes :)

**Comment by cyberalien** [comment]
Sorry, forgot about this issue. Was away when it was initially posted, saw it on phone, thought that I should test it when I get back... and forgot about it. Thanks for bumping it.

**Comment by cyberalien** [comment]
Done.

Currently all packages are being updated. Should take an hour or so to update everything.

Packages with new syntax have a new minor version `1.2.x`, so those devs who use Node 16 can continue using `1.1.x` with old syntax. I don't think this change is big enough to warrant a new major version.

**Comment by cyberalien** [comment]
All packages have been updated

**Comment by thetutlage** [comment]
Thanks @cyberalien ❤️
