### ISSUE TITLE
Solid start error

### ISSUE THREAD

**Issue by tutods** [iconify/iconify#331]
Hi everyone
I'm using the `@iconify/solid` package on a solid start project, but I'm facing this error:
<img width="479" alt="image" src="https://github.com/user-attachments/assets/19dcf84f-6762-49a1-aeeb-d2e29287612f">

Anyone already have this issue?

**Comment by cyberalien** [comment]
Can you create a reproduction? That screenshot is useless, cannot do anything with it and cannot even understand where error is.
