### ISSUE TITLE
Vite build warning with `@iconify/tailwind` package

### ISSUE THREAD

**Issue by sardor01** [iconify/iconify#334]
[plugin:vite:resolve] [plugin vite:resolve] Module "node:fs" has been externalized for browser compatibility, imported by "/project/node_modules/.pnpm/@iconify+tailwind@1.1.3/node_modules/@iconify/tailwind/dist/plugin.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

**Comment by cyberalien** [comment]
Why are you bundling plugin?
