### ISSUE TITLE
Rendering fails on first statement.

### ISSUE THREAD

**Issue by 72fcosta** [iconify/iconify#337]
Rendering fails on first request (test 2), only in the first statement.

- "vue": "3.5.7" (composition api)
- "pinia": "2.2.2"

test 1
```
<script setup lang="ts">
   import { onMounted, ref } from 'vue'
   import { useGlobalStore } from '@/stores/globalStore'
   const globalStore = useGlobalStore()
   const myIcon = ref('')
   const myIcon2 = ref('')

   onMounted(() => {
      myIcon.value = globalStore.myIcon // const myIcon = ref('tabler--books')
      myIcon2.value = 'tabler--books'
      console.log(myIcon.value === myIcon2.value) // log: true
   })
</script>
<template>
   <div>
       <span class="iconify" :class="myIcon"></span> <!-- success -->
      <span class="iconify" :class="myIcon2"></span> <!-- success -->
   </div>
</template>
```

test 2
```
<script setup lang="ts">
   import { onMounted, ref } from 'vue'
   import { useGlobalStore } from '@/stores/globalStore'
   const globalStore = useGlobalStore()
   const myIcon = ref('')
   const myIcon2 = ref('')

   onMounted(() => {
      myIcon.value = globalStore.myIcon // const myIcon = ref('tabler--edit')
      myIcon2.value = 'tabler--alien'
      console.log(myIcon.value === myIcon2.value) // log: false
   })
</script>
<template>
   <div>
       <span class="iconify" :class="myIcon"></span> <!-- fail -->
      <span class="iconify" :class="myIcon2"></span> <!-- success -->
   </div>
</template>
```

test 3
```
<script setup lang="ts">
   import { onMounted, ref } from 'vue'
   import { useGlobalStore } from '@/stores/globalStore'
   const globalStore = useGlobalStore()
   const myIcon = ref('')
   const myIcon2 = ref('')
   onMounted(() => {
      myIcon.value = globalStore.myIcon // const myIcon = ref('tabler--alien')
      myIcon2.value = 'tabler--edit'
      console.log(myIcon.value === myIcon2.value) // log: false
   })
</script>
<template>
   <div>
       <span class="iconify" :class="myIcon"></span> <!-- success -->
      <span class="iconify" :class="myIcon2"></span> <!-- success -->
   </div>
</template>
```

**Comment by cyberalien** [comment]
Looks like you are using `@iconify/iconify` package. It works by swapping elements to render SVG. That doesn't work well with various frameworks, so it should not be used when you are using Vue.

Furthermore, `@iconify/iconify` package has been deprecated.

For Vue there is `@iconify/vue` or, even better solution that works perfectly with Nuxt, `iconify-icon` package.

Closing this as not fixable because it is a known issue that cannot be fixed and package is deprecated.

**Comment by 72fcosta** [comment]
I'm using @iconify/tailwind and the repository indicated on NPM is github.com/iconify/iconify.
![Screenshot from 2024-09-23 17-07-27](https://github.com/user-attachments/assets/f59b1039-0a64-4eeb-8f98-5c4d07e79dcb)

**Comment by cyberalien** [comment]
Oh I see. Saw span syntax, assumed it was old package.

If it fails to render, it means CSS for icon is missing, which means Tailwind didn't register that as class name when parsing your Vue project. Add class name for icon to whitelist in tailwind config.

**Comment by 72fcosta** [comment]
Thanks!

`safelist: [{ pattern: /tabler--.+/ }]`
