### ISSUE TITLE
uniapp微信小程序不显示图标

### ISSUE THREAD

**Issue by chergn** [iconify/iconify#338]
结果：
![image](https://github.com/user-attachments/assets/222d4484-ec76-4a06-936e-628e4edaf185)

我的代码
![image](https://github.com/user-attachments/assets/eb83c77b-dcc1-465a-b77f-446b2cd132ad)

![image](https://github.com/user-attachments/assets/1e95153e-237a-49c0-b843-a0cf70083d50)

![Snipaste_2024-09-30_09-13-25](https://github.com/user-attachments/assets/c31c7c9a-ac8f-432d-8a24-d31a541da1a5)

**Comment by cyberalien** [comment]
Please do not open issues like that.

1. Please at least describe the issue.
2. Provide code samples, not screenshots.
3. Post to correct repositories. This is not a repository for uniapp.
