### ISSUE TITLE
add harmonyos icons

### ISSUE THREAD

**Issue by transtone** [iconify/iconify#340]
add harmonyos icons: https://developer.huawei.com/consumer/cn/design/harmonyos-icon/

**Comment by cyberalien** [comment]
I don't see any links to git repositories.

Icons must be available somewhere, where it would be possible to keep them up to date automatically, such as git repository. Downloading from website is not an option.

**Comment by cyberalien** [comment]
Also, I don't see license. Icon sets must have valid open source icons.

**Comment by transtone** [comment]
> Also, I don't see license. Icon sets must have valid open source icons.

sorry, I not mention the open source license.
