### ISSUE TITLE
Content Shift Issue in React When Changing Routes with Iconify Icons

### ISSUE THREAD

**Issue by Mizan-Rifat** [iconify/iconify#344]
I'm experiencing a content shift issue when using the @iconify/react package in my React application, specifically when changing routes. The layout shifts as the icons load, causing a visible jump in the page's layout until the icons fully render. This occurs even though I've set explicit height and width for the icons.

I'm using it like this:
```
import { Icon } from '@iconify/react';

<Icon icon="material-symbols:mail-outline-rounded" height={20} width={20} />
```

I have recorded a video showcasing the issue. You can view it 

https://github.com/user-attachments/assets/0345678f-dd1a-4a82-b097-1f37f623f9b1

**Comment by cyberalien** [comment]
Unfortunately that's expected behavior because of server side rendering mess. See https://iconify.design/docs/icon-components/react/#ssr

There is no solution for using component. I recommend switching to one of alternative solutions:
- If you need to load icons on demand, use web component: https://iconify.design/docs/iconify-icon/
- Otherwise use Unplugin Icons: https://iconify.design/docs/usage/svg/unplugin/

**Comment by Mizan-Rifat** [comment]
> Unfortunately that's expected behavior because of server side rendering mess. See https://iconify.design/docs/icon-components/react/#ssr
> 
> There is no solution for using component. I recommend switching to one of alternative solutions:
> 
> * If you need to load icons on demand, use web component: https://iconify.design/docs/iconify-icon/
> * Otherwise use Unplugin Icons: https://iconify.design/docs/usage/svg/unplugin/

My app is not server-side rendered, and based on [this documentation](https://iconify.design/docs/iconify-icon/react.html), I believe I am already using the web component in React. I also tried the `loadIcons` function, but the issue remains the same.

**Comment by cyberalien** [comment]
Component cannot detect if app is server side rendered or not, so it has to account for hydration.

Web component package is `@iconify-icon/react`, but syntax is the same.

**Comment by Mizan-Rifat** [comment]
> Component cannot detect if app is server side rendered or not, so it has to account for hydration.
> 
> Web component package is `@iconify-icon/react`, but syntax is the same.

Is there any way to load the icons first and then render the component, so the flickering doesn't happen? I thought this [documentation](https://iconify.design/docs/icon-components/react/load-icons.html#iconify-for-react-function-loadicons) addresses that issue, but when I use `loadIcons`, it doesn't work and still causes flickering.

**Comment by cyberalien** [comment]
Actually, I forgot that there is a way to do that. Add `ssr={true}` to props

**Comment by Mizan-Rifat** [comment]
> Actually, I forgot that there is a way to do that. Add `ssr={true}` to props

Thanks, It works

**Comment by Mizan-Rifat** [comment]
> Actually, I forgot that there is a way to do that. Add `ssr={true}` to props
Thanks, it worked.
