### ISSUE TITLE
Add the ability to remove `stroke-width` in `iconToSVG()`

### ISSUE THREAD

**Issue by laymonage** [iconify/iconify#346]
Hey, thanks for such a cool project!

I'm currently using it via [astro-icon](https://github.com/natemoo-re/astro-icon). It has the ability to render the icons as sprites using the `<symbol>` element, to be reused in different places using the `<use>` element, e.g.

```html
<!-- First usage of the icon -->
<svg width="1em" height="1em" viewBox="0 0 24 24" data-icon="tabler:music">
  <symbol id="tabler:music">
    <!-- Generated by `iconToSVG().body` -->
    <g
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
    >
      <path
        d="M3 17a3 3 0 1 0 6 0a3 3 0 0 0-6 0m10 0a3 3 0 1 0 6 0a3 3 0 0 0-6 0"
      ></path>
      <path d="M9 17V4h10v13M9 8h10"></path>
    </g>
  </symbol>
  <use xlink:href="#tabler:music"></use>
</svg>
<!-- Somewhere else in the document -->
<svg viewBox="0 0 24 24" class="custom-styles">
  <use xlink:href="#tabler:music"></use>
</svg>
```

[It utilizes the `iconToSVG()`](https://github.com/natemoo-re/astro-icon/blob/4060744f8b12016b7ff73f1cd519a8b4100604b7/packages/core/components/Icon.astro#L112-L129) function to get the SVG body (rendered as the `<g>` element inside the `<symbol>` as seen above.

This works really well. You can customize e.g. the width and height of each usage via the `custom-styles` class in CSS.

Unfortunately, changing `stroke-width` in CSS or via an attribute directly on the SVG does not seem to have any effect. However, if you remove the `stroke-width` attribute on the `<g>` element, you can see that the custom stroke widths get applied to each individual usage of the icon. This would be great! See this codepen for example: https://codepen.io/laymonage/pen/oNKqXLW

From what I've seen, the `stroke-width="2"` attribute comes from [the icon's JSON data](https://github.com/iconify/icon-sets/blob/abcfbeb4f5e9bf44edaa0f2e5c07bdbd652f6598/json/tabler.json#L11698), which in turn comes from [the source icon itself](https://github.com/tabler/tabler-icons/blob/69752f43def7288deee802433f10c77f2a41ce50/icons/outline/music.svg?short_path=58c2df3#L14).

I understand that removing the `stroke-width` from the JSON data itself or asking the icon library's author to remove that attribute from the SVG would be too disruptive. Hence, I'm asking is it possible to allow the `iconToSVG()` util function to remove the attribute based on an optional parameter?

P.s. I'm not sure if `iconToSVG()` would be the right place for this logic, but that's what the astro-icon package uses. As long as other packages like astro-icon can use it, I'm happy.

Thanks!

**Comment by cyberalien** [comment]
No, sorry. This is a very specific use case and issue is caused by using SVG sprites.

Avoid using SVG sprites. Not only you cannot control props, like in your example, often icons that use CSS and animations are broken.
