### ISSUE TITLE
Unknown file extension ".jsx" with vitest

### ISSUE THREAD

**Issue by sysmat** [iconify/iconify#347]
- deps: node 20.18.0
```
"typescript": "^5.6.3",
    "vite": "^5.4.10",
    "vite-plugin-solid": "2.10.2",
    "vitest": "^2.1.4"
"@solidjs/testing-library": "^0.8.10",
```

- error:

```
TypeError: Unknown file extension ".jsx" for solidjs_ts\node_modules\.pnpm\@iconify-icon+solid@2.1.1_solid-js@1.9.3\node_modules\@iconify-icon\solid\dist\iconify.jsx
```

**Comment by cyberalien** [comment]
This is not related to component, but to your test config.

**Comment by sysmat** [comment]
then, why is working for other libs

**Comment by cyberalien** [comment]
`.jsx` files should be parsed by anything that parses SolidJS components, tests are also most likely using `.jsx` or `.tsx`. If they don't work, you have setup test environment incorrectly.

If tests do work, but it throws error for `iconify-icon` component, question is why extension is not parsed in files from `node_modules`. That's a configuration issue.

**Comment by sysmat** [comment]
"@iconify-icon/solid": "^2.1.1",

**Comment by sysmat** [comment]
in https://github.com/iconify/iconify/tree/main/iconify-icon-demo/solid-demo you should have some tests, and upgrade dependency

**Comment by sysmat** [comment]
and in vitest github I find in config section

```
resolve: {
    preserveSymlinks: true,
  },
```

**Comment by spuxx-dev** [comment]
Is it actually necessary for the package to compile to JSX? This *does* seem to cause problems and common solutions like enabling `preserveSymLinks` aren't always a good idea (since that may break module resolution e.g. when using pnpm).

Could the package not expose plain js?
