### ISSUE TITLE
Emoji to Iconify

### ISSUE THREAD

**Issue by ivan-cc** [iconify/iconify#35]
Извините, что по-русски. Думаю, что не получится донести мысль с моим уровнем английского :(

Было бы удобно сделать базу соответствия иконок каким-либо эмодзи и соответственно их обрабатывать, т.е. пишем в коде:
`<span class="iconify" data-collection="mdi">📝</span>`
а в результате подставляется иконка из набора MDI
`<span class="iconify" data-icon="mdi:clipboard-edit" data-inline="false"></span>`

Таким образом, можно обыграть ситуацию, когда иконки из iconify по какой-то причине не подгрузились. Это будет лучше чем сейчас - пустота вместо иконок.

**Comment by cyberalien** [comment]
Это уже можно использовать. Если иконка не загрузилась, содержимое `<span />` не удаляется.

Автоматически это не сделать. Большинство иконок не имеет аналогичных эмодзи.
