### ISSUE TITLE
Option to disable Cookies | GDPR

### ISSUE THREAD

**Issue by develth** [iconify/iconify#354]
Hi,

would be nice to have an option to disable the two(or all) Cookies `iconify-count` and `iconify-version` set by this framework.
IMHO it is not necessary for run the Site & hard to explain the needs to set this cookie regarding GDPR.

Came up with via https://github.com/nuxt/icon/issues/94

Thanks!

**Comment by cyberalien** [comment]
It is used for caching. You can disable it by disabling cache `disableCache('all')`: https://iconify.design/docs/icon-components/vue/disable-cache.html

**Comment by cyberalien** [comment]
And those are not cookies. That is localStorage or sessionStorage

**Comment by develth** [comment]
Thanks for the quick info @cyberalien 
Regarding GDPR it doesn´t matter. It is saved on the client´s device.

**Comment by cyberalien** [comment]
I think this feature has outlived its purpose. It was great at start of project when API was slower and less reliable, but no longer needed. Furthermore, storage caching doesn't have a simple way to expire cached data. Then there are potential GDPR issues.

So I'll remove it in next patch.

**Comment by develth** [comment]
many thanks for taking this topic serious!
Wish you nice holidays
