### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by GbrAntunes** [iconify/iconify#37]
Does it work with Typescript? i'm getting the declaration types error and can't find the correspondent @types.

**Comment by antfu** [comment]
Try install @iconify/iconify@2, it's rewritten in TypeScript

**Comment by cyberalien** [comment]
`@types` packages are needed only for libraries that do not have TypeScript definition files. Iconify packages are written in TypeScript and have definition files.

What NPM package are you experiencing issues with?
