### ISSUE TITLE
Custom SVG icon with '-' in the file name

### ISSUE THREAD

**Issue by goddas** [iconify/iconify#45]
I'm using this example: https://docs.iconify.design/sources/bundles/examples/svg-framework-full.html

It works great, except that a file like thumbs-up.svg, when bundled, the custom icon will have a name of just "up".
Is there way to keep the full name, so I can use the icon like
`<span class="iconify-inline" data-icon="custom:thumbs-up"></span> ` instead of just `..."custom:up"...` ?

**Comment by cyberalien** [comment]
Thanks for noticing!

Replace
```js
.ImportDir(dir)
```
with
```js
.ImportDir(dir, {
					prefix,
				})
```

**Comment by goddas** [comment]
That fixed it, thanks!
