### ISSUE TITLE
Question: why is npm install using --save-dev ?

### ISSUE THREAD

**Issue by garytalmes** [iconify/iconify#46]
I notice that the instructions indicate to install the package with `npm install --save-dev ` but this seems counter-intuitive to me. Wouldn't the library be needed in production as well. Can you please confirm, and I'd recommend amending the docs either way just to avoid any confusion.

**Comment by cyberalien** [comment]
Which package are you referring to? SVG framework or one of components?

For most components and for SVG framework you should bundle it, so production file has only one script file to include in web page. It is bundled during development, so it is a dependency only during development. In production it is included in the bundle and bundle does not depend on package anymore.

**Comment by cyberalien** [comment]
Also, for SVG framework you can avoid bundling it and use it as dependency, but then you will need to link to SVG framework script in page. It would be a bad idea to link to file inside node_modules in a public document.

Therefore SVG framework script is better to be either included from external website (such as link to code.iconify.design) or copied somewhere. If it is linked as external script and used in bundle as external variable, it is no longer a local dependency and used only during development. If it is copied somewhere, it is done during development, so it is also only a dev dependency.

**Comment by garytalmes** [comment]
Hi - I'm referring to the Iconify For React package, as referenced here:  https://github.com/iconify/iconify/tree/master/packages/react

Oh, I see what you mean -- during the build process all the resources are bundled then, is that correct? (Sorry, I didn't know that the build process also assembled fonts/svg in this way).

**Comment by cyberalien** [comment]
Yes, you are correct. It is bundled during development and module is not accessed in production (it is accessed as part of bundle, not as external file from node_modules), therefore it is a dev dependency.

**Comment by garytalmes** [comment]
Thanks very much!
