### ISSUE TITLE
@iconify-icons/xxx vs @iconify/icons-xxx and SSR application.

### ISSUE THREAD

**Issue by nghiepit** [iconify/iconify#49]
Hi,

Today, I see all icon packages move to `@iconify-icons/xxx` instead of `@iconify/icons-xxx `
The `@iconify-icons/xxx` will crash in SSR, for example with `Next.js`.
Because NodeJS doesn't support ES modules syntax.

What happens if I'm still using the old`@iconify/icons-xxx`? Is it still up to date?

![image](https://user-images.githubusercontent.com/4768095/98390307-c011d500-2087-11eb-90fc-f134cbea1e27.png)

**Comment by cyberalien** [comment]
Both are up to date. Publish script updates both versions, so you can use whatever you prefer.

More and more bundlers switch to modern ES syntax, some, such as Vite used for Vue 3, no longer support CommonJS, so code samples use ES packages by default. In React tests I've been using react-scripts package, which works well with both ES and CommonJS packages.

**Comment by cyberalien** [comment]
Also see Iconify documentation: https://docs.iconify.design/sources/npm/

**Comment by nghiepit** [comment]
@cyberalien Thanks,  I was clear.
