### ISSUE TITLE
CC License

### ISSUE THREAD

**Issue by Aspie96** [iconify/iconify#50]
The CC License doesn't exist. There are multiple different CC licenses.

Some icons report " CC 4.0" as "License", which means nothing, as in https://iconify.design/icon-sets/bx/bxs-network-chart.html. I suggest updating it once it gets fixed in the original source.

For that icon set, I opened an issue in https://github.com/atisawd/boxicons/issues/111.

**Comment by cyberalien** [comment]
Thanks for noticing. For that icon set, license in package is `(CC-BY-4.0 OR OFL-1.1 OR MIT)`, but that applies to entire repository. In readme, license for icon is `CC 4.0`, so I guess correct license would be `CC-BY-4.0`.

**Comment by Aspie96** [comment]
I do not know if it'd be good to correct it until they do: maybe it's best to leave this issue open until then. But "CC 4.0" does not mean anything that I know of. There are many "CC 4.0" licenses and have very little in common.

I agree with you it's almost defenitely CC-BY-4.0 what they mean, as I wrote in that issue, which I hope they fix soon in their readme.

**Comment by cyberalien** [comment]
Yes, I agree.

**Comment by Aspie96** [comment]
Ok, I checked better and I can almost defenitely be sure it's the Creative Commons Attribution 4.0 International Public License they are referring to.

They say:
> You can read more about the license here!

The link is broken.

But the home page of the website brings us to https://boxicons.com/usage/#license, which also mentions this non-existing "CC 4.0" license. However, that links directly to the CC-BY 4.0 license.

If those are actually the same icons on iconify (which I didn't check), I think it's pretty clear, from both the package.json we mentioned and that link that they are referring to CC-BY. If not, I'd wait.

**Comment by Aspie96** [comment]
Ok, I digged even further and boxicons.com does link back to that repository. At this point I'd assume it's pretty safe to say CC-BY 4.0, everything considered.

**Comment by cyberalien** [comment]
I've changed license to CC-BY 4.0 in files, but will keep this issue open for now until icon set authors confirm it.

**Comment by cyberalien** [comment]
Looks like this is a dead end. Author no longer maintains icon set, so I doubt license question will ever get answered.

Will keep license for icon set as `CC-BY-4.0`, which seems to be correct license.
