### ISSUE TITLE
Continuous 'Loading icon finder...'

### ISSUE THREAD

**Issue by barker2905** [iconify/iconify#51]
Using Sketch, the plugin opens but continues to load 'icon finder' to no end. The plugin was working fine at the beginning of my design session but randomly stopped working. I tried closing and reopening the plugin, and restarting Sketch (as instructed), I also rebooted my Mac but still no success.

**Comment by cyberalien** [comment]
I've just started Sketch to test it, getting the same error too. That's good because I can finally debug that mysterious error!

Temporary fix that works for me: right click in plug-in window, select "Reload".

**Comment by cyberalien** [comment]
Looks like error is caused by Sketch Web View. It sometimes fails to send `ready-to-show` event.

Try updating to 1.1.8 that I've just published. It uses workaround for that event. Please tell me if it solved plug-in issue.

**Comment by barker2905** [comment]
The "Reload" works for me also! Unfortunately though, update 1.1.8 doesn't seem to be working. When I select "Update" in the Plugin window, it doesn't run the update. It doesn't do anything. I seem to be stuck with an update I can't action.

**Comment by cyberalien** [comment]
Try installing manually from plug-in repository: https://github.com/iconify/iconify-sketch/releases

Download `iconify.sketchplugin.zip` for version 1.1.8, click zip file unpack it, click plug-in file to install.

**Comment by barker2905** [comment]
That doesn't seem to work either. I have attached some photos of the messages I'm getting.
After clicking the plugin file I get 'Shot 1', I then press "Replace" and get 'Shot 2'. After that, nothing happens, update is still there.

<img width="267" alt="Shot 1" src="https://user-images.githubusercontent.com/74615240/99443328-93c14880-2912-11eb-907b-afa26208c3d7.png">
<img width="266" alt="Shot 2" src="https://user-images.githubusercontent.com/74615240/99443332-9459df00-2912-11eb-9694-f7ddcb595900.png">

**Comment by cyberalien** [comment]
I've made another attempt at publishing update, this time without Sketch Plugin Manager. 

Version 1.1.9 is available here: https://github.com/iconify/iconify-sketch/releases/tag/1.1.9

**Comment by barker2905** [comment]
Version 1.1.9 works temporarily but then crashes Sketch after a few moments. I tried it a few times with the same results.

**Comment by cyberalien** [comment]
Try file in attachment.

It is a very very early version of new generation of plug-in. It was written in last few hours based on upcoming Iconify Icon Finder. Whatever is causing Sketch to crash seem to not affect new code base.

This version is almost fully functional: that is it can search, browse and import icons, but could have some bugs because for icon import I've just copied code from old plug-in. Tomorrow I'll rewrite icon import process. At least it doesn't crash, unless you close plug-in window by clicking X in top left corner, but that seem to affect all plug-ins that use Sketch Web View. To close window without crashing use "Close" button in footer.

[iconify.sketchplugin.zip](https://github.com/iconify/iconify/files/5556589/iconify.sketchplugin.zip)

**Comment by barker2905** [comment]
Amazing, works exactly as you said! I'll close the case for now and await the new version with the new import process. I appreciate the speedy response, thank you!

**Comment by cyberalien** [comment]
Awesome.

I've attached updated version with correct import process. It appends imported icons to current page, does not take into account selected layers. Improved import, which considers currently selected layers will take a bit longer to develop.

Other functionality: plug-in remembers last session and you can select multiple icons (button in top right corner above icons list toggles mode to select multiple icons).

Plugin still crashes when you close it by closing window. As far as I can tell by browsing various recent bug reports, it affects all plug-ins when running Sketch on Big Sur for at least few more people. Close button in footer closes plug-in without crashing.

[iconify.sketchplugin.zip](https://github.com/iconify/iconify/files/5559008/iconify.sketchplugin.zip)
