### ISSUE TITLE
Error building with iconify api

### ISSUE THREAD

**Issue by igorgarciaco** [iconify/iconify#55]
When I Run build inside GatsbyJS it says `Building static HTML failed` but only **Iconify for React with API.** method

![image](https://user-images.githubusercontent.com/36867094/102529807-32120c80-407f-11eb-9f9b-6e3edd4ee701.png)

Im wan't the Api version because I need to call the icon name with a string

**Comment by cyberalien** [comment]
I haven't used Gatsby. Can you explain what that build process is supposed to do?

**Comment by igorgarciaco** [comment]
> I haven't used Gatsby. Can you explain what that build process is supposed to do?

gatsby build creates a version of your site with production-ready optimizations like packaging up your site’s config, data, and code, and creating all the static HTML pages that eventually get rehydrated into a React application. It runs when you deploy.

**Comment by cyberalien** [comment]
Can you make a simple test case, which would allow me to debug that issue?

Icon component with API is not a simple component, so it is not easy to render. It has a state. When you call it first, it checks if data for icon is available. If it is available, icon is rendered immediately, which should be fine with Gatsby. 

However, if icon data is not available, it doesn't render anything. Render function returns null. Component sends request to API, which is asynchronous. When data from API is available, event is triggered, state changes, forcing component to re-render and it renders icon. Loading process is asynchronous, it also relies on Fetch API, which is most likely not available during Gatsby's build process.

Easiest workaround is to provide icon bundles. Documentation for it is here: https://docs.iconify.design/sources/bundles/ and documentation specific to React component is available here: https://docs.iconify.design/sources/bundles/react-with-api.html

**Comment by igorgarciaco** [comment]
How do I generate the icon data for bundle?
Here is an example what Im trying to do

```
import React from "react"

import "../css/card-icon.css"
import { Col } from 'reactstrap';

// Google Material Icons https://iconify.design/icon-sets/ic/
import { Icon } from '@iconify/react-with-api'

const CardIcon = ({ iconName, iconLabel }) => {

    return (
        <>
            <Col>
                <div className="card-icon-wrapper">
                    <Icon icon={iconName} className="icon" color="var(--primary-color)"/>
                    <p className="icon-label">{iconLabel}</p>
                </div>
            </Col>
        </>
    )
}

export default CardIcon
```

**Comment by cyberalien** [comment]
Do you know all possible values for `iconName`? If yes and you can create list of those icons, you can use this example to generate bundle: https://docs.iconify.design/sources/bundles/examples/component-simple.html

**Comment by cyberalien** [comment]
I did some research, looks like Gatsby can handle such components if data is loaded after component is mounted.

Try attached files. Replace `node_modules/@iconify/react-with-api/dist` with contents of attached archive. I'm not sure if it will help, but it might.
[dist.zip](https://github.com/iconify/iconify/files/5712202/dist.zip)

**Comment by cyberalien** [comment]
Tested Gatsby, got error message and after debugging it I think I've figured it out.

Try files in attachment. Replace files `node_modules/@iconify/react-with-api/dist`
[Archive.zip](https://github.com/iconify/iconify/files/5714576/Archive.zip)

**Comment by igorgarciaco** [comment]
> Do you know all possible values for `iconName`? If yes and you can create list of those icons, you can use this example to generate bundle: https://docs.iconify.design/sources/bundles/examples/component-simple.html

I do know the values for `iconName` the idea is that I want to use all iconify names whenever I want haha.

> Tested Gatsby, got error message and after debugging it I think I've figured it out.
> 
> Try files in attachment. Replace files in `node_modules/@iconify/react-with-api/dist`
> [Archive.zip](https://github.com/iconify/iconify/files/5714576/Archive.zip)

wow it works, thank you <3 but only locally for now, since im using gatsby cloud or Netlify it downloads node modules for himself.

**Comment by cyberalien** [comment]
Excellent!

I've just published update, so all you need to do is update dependencies.
