### ISSUE TITLE
Support for react 17 

### ISSUE THREAD

**Issue by mjkl-gh** [iconify/iconify#59]
First of all many thanks for developing this library. It's been of great use!

Unfortunately the base project I used for my project moved to React 17 recently. NPM install now returns:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: esp-dsmr@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from @iconify/react@1.1.3
npm ERR! node_modules/@iconify/react
npm ERR!   @iconify/react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

Will this library support react 17 in the near future? Or is there something else I'm missing?

**Comment by cyberalien** [comment]
Thanks!

It should work fine with 17. I guess it would be safe to just remove peer dependency and assume users do have some version of React installed without explicitly listing it in dependencies. I'll test it.

**Comment by cyberalien** [comment]
Works fine without peer dependencies, so I've removed it. Tested with React 17, no issues.

Install `@iconify/react@beta` for latest version.

**Comment by cyberalien** [comment]
Fixed in version 1 as well.
