### ISSUE TITLE
Add freeicons.io ?

### ISSUE THREAD

**Issue by MentalGear** [iconify/iconify#60]
Thanks for this big library ! Maybe adding freeicons.io would be a good candidate ?

**Comment by cyberalien** [comment]
That's a website with many small icon sets, not an icon set.

For an icon set to be added to Iconify, it needs to:
- Have open source license.
- Be available at GitHub or NPM (or something similar, where icons can be automatically downloaded from to keep them up to date).

All icon sets on that website do not match those requirements.
