### ISSUE TITLE
getting icons list as json

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [iconify/iconify#61]
hey there.
this projects looks promising.
I was looking for a way to get icons list of an iconset in json. e.g. material icons or font awesome full icons list. I couldn't find it in docs. or maybe I didn't read carefully 😅
is there a way for this?

thank you

**Comment by cyberalien** [comment]
You can find all data in this repository: https://github.com/iconify/collections-json in directory "json".

Format of JSON files is in documentation: https://docs.iconify.design/types/iconify-json.html

**Comment by Mohsen-Khakbiz** [comment]
that's what I wanted. thank you!
