### ISSUE TITLE
How to use own set of SVG files with @iconify/react?

### ISSUE THREAD

**Issue by aivenkimmob** [iconify/iconify#63]
We have a bunch of svg icons in a directory: a.svg, b.svg etc. They're our brand internal icons that are not meant to be released as a public icon set for now. I'd like to make an internal package out of them, and use the good core API `@iconify/react` package has to convert the icons into React components.

The end goal is that we could do this:

```tsx
import { Icon } from '@iconify/react';
import ourLogo from 'our-internal-package/ourLogo';
```

But how can one build the `our-internal-package`? I checked into the iconify documentation and tooling, and found that [this script](https://docs.iconify.design/tools/node/import-mdi.html) is handy to convert svg files into a JSON bundle. However the bundle is large and we'd like to split it into individual files. When checking `@iconify/icons-teenyicons` package, each icon corresponds to two files, for example `add-outline` icon:

**node_modules/@iconify/icons-teenyicons/add-outline.d.ts**:
```typescript
interface IconifyIcon {
    body: string;
	left?: number;
	top?: number;
	width?: number;
	height?: number;
	rotate?: number;
	hFlip?: boolean;
	vFlip?: boolean;
}
declare const data: IconifyIcon;
export default data;
```

**node_modules/@iconify/icons-teenyicons/add-outline.js**:
```javascript
var data = {
	"body": "<g fill=\"none\"><path d=\"M7.5 1v13M1 7.5h13\" stroke=\"currentColor\"/></g>",
	"width": 15,
	"height": 15
};
exports.__esModule = true;
exports.default = data;
```

How can we turn the icons JSON bundle into a set of type definition and JS files, similar to how @iconify/teeny-icons is released?

**Comment by cyberalien** [comment]
Export is done with `@iconify/tools` package.

Sample code:
```js
const tools = require('@iconify/tools');

(async () => {
	// Import icons from directory 'svg'
	const collection = await tools.ImportDir('svg');

	// Clean up and optimise all icons
	await collection.promiseAll((svg) => tools.SVGO(svg));

	// Export as components
	await tools.ExportComponent(collection, 'icon-components', {
		sources: false,
		// Set to true to generate CommonJS modules
		commonjs: false,
	});
})();
```

That code imports all icons from directory 'svg'. Then it optimises icons. Then it exports them as components with ES export syntax (change 'commonjs' option to true to export CommonJS modules).

I've just noticed that components export is not listed in documentation, so I'll add it. Until then you can see list of options for ExportComponent function in source code: https://github.com/iconify/tools/blob/master/src/export/component.js

**Comment by aivenkimmob** [comment]
Very nice, thanks for the quick response! I was almost starting to create my own script for that but I'll rather use the existing API :+1:
