### ISSUE TITLE
is it possible to support stroke-width?

### ISSUE THREAD

**Issue by cyber-carlos** [iconify/iconify#64]
like is:
```html
<span class="iconify" data-icon="carbon:bat" data-stroke-width="5">

<!-- or css -->
<span class="iconify stroke-5" data-icon="carbon:bat">

<style>
.stroke-5 {
  stroke-width: 5;
}
</style>
```

reference: https://iconpark.bytedance.com/official

![image](https://user-images.githubusercontent.com/50797685/109383776-ba384c00-7923-11eb-9894-1b5433fdbf9b.png)

**Comment by cyberalien** [comment]
Code you wrote is valid (second example with class and css), so you can use that if icon supports it.

But custom attributes - no. That would be very library specific. Iconify is meant to be used with any icon sets, so it should not contain any code specific to any icon set.

**Comment by cyber-carlos** [comment]
Okay, I get it, thanks for your reply and library.
