### ISSUE TITLE
What is your privacy policy and where is it located?

### ISSUE THREAD

**Issue by Explosion-Scratch** [iconify/iconify#65]
(self explanatory)

**Comment by cyberalien** [comment]
Good question. It will be added to new website. I'll keep this ticket open to make sure I don't forget.

As for policy itself, website doen't do any tracking, except for statistics used by Google Analytics, which are used simply to get idea where users are coming from and how many users are visiting. Website doesn't even have option to log in, so there is no private data to deal with.

**Comment by cyberalien** [comment]
Oh, and there is one cookie, which is set by Cloudflare. I have no idea what it is for and have no option to disable it, but also cannot access it. It is not passed from Cloudflare servers to Iconify servers.

**Comment by cyberalien** [comment]
New version of website has privacy policy: https://iconify.design/privacy/

**Comment by Explosion-Scratch** [comment]
Thanks for implementing this!
