### ISSUE TITLE
addIcon: TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by hohol92** [iconify/iconify#66]
My code:
```
import { Icon, InlineIcon, addIcon } from '@iconify/react'
import walletIcon from '@iconify-icons/system-uicons/wallet'
addIcon('wallet', walletIcon)
In jsx:
<Icon icon="wallet" />
```
An error occurs on the line with the function: addIcon('wallet', walletIcon)
What to do?

**Comment by cyberalien** [comment]
You have probably installed version 1 of component. Try version 2: `npm install --save-dev @iconify/react@beta`

**Comment by cyberalien** [comment]
New stable version of component has been released a while ago, it no longer has this error.

It also has ability to retrieve icon data from API, so no need to install `@iconify-icons/system-uicons` package, now you can use that icon as `<Icon icon="system-uicons:wallet" />`, though old method that uses icon packages is available too.
