### ISSUE TITLE
Usage with React and preserving dynamic loading

### ISSUE THREAD

**Issue by TheKnarf** [iconify/iconify#68]
I'm building an application where the enduser can add icons, as such the dynamic loading of icons from iconify is great. That way I don't need to bundle icons and can allow endusers to pick any valid Iconify icon. However my application is in React / Next.js, I currently have the following code and it mostly works but seems to fail at weird edge cases:

```
import React, { useEffect } from 'react';

const Icon : React.FC<{ icon: string; className?: string }> = ({ icon, className }) => {
  useEffect(() => {
   // Check that "process.browser" exists so that its only loaded at runtime in React
  // And not at compiletime in Next.js
    if(process.browser) {
      // Simply requiring Iconify and setting a variable seems to trigger it to replace spans with the `iconify` classname and a data-icon
      const Iconify = require('@iconify/iconify');
    }
  }, []);

  return <span className={`iconify ${className}`} data-icon={icon} />;
};

export default Icon;
```

Is there a version of Iconfiy that works with React and allow me to load icons dynamicly at run time?

**Comment by cyberalien** [comment]
Yes. See `@iconify/react-with-api` package.

Documentation: https://docs.iconify.design/implementations/react-with-api/

**Comment by TheKnarf** [comment]
Testet it out and does seem to work. :-)

But I'm also getting this warning:

```
warn  - ./node_modules/@iconify/react-with-api/dist/icon.esm.js
Module not found: Can't resolve 'cross-fetch' in '/Users/knarf/projects/dave/node_modules/@iconify/react-with-api/dist'
```

**Comment by cyberalien** [comment]
If you can't make Webpack ignore cross-fetch, try adding it as dev dependency to prevent it from being bundled.

cross-fetch is used only when you are trying to load icons on server side. If you are not explicitly loading icons on server side, icons are loaded when component is mounted, which means they are loaded only on client side and cross-fetch is not used.
