### ISSUE TITLE
Can't get iconify to work on SvelteKit

### ISSUE THREAD

**Issue by Bara-dev** [iconify/iconify#69]
This is probably an issue with Vite.

In dev:
Using the ES module icons will bring up this error: https://github.com/iconify/iconify-react/issues/19 (which afaik shouldn't be an issue with vite.)
Using the CommonJs icons works as expected.

But, when building with any adapter (or without an adapter and run preview):
I get the following error with both ES and CommonJs icons
```
Cannot find module '[...]/node_modules/@iconify/icons-twemoji/cowboy-hat-face' imported from [...]/.svelte-kit/output/server/app.js
Did you mean to import @iconify+icons-twemoji@1.1.1/node_modules/@iconify/icons-twemoji/cowboy-hat-face.js?
```

The first error has been reported reported to Vite but it ended with them using vite-plugin-icons (which is only for Vue afaik) https://github.com/antfu/vite-ssg/issues/31.

Am I missing something?

**Comment by cyberalien** [comment]
I'm confused. So ES modules don't work in dev mode, CommonJS modules don't work in production mode?

**Comment by Bara-dev** [comment]
Unless I'm doing something wrong, ES modules don't work in dev mode with the same error as in the linked issue (` Unexpected token 'export'`), while CommonJS modules work great.

In production mode neither of them work.

### Update

At the time of writing that, I figured out the issue:
For ES module icons to work you need to install them as normal dependencies (not dev). This also fixed production!

Perhaps a note for Vite/SvelteKit might help people if they encounter the same issue!
