### ISSUE TITLE
Youtube Icon Is Not A Legal Use Of Youtube's Trademark

### ISSUE THREAD

**Issue by hrichiksite** [iconify/iconify#70]
### The Youtube icon at https://iconify.design/icon-sets/mdi/youtube.html is a violation of YouTube's Trademark.

I recently contacted Youtube about using their logo in our own product, and sent them the link above, they responded 

> The link you provided has nothing to do with us, and is not a legal use of our trademark. Our official branding is available on YouTube.com/brand and all use requests should be submitted via the form on the site.

Maintainers are requested to take the required action.

**Comment by cyberalien** [comment]
You should open this issue at Material Design Icons repository: https://github.com/Templarian/MaterialDesign

**Comment by hrichiksite** [comment]
Ok, I will do that, thanks.
