### ISSUE TITLE
Svelte component

### ISSUE THREAD

**Issue by geoidesic** [iconify/iconify#72]
I notice you have React and Angular components... it would be great to have Svelte (and Vue) components too.

**Comment by cyberalien** [comment]
They are available. Documentation for components is available here: https://docs.iconify.design/implementations/components/

I don't have Angular component though. It is a third party port.

There are also alpha versions of all components, which is not in documentation. See packages/vue (for Vue 3), packages/vue2 and packages/svelte of this repository. They all support loading icons on demand from Iconify API and demos for how to use them are available in various demo packages in 'packages' directory.
