### ISSUE TITLE
Turbolinks / Turbo compatibility

### ISSUE THREAD

**Issue by ocarreterom** [iconify/iconify#73]
When I use an Iconify Bundle (without API), icons stops rendering after a visit using Turbolinks.

¿There are any workaround to enable the observer after [`turbolinks:load`](https://github.com/turbolinks/turbolinks#observing-navigation-events) event?

More info:
https://github.com/turbolinks/turbolinks
https://github.com/hotwired/turbo

Thanks! 🙌

**Comment by cyberalien** [comment]
You can try this (for Iconify 2.0):
```js
document.addEventListener("turbolinks:load", function() {
  Iconify.scan();
})
```
or this for Iconify 1.0:
```js
document.addEventListener("turbolinks:load", function() {
  Iconify.scanDOM();
})
```

**Comment by cyberalien** [comment]
I think I found a solution for this issue. Try updated version of SVG framework from attachment. It will be released later as 2.0.2, but before doing that I need to do more tests to make sure it works everywhere.

[iconify-dev.zip](https://github.com/iconify/iconify/files/6663064/iconify-dev.zip)

**Comment by cyberalien** [comment]
Should be fixed in 2.0.2.

Update doesn't do anything specific to Turbolinks, just fixes code that was causing conflicts, so changes should work with all similar software.

**Comment by ocarreterom** [comment]
@cyberalien I attachment works ok for me 👍

**Comment by ocarreterom** [comment]
Thanks for your quick response and solutions!
