### ISSUE TITLE
How to deal with framework attribute bindings, updates to custom icon component?

### ISSUE THREAD

**Issue by chasegiunta** [iconify/iconify#76]
Currently I'm wrapping using span tags in an Ember component
```
<span class="iconify" data-icon={{name}} ...attributes></span>
```
which is working great for initial loading & replacement.

Unfortunately, if I need to replace classNames or attributes on the icon element, those changes aren't reflected on the now-replaced SVG (the attribute bindings provided by the framework are lost once Iconify takes over and replaces the SPAN).

My use case is similar to:
```
<IconComponent @name="fa-solid:chevron-down" class={{if item.open 'rotate-180' 'rotate-0'}} />
```

What's the best way to approach this? Potentially, if there was a way to _leave_ the initial SPAN/I tag, I could keep the binding and observe that element for className changes, and manually add it to the SVG.

I could handle rendering each and every icon myself with the SVG functions and leverage the above strategy, but it seemed a bit more straightforward to let the SVG framework do it's thing and replace all in a batch update, rather than on a per-component basis, seeing as there could be several dozen icons on one page.

**Comment by cyberalien** [comment]
Best way to approach this is to create a native component for Ember. Recently I've streamlined all code, making it easy to reuse for various components and created 4 components with it (React, Svelte, Vue 2, Vue 3), so it should not be hard to create Ember component. I'll take a look at that.

Another solution is deal with node directly if you can get parent node. I'm not familiar with Ember, so I'll use React as example. In React you can get reference to any element, so if you get reference to parent element, you can use it to find child element and change its attribute. This is quirky, but doable.

**Comment by chasegiunta** [comment]
@cyberalien thanks for the suggestion. I'm not as hopeful as you that it's as easy to create an Ember component as React, Svelte, and Vue, but hopefully I'm wrong! 😅

**Comment by cyberalien** [comment]
I've already created it yesterday, now trying to figure out why it doesn't work as Ember addon. So it should be available soon.

**Comment by cyberalien** [comment]
Component is in attachment, everything seems to be working except for 2 things:
- Inline attribute: `<IconifyIcon @icon="mdi:home" @inline={{true}} />`
- Color attribute: `<IconifyIcon @icon="mdi:home" @color="red" />`

Problem is both require adding inline style to SVG, but there are some weird shenanigans with adding style, so it doesn't support it yet.

Both can be set by style instead: `<IconifyIcon @icon='mdi:home' style='color: red; vertical-align: -0.125em' />`

Unpack archive, add component to app/components/.

As soon as I solve issue with style and figure out why it doesn't work as addon (my primary suspect is Ember doesn't like monorepos), it will be published as `@iconify/ember` package.

[Archive.zip](https://github.com/iconify/iconify/files/6846401/Archive.zip)

**Comment by cyberalien** [comment]
Finally got it working.

Install `@iconify/ember` as dependency.

Use `<IconifyIcon />` in templates. All component properties start with `@` and `@icon` property is required.

All functions that are available in other components, such as `addIcon()`, `addCollection()` and so on are available in Ember component too. You need to import them from `@iconify/ember/components/iconify-icon`:

```js
import { disableCache, addIcon } from '@iconify/ember/components/iconify-icon';

disableCache('all');

const iconData = {
  body: '<path d="M4 19h16v2H4zm5-4h11v2H9zm-5-4h16v2H4zm0-8h16v2H4zm5 4h11v2H9z" fill="currentColor"/>',
  width: 24,
  height: 24,
};

addIcon('demo', iconData);
```

I'll do more tests, will write documentation and will publish 1.0.0 when it is ready.

**Comment by chasegiunta** [comment]
@cyberalien Great! Sorry, I'm bouncing around different things at the moment, but will leave feedback here once I get a chance to implement this component (hopefully by end of week).

**Comment by chasegiunta** [comment]
@cyberalien I'm way behind on this, I apologize, but I finally found the time to test this out. All seems to be working great!

**Comment by cyberalien** [comment]
Thank you!
