### ISSUE TITLE
"Module '\"../../../node_modules/@iconify/icons-mdi-light/alert\"' has no exported member 'alert'."

### ISSUE THREAD

**Issue by peterennis** [iconify/iconify#8]
I am trying to use Iconify in a Stencil component.

![iconify-stencil](https://user-images.githubusercontent.com/140737/61599013-88082980-abd9-11e9-8061-31ce1d221d81.gif)

This repo: https://github.com/adaept/ae-svgtest-component/tree/iconify-test

I tried various suggestions from the documentation but cannot get it to work.

Specific Code: https://github.com/adaept/ae-svgtest-component/blob/iconify-test/src/components/ae-svgtest-component/ae-svgtest-component.tsx

I tried using `import Iconify from '@iconify/iconify'` but that gives the error  `"no module exported for alert"` where alert is the test icon.

**Comment by peterennis** [comment]
From here: https://iconify.design/icon-sets/

```
Integration
Currently Iconify is available only as JavaScript library for browsers and React component.

If you use HTML or CSS syntax, Iconify loads icons from Iconify API. To use Iconify without relying on Iconify API there is possibility to host custom API and bundle icons with custom scripts or use Iconify for React.
```

StencilJS is using JSX.

My goal is to be able to include selected icons in a component, have no external
dependencies, compile, and then use the component in different apps.

**Comment by cyberalien** [comment]
You are importing icon incorrectly. Exports are not named, so correct syntax is
```
import alert from '@iconify/icons-mdi-light/alert';
```

**Comment by peterennis** [comment]
Fixed here: https://github.com/adaept/ae-svgtest-component/commit/edd4b60eec0dfa64d2b6024596671824613ad16c

However, the \<iconify-icon\> does not display and no errors are shown.

![Capture645](https://user-images.githubusercontent.com/140737/61669461-fb22a600-ac94-11e9-9e46-9711ee9efb6c.png)

How do I import \<iconify-icon\>?

**Comment by cyberalien** [comment]
You are mixing two completely unrelated things: Iconify for React and Iconify script.

See mdi-light:alert page: https://iconify.design/icon-sets/mdi-light/alert.html
Click on React tab, see code.

If you want to use React component, use React component (click "React" tab when viewing icon).
If you want to use iconify-icon tag, use Iconify script (click "HTML" tab when viewing icon).
