### ISSUE TITLE
renderHTML requires meaningless inline option - upgrade troubles to v2

### ISSUE THREAD

**Issue by schlomo** [iconify/iconify#80]
I used `getSVG()` with v1 which doesn't work in v2. The corresponding `renderHTML()` function doesn't work as [advertised](https://docs.iconify.design/icon-components/svg-framework/render-html.html) and requires (in contrast to the documentation) a customization object with `inline: true|false`.

This change [worked for me](https://github.com/schlomo/chromebooks-in-deutschland/commit/a973de63208d88b1db51c3e32620af9c338eddd7#diff-6f03c238fd7f444e394b5384bf24fdf55939c71e0e21fc2f080c3534c0482902):
![image](https://user-images.githubusercontent.com/101384/130042563-3711c207-ba99-4b12-8905-4111698f46d1.png)

I could not observe any difference between setting `inline` to `true` or to `false`, and I have the impression that the parameter is actually irrelevant.

I am not sure if the bug is in the documentation or in the code, could you please have a look?

I had to trace through the JS in the browser to figure that out and guess to try adding this parameter. The error "message" looked like this:
![2021-08-19 at 11 16](https://user-images.githubusercontent.com/101384/130043249-132053f2-a39b-45d9-88d5-74f3b9fe6238.png)

Maybe you can extend Iconify with more verbose error handling and messages?

This issue once blocked schlomo/chromebooks-in-deutschland#21

**Comment by cyberalien** [comment]
Big confirmed. Thanks for reporting, I'll fix it as soon as possible.

**Comment by schlomo** [comment]
It might also affect the `renderSVG()` function, haven't tested that.

**Comment by cyberalien** [comment]
Yes, it affects `renderSVG()` and `renderIcon()` too.

Fixed in 2.0.4.
