### ISSUE TITLE
Licensing issue with emojione icons

### ISSUE THREAD

**Issue by soryy708** [iconify/iconify#85]
Iconify offers icons from `emojione`. For example, [emojione:warning](https://icon-sets.iconify.design/emojione/warning/), and it claims that the license is `CC BY-SA 4.0`.
The license is wrong, and exposes Iconify users to litigation.

EmojiOne rebranded to JoyPixels, and their license at the time of writing is as such:
* [Free license](https://www.joypixels.com/licenses/free):
  * Intended for personal use, including students and teachers
  * Businesses can use free emoji for testing purposes only
  * Upgrade to premium license for expanded business use of free emoji
* [Premium license](https://www.joypixels.com/licenses/premium)
  * For businesses up to 249 employees. Enterprise license required for larger orgs.
* [Enterprise license](https://www.joypixels.com/licenses/enterprise)
And the pricing is as such: https://www.joypixels.com/licenses/pricing (hundreds of USD, depending on organization size)

Also, I'm not sure if the license allows Iconify to redistribute JoyPixels assets at all.

**Comment by cyberalien** [comment]
Licenses you have listed apply to newer version of icon set. Icon set offered with Iconify offers only old version, which was published before they rebranded, taken from old EmojiOne GitHub repo.

You can see licenses and icons at backup of repository here: https://github.com/cyberalien/emojione2-backup

That repository is cloned directly from EmojiOne repo, without modifications (other than title and description).

**Comment by soryy708** [comment]
From [JoyPixels FAQ](https://www.joypixels.com/faq):
> **Where can I download JoyPixels 1.x or 2.x?**
> Both are now super limited editions (aka discontinued) and no longer distributed here.
> However, there is a Github project that’s keeping Version 2 alive, called [Emojitwo](https://github.com/EmojiTwo/emojitwo). It’s maintained by a fine individual who goes by Crissov. Version 2 artwork is licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/), an open source license by Creative Commons.

If Iconify includes only version 2, then indeed there is no license issue.
Is this written anywhere? If not, then perhaps it's worth clarifying things so that other users don't get concerned about the license's nuance.

**Comment by cyberalien** [comment]
Thanks for linking EmojiTwo, didn't know someone continued development of that icon set. I will update links to that repository.

Also just noticed an error with license. As you have noticed, Iconify lists license as `CC BY-SA 4.0`, but that's license for version 1. For version 2 it should be `CC BY 4.0`. I'll fix that.

**Comment by cyberalien** [comment]
Fixed license.

Also ran update script using EmojiTwo repository as source for SVGs, icons seem to be identical to ones in my backup, so looks like there are no changes.

**Comment by soryy708** [comment]
As I mentioned earlier, perhaps it's worthwhile to clarify the license's nuance somewhere?
I couldn't find any mention of the fact you're using a specific version of emojione which has a different license from JoyPixels +3.

**Comment by cyberalien** [comment]
Icon sets now link to EmojiTwo repository and I've added version number to icon set information block on website. That should be enough to avoid confusion.
