### ISSUE TITLE
`build.js` is missing in `@iconify/utils@v1.0.11`

### ISSUE THREAD

**Issue by antfu** [iconify/iconify#86]
https://unpkg.com/browse/@iconify/utils@1.0.11/lib/svg/

The CJS version of `build.js` is somehow missing but only the ESM version

Which used to present in v1.0.10

https://unpkg.com/browse/@iconify/utils@1.0.10/lib/svg/

**Comment by cyberalien** [comment]
Thanks for reporting. Fixed and published update.

Error was caused by bad entry in `.npmignore`.
