### ISSUE TITLE
Twemoji wrong license.

### ISSUE THREAD

**Issue by the-j0k3r** [iconify/iconify#87]
Twemoji has CC BY 4.0 on site while in reality its MIT lic

![Capture](https://user-images.githubusercontent.com/31389848/139687237-6b225d84-bede-4bfc-a57b-acc432e3238c.PNG)

https://github.com/twitter/twemoji/blob/master/LICENSE

Also thanks for this project, I have the same issue as you, when I dont do custom icons/svgs for a job, using opensource for some projects is ideal, beats downloading whole libraries and browse on OS.

Thanks.

**Comment by the-j0k3r** [comment]
Also how often are the svgs updated from the projects? Seems like its been a little bit or am I mistaken?

Thanks again !!

**Comment by cyberalien** [comment]
You've linked license for package.

However, in readme of that package it states this:
> The graphics are licensed under the CC-BY 4.0

Then at the end of readme license is repeated:

> Copyright 2019 Twitter, Inc and other contributors
> Code licensed under the MIT License: http://opensource.org/licenses/MIT
> Graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/

**Comment by cyberalien** [comment]
> Also how often are the svgs updated from the projects? Seems like its been a little bit or am I mistaken?
> 
> Thanks again !!

All icons are automatically updated every few days. Currently I've set script to run on Monday, Wednesday and Friday.

**Comment by the-j0k3r** [comment]
Thanks, I clearly didn't read the huge twemoji readme and I dont understand why licenses aren't grouped together but that's not a you problem =)

Thanks again =)

**Comment by cyberalien** [comment]
Yep, those licenses can be sneaky like that. 😄
