### ISSUE TITLE
ability to add iconify collection by name

### ISSUE THREAD

**Issue by acalvino4** [iconify/iconify#89]
The readme for [collections-json](https://github.com/iconify/collections-json) shows how to load an icon set by name, quite conveniently - just something like 
```
const collection = new Collection()
collection.loadIconifyCollection('icon-set-name')
```
However, this example uses json-tools, which is deprecated and should be replaced by iconify/utils according to the documentation.  However, I don't see any examples of how to do this via the utils library. There doesn't seem to be a collections class, nor any method similar to `loadIconifyCollection`.  I see you can import a single collection like this
```
import { icons } from '@iconify-json/mdi-light';
```
but which icon set I load is determined by configuration (since I want an end user to be able to select an icon set via my site's back-end) and to achieve what I want using this syntax would have to be a dynamic import, not to mention including all the sets as individual dependencies in `package.json`. I really liked the old syntax (`loadIconifyCollection('icon-set-name')`), which is working for me using json-tools, but I like to update away from deprecated libraries when possible. Is what I'm looking for possible with `iconify/utils`? If not, consider this a feature request. I understand that if I want all the icons available that this is a 130M package, but that's really not a big deal for a server-side rendered app.

**Comment by acalvino4** [comment]
If there is a way to get what I'm looking for with `iconify/utils` that requires installing the `iconify/json` package, that's perfectly acceptable to me (in fact, that's what I'm expecting).

**Comment by cyberalien** [comment]
`@iconify-json/*` packages are just split version of `@iconify/json` package.

So you can do this:
```js
import { icons } from '@iconify-json/mdi-light';
```
or you can do this:
```js
import icons from '@iconify/json/json/mdi-light.json';
```
Difference between imports is in first example you get minimal icon data, without all info, categories, themes. Other data can be imported from same file using different named imports: 'info' for info, 'metadata' for categories and themes, 'chars' for characters map.

In second example it is full data, with info block, categories. It is identical to old `loadIconifyCollection()` function.

**Comment by cyberalien** [comment]
Currently I'm in process of rebuilding almost everything. Old code is few years old, it was made before I switched to TypeScript, so in some cases types are wrong and type definitions are missing, some functions are synchronous where they don't need to be. New code is rewritten with TypeScript, all blocking functions (such as reading and writing files) are asynchronous, supports ES modules.

Packages that are ready:
- `@iconify-json/*` are ready. They have types, correct data structure, ES support.
- Iconify Utils is ready.

Packages that are in process of being rebuilt:
- Iconify Tools is currently being rebuilt from zero. I've been working on it in last few weeks.
- `@iconify/json` package is being rebuilt. You can see new version in `next` branch of repo: https://github.com/iconify/collections-json/tree/next (also available with `next` tag at NPM). To complete move to new structure I need to finish rewrite of Tools package first. Old package has incorrect format for info blocks in icon sets. Function for converting old icon set info to correct format is available in Iconify Utils: https://docs.iconify.design/tools/utils/convert-info.html

**Comment by acalvino4** [comment]
Thanks @cyberalien,
```
import icons from '@iconify/json/json/mdi-light.json';
```
is helpful, but doesn't quite achieve the same thing that `loadIconifyCollection` did because the icon set needs to be known at compile time for es6 imports. It would be helpful to have a way to load an icon set at runtime like `loadIconifyCollection` does.
I want to do something like
```
iconSet = functionThatLoadsFromConfig
import icons from '@iconify/json/json/' + iconSet + '.json';
```
But that is not valid syntax, hence why I would find the old function helpful.

**Comment by cyberalien** [comment]
You can use `require.resolve()` to get filename, then read it:

```ts
import { promises as fs } from 'fs';
import type  { IconifyJSON } from '@iconify/types';

export async function loadCollection(prefix: string): Promise<IconifyJSON> {
    const filename = require.resolve(`@iconify/json/json/${prefix}.json`);
    return JSON.parse(await fs.readFile(filename, 'utf8'));
}
```

**Comment by acalvino4** [comment]
Indeed, and that's what I was about to do (something of that sort) - it would just be very convenient to have that function baked in as it was before. But maybe my use case is kinda fringe, idk.

**Comment by cyberalien** [comment]
Actually, I completely forgot about it, but there is a function. But it is a 2 step function:

```ts
import { locate, loadCollection } from '@iconify/json';
```

First step is locating file:
```js
const filename = locate('mdi');
```
Second step is loading it:
```js
const content = await loadCollection(filename);
```

It requires `next` version of `@iconify/json` package, which currently is not updated as often as it should be.

**Comment by acalvino4** [comment]
Oh, nice! That's exactly what I need. I just came up with the following 
```
import collections from '@iconify/json'
const set = JSON.parse(readFileSync(collections.locate(setName)))
```
which I'm guessing does basically the same thing, albeit in a synchronous manner.

**Comment by acalvino4** [comment]
I think I'll stick with my solution until you officially release the `next` version.

And just an idea - what if that `loadCollection` method could take a collection name or path; in other words, check to see if there is a matching official collection, if so perform the locate method and load, otherwise just load by path? OR maybe an additional function like `loadIconifyCollection`? 

It's up to you....but those might be some ideas for convenient syntax that would be pretty easy to implement.

**Comment by cyberalien** [comment]
It would be easy to implement, but if you already have a filename, why not just load file? Then what if there are multiple sources for icon sets? That would require custom logic anyway, making changes to `locate()` pointless.

**Comment by acalvino4** [comment]
I'm not suggesting any changes to locate - I'm suggesting a convenience modification to `loadCollection` that eliminates the need for developer to call `locate`.  It just seems like
```
import { loadCollection } from '@iconify/json'
faBrands = loadCollection('fa-brands')
```
would be a marvelously nice syntax (That's pretty much what we had to do with the old json-tools, and I'm just suggesting we keep that around).  And if someone has their own collection path, they can still use `loadCollection('path/to/my/set.json')`

**Comment by cyberalien** [comment]
Oh, I see. Yes, that makes sense.

**Comment by cyberalien** [comment]
Version 2.0 has function `lookupCollection` that does exactly that.

`await lookupCollection('fa-brands')` is identical to `await loadCollection(locate('fa-brands'))`

As of this week, version 2.0 is maintained along with version 1, so it is up to date. Install it using `@iconify/json@next`.
