### ISSUE TITLE
How to get a list of all collections in order to search for icons?

### ISSUE THREAD

**Issue by arjendejong12** [iconify/iconify#9]
Hey there!

I was wondering how you made the search function on your documentation website. 
I want to create a custom Advanced Custom Fields field (for WordPress) where users can search for icons in Iconify, similar to the existing FontAwesome Field add-on:
![image](https://user-images.githubusercontent.com/10572554/67011384-c4bbc200-f0ef-11e9-8b0e-5eadd72be44e.png)
We have our own API set up. I'd like to know if there are any functions available in Iconify to get a list of all available collections. Do you just search for icons whose names contain the search parameter and return them?

**Comment by cyberalien** [comment]
Search engine is not part of public API. I do plan to create script for searching icons, so it can be integrated into any software. It should have been ready by now according to my original plan, but its taking longer than expected.

When its ready it will be published here: https://github.com/iconify/icon-finder

**Comment by SavaSebastian** [comment]
Hi !

Some updates about this ?

Thanks !

**Comment by cyberalien** [comment]
It is in development.

I've implemented it as Figma plug-in (see https://github.com/iconify/iconify-figma/tree/master/ui/src ), currently working on separating that code into separate reusable library. I think it will be published in January.

**Comment by cyberalien** [comment]
API queries are now part of documentation: https://docs.iconify.design/sources/api/queries.html
