### ISSUE TITLE
Problem with version "@iconify/react": "^3.1.0"

### ISSUE THREAD

**Issue by mtr1990** [iconify/iconify#91]
Hello,

I encountered a warning when updating from version `"@iconify/react": "^3.0.1` => "@iconify/react": "^3.1.0"

`
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`
Version `"@iconify/react": "^3.0.1` worked fine until the warning appeared when I updated to `"@iconify/react": "^3.1.0"`

My working environment:
- `"next": "^12.0.3"`
- node `v14.17.3`

Thanks!

**Comment by cyberalien** [comment]
I don't see that issue. Just tested it by creating basic next.js app, adding icon component.

Are you using default next.js build script that uses Webpack?

**Comment by mtr1990** [comment]
Hi, I use Next js by default.

This is the screen console of I when I use version 3.0.1

<img width="773" alt="Screen Shot 2021-11-14 at 21 30 23" src="https://user-images.githubusercontent.com/13531993/141685675-7ec2ed11-8a7e-432c-b0e6-5045ef60fbb6.png">

Then i upgrade the package with npm command: **npm i @iconify/react@latest** => "@iconify/react": "^3.1.0

I restart the console with the command: npm run dev (next start)


and got this error:


<img width="1209" alt="Screen Shot 2021-11-14 at 21 31 11" src="https://user-images.githubusercontent.com/13531993/141685665-4485d689-8070-48a9-989d-c3b3e10e193b.png">

**Comment by cyberalien** [comment]
Can you post chunk of code from your component where you are using icon?

**Comment by mtr1990** [comment]
I use the iconify component in quite a few places

```tsx
// icons
import { Icon, IconifyIcon } from '@iconify/react';
// @mui
import { SxProps } from '@mui/system';
import { Box, BoxProps } from '@mui/material';

// ----------------------------------------------------------------------

interface Props extends BoxProps {
  sx?: SxProps;
  icon: IconifyIcon;
}

export default function Iconify({ icon, sx, ...other }: Props) {
  return <Box component={Icon} icon={icon} sx={{ ...sx }} {...other} />;
}

```

Usage 

```tsx
import { Iconify } from '../components';

<Iconify icon={checkmarkOutline} width={28} height={28} />

or

<Iconify icon="carbon:cube" />

```

**Comment by cyberalien** [comment]
Here is an error:

```js
export default function Iconify
```

You are exporting it as `default`, not a named export. But importing it as named import.

**Comment by mtr1990** [comment]
Hi, Is this a change in version 3.1.0 or is it my code? Because it doesn't warn at version 3.0.1



```tsx
// in `src/components/Iconify.tsx`

import { Icon, IconifyIcon } from '@iconify/react';
import { SxProps } from '@mui/system';
import { Box, BoxProps } from '@mui/material';

// ----------------------------------------------------------------------

interface Props extends BoxProps {
  sx?: SxProps;
  icon: IconifyIcon;
}

export default function Iconify({ icon, sx, ...other }: Props) {
  return <Box component={Icon} icon={icon} sx={{ ...sx }} {...other} />;
}
```



```tsx
// in src/components/index.ts

export { default as Iconify } from './Iconify';

```
```tsx
import { Iconify } from '../components';

<Iconify icon={checkmarkOutline} width={28} height={28} />

or

<Iconify icon="carbon:cube" />
```

**Comment by cyberalien** [comment]
Tried your code, it works fine with Node 14.7.

**Comment by mtr1990** [comment]
I have fixed this problem, thanks for your patience.

But until now, I still don't understand, after upgrading the package, the warning like above occurs. 


For example, I used this before, and it worked fine

```js

import { ThemeColorPresets } from '../src/components';

```

But after upgrading the icon pack

I need to fix this to turn off the warning


```js

import ThemeColorPresets from '../src/components/ThemeColorPresets';

```

Please close this topic.

Thank you

**Comment by cyberalien** [comment]
I don't understand it either.

My guess is some part of build process for whatever reason imports CommonJS file, while expecting ES module. Maybe it is caused by `exports` field in `package.json`, which some outdated bundlers fail to handle, but for old software there are also `main` and `module` fields. Next.js build process uses modern version of Webpack, so it should work fine.

If I could emulate that bug, I'd do my best to find out which part of build process is bugged, but I'm not getting any errors. Tried with Node 14.17.3, but not getting any errors either.

Oh well, at least there is a workaround.
