### ISSUE TITLE
如何加载iconify所有远程图标

### ISSUE THREAD

**Issue by yudan215** [iconify/iconify#98]
我现在主要是有一个这样的功能·用户可选Carbon、CoreUI Free、BoxIcons、Jam Icons等包（最好是远程库，不需要打包在项目内）,这个如何加载远程的？VUE3.0

用户可在里面选择喜欢的图标，将图标字符串标识存储到后端·后端根据用户选择的·渲染到同一个项目的不同位置·ICONIFY是可以动态只引入选择的吗？

**Comment by cyberalien** [comment]
If translation is correct, you are asking how to dynamically load icon based on user selection?

Then all you have to do is use icon name, such as "carbon:account": `<Icon icon="carbon:account" />`

**Comment by yudan215** [comment]
> If translation is correct, you are asking how to dynamically load icon based on user selection?
> 
> Then all you have to do is use icon name, such as "carbon:account":

How to remotely load all types of icons for iconify

**Comment by cyberalien** [comment]
I'm not sure what you mean by "types of icons".

Do you want to load list of icon sets? You can get it from API `https://api.iconify.design/collections`, you can also get it from NPM package `@iconify/collections` or from GitHub repository: https://github.com/iconify/collections-json Documentation is available here: https://docs.iconify.design/icons/collections.html 

Do you want to load list of icons? You can load it from API, like this: `https://api.iconify.design/collection?prefix=mdi` Documentation is available here: https://docs.iconify.design/api/queries.html

Do you want to get data for all icons in icon set? See https://docs.iconify.design/icons/json.html or https://docs.iconify.design/icons/all.html
