### ISSUE TITLE
Vue Component: Events do not work

### ISSUE THREAD

**Issue by floorfi** [iconify/iconify#99]
Hi there!

I just started using Iconify, replacing the use of plain Font Awesome (with the official Vue Library).

I'm trying to bind a click event to an Iconify icon. Unfortunately this does not work as intended.
By binding a simple "@click"-event to the Iconify icon component, no event handler is bind to the rendered svg-Element.

```Vue
// Old one, works
<font-awesome-icon icon="info-circle" @click="test"/>

// New one, does not work
<Icon icon="fa-solid:info-circle" @click="test"/>
```

**Comment by cyberalien** [comment]
Vue 2 or 3?

**Comment by floorfi** [comment]
This is about Vue 2

**Comment by cyberalien** [comment]
That's expected behaviour for Vue 2 component. Passing events in functional components in Vue 2 is not possible.

It works correctly in Vue 3 component.

**Comment by floorfi** [comment]
That's sad.

Maybe than the documentation should be edited, because there is mentioned, that this is possible:
https://github.com/iconify/iconify/tree/master/packages/vue2#other-properties-and-events
"...you can do stuff like assigning click event..."

**Comment by cyberalien** [comment]
Thanks for noticing! Readme updated.
